### ISSUE TITLE
[Map on frontpage] Unpublished RSS feed items and published feeds are appearing on maps

### ISSUE THREAD

**Issue by mishari** [OpenDevelopmentMekong/opendev-wptheme#10]
<a href="https://github.com/acorbi"><img src="https://avatars.githubusercontent.com/u/384894?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [acorbi](https://github.com/acorbi)**
_Sunday Feb 01, 2015 at 19:21 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/oeco/opendev-wptheme/issues/13_

---

Map is showing unpublished and published RSS feed items (imported using RSS Multi Importer plugin). Clicking on the unpublished items causes a 404 error, and clicking on the published items causes a script error:
![c users dan pictures odm child theme rss map display issue2 013115](https://cloud.githubusercontent.com/assets/384894/5993398/6e09b188-aa4f-11e4-865f-03e3f58122da.png)
The error in the screenshot references the **isNullOrEmptyString** which is exposed by the wpckan plugin (utils/wpckan_utils.php). 
1. Is some reference missing? 
2. Why does the child theme reference this function directly?
3. SHould RSS Feeds be shown in the map?

**Comment by mishari** [comment]
<a href="https://github.com/acorbi"><img src="https://avatars.githubusercontent.com/u/384894?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [acorbi](https://github.com/acorbi)**
_Sunday Feb 01, 2015 at 22:53 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

---

I could reproduce the issue and fixed it by activating wpckan plugin, was disabled. 

Also, under Jeo Settings there is an option to select the post types used by the mapping function. This should be tuned accordingly.
![bildschirmfoto 2015-02-01 um 22 21 43](https://cloud.githubusercontent.com/assets/384894/5994291/657aaf68-aa6d-11e4-918a-a473a7895586.png)

**Comment by mishari** [comment]
<a href="https://github.com/DBishton"><img src="https://avatars.githubusercontent.com/u/1206387?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [DBishton](https://github.com/DBishton)**
_Tuesday Feb 03, 2015 at 11:26 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

---

Hi both,

Having followed your instructions Alex, we are still seeing feeds and feed items in our front page map. There is also a display issue in the 'summary' view of these items, see below.

![image](https://cloud.githubusercontent.com/assets/1206387/6019350/2eaa4654-abd2-11e4-8e30-9bb6345d9788.png)

**Comment by mishari** [comment]
<a href="https://github.com/miguelpeixe"><img src="https://avatars.githubusercontent.com/u/820752?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [miguelpeixe](https://github.com/miguelpeixe)**
_Friday Feb 06, 2015 at 17:54 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

---

Where does "feeds" come from? Is it a post type? I'm not familiared with this plugin's behaviour.

About the last image @DBishton sent, I will fix the style for clusterized markers. The number 4 you are seeing is a cluster with 4 posts that are from the same location (or very close, dependeding on the map zoom)

**Comment by mishari** [comment]
<a href="https://github.com/miguelpeixe"><img src="https://avatars.githubusercontent.com/u/820752?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [miguelpeixe](https://github.com/miguelpeixe)**
_Friday Feb 06, 2015 at 20:04 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

---

The marker cluster style has been fixed 068cb623580e7bf485a4a910e66793930f063b04

**Comment by mishari** [comment]
<a href="https://github.com/DBishton"><img src="https://avatars.githubusercontent.com/u/1206387?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [DBishton](https://github.com/DBishton)**
_Wednesday Feb 11, 2015 at 11:28 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

---

Thanks Miguel.

The plugin we are using to aggregate news is https://wordpress.org/plugins/wp-rss-multi-importer/.

**Comment by acorbi** [comment]
@DBishton @Numnov I believe this Issue has been solved. Can we please close this Issue?
