### ISSUE TITLE
Highlight current taxonomy in Topic Pages

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#100]
In the Topic Areas box found in Topic Pages such as http://opendevelopmentmekong.net/topics/environment-and-natural-resources/, the current taxonomy is only highlighted using bold text.

This should be highlighted better. The idea would be to come up to 2-3 suggestions for highlighting, discuss them with the team and choose one.

![bildschirmfoto 2015-05-21 um 12 00 20](https://cloud.githubusercontent.com/assets/384894/7746260/2cf54d26-ffb1-11e4-8e45-d8322d55671e.png)

**Comment by acorbi** [comment]
Suggestion would be to change the text color to the country site's color

**Comment by Huyeng** [comment]
is it what you expected?
![screenshot_27](https://cloud.githubusercontent.com/assets/6613530/8002473/7133980a-0b99-11e5-999a-8334109f817f.jpg)

**Comment by acorbi** [comment]
@Huyeng That would be good for me! I would suggest that you commit & merge the changes and if @DBishton , @Numnov or anyone has a better proposal, then we open a new Issue.

**Comment by Huyeng** [comment]
Sounds good. 

Done!
