### ISSUE TITLE
Add "Revision" on back end 

### ISSUE THREAD

**Issue by vatana92** [OpenDevelopmentMekong/opendev-wptheme#1014]
Please add Revision on back end of News archive and Topics.

**Comment by acorbi** [comment]
Hi vatana.
2 comments regarding your feature request:
- please log it on the wp-odm_theme repository. this repository is not maintained anymore.
- please provide a **detailed** description of what you are requesting. i do not understand what you mean by
  > Please add Revision o­n back end of News ar­chive and Topics.
  --
  Gesendet von der myMail-App für Android Montag, 05 September 2016, 09:11vorm. +02:00 von Vatana  notifications@github.com :

**Comment by vatana92** [comment]
![capture](https://cloud.githubusercontent.com/assets/19201022/18240324/281e84c8-7375-11e6-81a4-e954e5fb0e47.JPG)
Hi acorbi

Before I can trace who have working on the "Edit news articles" and "Edit topics" by seeing on "Revision" navigation. But now there is no Revision on back-end as before, and I cannot see who has worked on particular topic or news before me anymore.

**Comment by acorbi** [comment]
Hi Vatana, i believe you can show that information by checking the corresponding box on **Screen Options** on the top-right corner of the Wordpress dashboard.

**Comment by Huyeng** [comment]
Closed the issue and moved to new theme.
https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/377
