### ISSUE TITLE
Lost bullet point on the Topic page navigation on Khmer site

### ISSUE THREAD

**Issue by vatana92** [OpenDevelopmentMekong/opendev-wptheme#1015]
![screenshot_5](https://cloud.githubusercontent.com/assets/19201022/23847508/4834d756-0805-11e7-8b46-dccdc5cb5fe1.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/19201022/23847509/48362408-0805-11e7-8d26-3603386fe18e.png)

**Comment by Huyeng** [comment]
Move to https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/779
