### ISSUE TITLE
Print function doesn't work in full screen mode

### ISSUE THREAD

**Issue by punwath** [OpenDevelopmentMekong/opendev-wptheme#1016]
When I click the prints button in the full-screen mode of map explorer, there is nothing happen and it shows like this: 
![image](https://user-images.githubusercontent.com/18112596/28156463-09bf7f52-67dd-11e7-92ff-4f833ba70965.png)
However, if I turn off the full-screen mode, the print function works well. 
![image](https://user-images.githubusercontent.com/18112596/28156524-51c899c8-67dd-11e7-9ce9-21c2777e8553.png)

**Comment by acorbi** [comment]
@punwath can you please specify which browser are you using? Thanks

**Comment by Huyeng** [comment]
Thanks @punwath for raising this issue. 
@acorbi, to produce the error:
- Go to Map explorer
- Click view full screen
- Click print map
- Then you will see the error as @punwath reported. 
I'm taking a look now.

**Comment by Huyeng** [comment]
Move to https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/1097
