### ISSUE TITLE
Integrate ODC's contact form

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#103]
Currently, http://opendevelopmentmekong.net/contact/ (and also the contact section of the country sites) just contains a link to an email adress. Improve this page by adding a contact form similar to the one used on ODC site. For this, existing Wordpress contact form plugins can be identified.
![screen shot 2015-05-21 at 7 05 50 pm](https://cloud.githubusercontent.com/assets/384894/7748283/5b95ea70-ffc3-11e4-8d50-8e406fe9138c.png)

**Comment by acorbi** [comment]
@Huyeng @DBishton Can anybody paste the link to the contact form on the ODC Site we just spoke about? In http://cambodia.opendevelopmentmekong.net/contact/ there is nothing

**Comment by acorbi** [comment]
2 levels of implementation possible:
1. Just 1 contact form on http://cambodia.opendevelopmentmekong.net/contact/ 
2. A Feedback/Contact/Ideas/Issues button all over the site

#1 should be adressed first.
NOTE: @Huyeng states that plugin used on ODC site does not support multisite so it needs to be improved/fixed, or an alternative should be found.

**Comment by Huyeng** [comment]
I have already improved the Contact form plugin to be supported with the multiple site and multiple language. 

When I'm coding to add the form of contact into contact page, I have a few questions appeared in my head, "Do we still need a contact page while there is a button of Contact form fixed on the left hand side every page? What are they different? Don't they duplicate for [#1] and [#3]?"
I think that we should omit the contact menu item and its page off, what do you think?

How the form works:
-  Click the button [#1] on the left side the form will appear as [#2]

Look at what I have done below:

![contact-form](https://cloud.githubusercontent.com/assets/6613530/7982757/e6ec7c80-0ae3-11e5-93a0-04c0cefb6758.jpg)

**Comment by acorbi** [comment]
@Huyeng I would make as you suggest. Disabling the contact page sounds good for me. Or better, why don't we remove [1] and open [2] when the user clicks [3] ??? How about that?

**Comment by Huyeng** [comment]
Remove [1] or [3] either one is ok. However, for [3], we have to study that if the option of contact page in the child theme setting is set.

![screenshot_22](https://cloud.githubusercontent.com/assets/6613530/7983085/0ff27316-0ae7-11e5-8027-6d0e6c71802d.jpg)

Btw, @Terry would like to keep the contact page and add much more comprehensive information to it including map to office, phone contacts, etc. Thus, the contact information is needed.

**Comment by Huyeng** [comment]
The plugin is implemented now for all sites in different languages.
@DBishton or @PenhleakChan, does either one send the contact information to me for the contact page please? 

![screenshot_24](https://cloud.githubusercontent.com/assets/6613530/8001395/9e9d24be-0b8f-11e5-9002-f37d398d2687.jpg)
