### ISSUE TITLE
Top level tags do not appear in dropdown

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#106]
Tags that appear in dropdown on library and dataset forms do not reflect top level taxonomy category. In the example below, the first item to appear should be "Energy", but the only selectable item is "Energy policy and administration"

![image](https://cloud.githubusercontent.com/assets/1206387/7770000/adef8916-00b3-11e5-8cf9-25cbe75505a3.png)

**Comment by acorbi** [comment]
@DBishton Does this happen for ALL the top level taxonomies?

**Comment by Huyeng** [comment]
It seems not the issue at the Wordpress side. Is it the issue of wpckan or Ckan?

**Comment by acorbi** [comment]
@Huyeng Yeah, this only relates to the CKAN UI

**Comment by Huyeng** [comment]
So, the issue should post into ckanext-odm_theme repository. :P

**Comment by DBishton** [comment]
My apologies!

On Tue, May 26, 2015 at 9:34 AM, Huyeng notifications@github.com wrote:

> So, the issue should post into ckanext-odm_theme repository. :P
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/106#issuecomment-105365717
> .

## 

_Daniel Bishtonmobile:  +855968153317 | Twitter:
http://twitter.com/DanielBishton http://twitter.com/DanielBishton |
LinkedIn: http://linkd.in/Uf2YKt http://linkd.in/Uf2YKt_

**Comment by acorbi** [comment]
Fixed via https://github.com/OpenDevelopmentMekong/ckanext-odm_theme/commit/4ba9c7106df8d67c0e22d17592d0f5765db0dfa1
