### ISSUE TITLE
Improve how topics are listed

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#107]
Currently, on http://opendevelopmentmekong.net/topics/, there is a lot of unused blank space underneath the topic's title.
![bildschirmfoto 2015-05-25 um 10 04 12](https://cloud.githubusercontent.com/assets/384894/7793938/b53a6d12-02c5-11e5-9e14-4b6fb20085c2.png)

**Comment by Huyeng** [comment]
Is there any discussed idea how to improve the topic listed?

**Comment by acorbi** [comment]
@Huyeng not yet, I would suggest just to put the text body below the title as depicted here:
![b53a6d12-02c5-11e5-9e14-4b6fb20085c2](https://cloud.githubusercontent.com/assets/384894/8002687/2520adb8-0b71-11e5-9bc4-cc37eb22657e.png)

**Comment by Huyeng** [comment]
It looks good as what I thought.

**Comment by Huyeng** [comment]
I wonder that if all the topic items have the thumbnail? 
Currently, the Fishing and fisheries doesn't have feature image, so the list of topic will look like this: 
![screenshot_28](https://cloud.githubusercontent.com/assets/6613530/8004483/5b6c1482-0baa-11e5-947e-34dfef9e2614.jpg)

**Comment by acorbi** [comment]
@Huyeng I would then use a placeholder image something like:
https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fcumbrianrun.co.uk%2Fwp-content%2Fuploads%2F2014%2F02%2Fdefault-placeholder.png&f=1

**Comment by Huyeng** [comment]
Done!
