### ISSUE TITLE
CartoDB Map icons in legend box have issues

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/opendev-wptheme#114]
The icons and texts in the legend box of the CartoDB Map doesn't look nice, need to fix the stylesheet. 
![screenshot_23](https://cloud.githubusercontent.com/assets/6613530/7998341/f7adcee4-0b64-11e5-8023-f075f3a0a7dd.jpg)

**Comment by acorbi** [comment]
Now legends are presented in the layer selection sidebar. 
![screenshot from 2015-06-18 18 00 10](https://cloud.githubusercontent.com/assets/384894/8235737/eb8c3a90-15e3-11e5-8091-d3c3281f8d8a.png)
Legends can be customized using CSS, the important thing here is to define a "common" structure on how the legends' HTML is built. If we use the same structure as the one provided by cartodb ( same classes, same type of divs,...) we can achieve a consistent result
