### ISSUE TITLE
Add related news and links into the topic page

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/opendev-wptheme#118]
On the topical page, should add the related news. Provide ability for the Editors to add the other links that related into the topic pages.

**Comment by Huyeng** [comment]
Is it what we expected?
![screenshot_4](https://cloud.githubusercontent.com/assets/6613530/8031456/8d6f7136-0df8-11e5-96e8-80b386cceff1.jpg)

**Comment by acorbi** [comment]
Looks good!

**Comment by DBishton** [comment]
Looks great Huy Eng, thank you!

On Mon, Jun 8, 2015 at 4:09 PM, Alex Corbi notifications@github.com wrote:

> Looks good!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/118#issuecomment-109919739
> .

## 

_Daniel Bishtonmobile:  +855968153317 | Twitter:
http://twitter.com/DanielBishton http://twitter.com/DanielBishton |
LinkedIn: http://linkd.in/Uf2YKt http://linkd.in/Uf2YKt_

**Comment by Huyeng** [comment]
Created a widget to be able to show the related news or the latest news into the sidebar of the topic pages. 
![screenshot_6](https://cloud.githubusercontent.com/assets/6613530/8032962/b0f95f70-0e04-11e5-8d4c-04242ec872d7.jpg)

For related links (other links): 
Magic field is using to create a custom files meta box for topic post type to add the related links of the topic. The number of links can as many as needs.

![screenshot_8](https://cloud.githubusercontent.com/assets/6613530/8033028/528a82ba-0e05-11e5-8542-e151e20386c6.jpg)

**Comment by acorbi** [comment]
@Huyeng looks good, but not forget that we might need to document this on the wiki

**Comment by Huyeng** [comment]
@acorbi, is there an existing document related to topic page that I have to update, or should I create a new one?
BTW, I can't add a new page on the ODM wiki, but I can update. Last time it seems fine for me.

**Comment by Huyeng** [comment]
@DBishton, I would like to inform you that there is no post that assign to any category right now. 
If they are assigned, the related news box will be appeared.

**Comment by acorbi** [comment]
@Huyeng I have created http://wiki.opendevelopmentmekong.net/topic_pages for you to edit. You can begin adding some instructions there.
