### ISSUE TITLE
Icon isseus

### ISSUE THREAD

**Issue by mishari** [OpenDevelopmentMekong/opendev-wptheme#12]
<a href="https://github.com/Huyeng"><img src="https://avatars.githubusercontent.com/u/6613530?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Huyeng](https://github.com/Huyeng)**
_Thursday Feb 05, 2015 at 07:18 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/oeco/opendev-wptheme/issues/19_

---

Viewing the ODM website on Firefox, the icon of ODM logo and the three icons of Introductions don't not appear. Look at the screenshot below.
![icon_errors](https://cloud.githubusercontent.com/assets/6613530/6056326/ace24c72-ad41-11e4-93f6-1e3ac60f6659.png)

**Comment by mishari** [comment]
<a href="https://github.com/acorbi"><img src="https://avatars.githubusercontent.com/u/384894?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [acorbi](https://github.com/acorbi)**
_Thursday Feb 05, 2015 at 07:35 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

---

I cannot reproduce this (using FF 35.0.1). For me, the icons are being shown properly.

**Comment by mishari** [comment]
<a href="https://github.com/miguelpeixe"><img src="https://avatars.githubusercontent.com/u/820752?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [miguelpeixe](https://github.com/miguelpeixe)**
_Thursday Feb 05, 2015 at 16:20 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

---

This problem is possibly related to the site's url. When using `www` or not using it (depends on your actual URL), may cause some errors while viewing contents.

**Comment by mishari** [comment]
<a href="https://github.com/miguelpeixe"><img src="https://avatars.githubusercontent.com/u/820752?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [miguelpeixe](https://github.com/miguelpeixe)**
_Friday Feb 13, 2015 at 19:51 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

---

Any update on this issue @acorbi @Huyeng ?

**Comment by mishari** [comment]
<a href="https://github.com/acorbi"><img src="https://avatars.githubusercontent.com/u/384894?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [acorbi](https://github.com/acorbi)**
_Monday Mar 02, 2015 at 08:26 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

---

Exactly, when browsing this site **without www** icons are displayed properly.
Can this have something to do with the password protection currently active on the site?

![bildschirmfoto 2015-03-02 um 09 24 28](https://cloud.githubusercontent.com/assets/384894/6437341/f2ac14ec-c0bd-11e4-999e-163c6f369cdf.png)

**Comment by mishari** [comment]
<a href="https://github.com/mishari"><img src="https://avatars.githubusercontent.com/u/503018?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mishari](https://github.com/mishari)**
_Monday Mar 02, 2015 at 12:10 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

---

I would like to confirm @acorbi's observation, I think we can close this issue.

**Comment by Huyeng** [comment]
It seems fixed with the latest updated of the child theme.
