### ISSUE TITLE
Layout problem on topic bar

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#121]
This happens when I visit http://cambodia.opendevelopmentmekong.net with a display with resolution =  1440 x 900

![screenshot from 2015-06-08 18 02 29](https://cloud.githubusercontent.com/assets/384894/8039221/8c88198e-0e08-11e5-9793-9f8b8f0f7396.png)

**Comment by acorbi** [comment]
@Huyeng please check this out

**Comment by Huyeng** [comment]
Mine is only 1366 X 768, but it look fine.  How can it happen with the screen 1440 X 900. 
Anyways, it will fix it as it is not responsive with 1280 x 1024 and other smaller.

**Comment by Huyeng** [comment]
Fixed.
