### ISSUE TITLE
Define CSS Styles for topic pages

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#122]
We will not be defining alternative layout templates for the topic and landing pages at this stage.

However, we will be defining the common styles we wish to use on these pages so that these can be handled by CSS so that editors do not need to manually set these for each new page -- manually formatting images, captions, references, subheadings and the like is time consuming, boring, introduces a lot of potential errors, and is unnecessary.

Suggestion is that we pick one page that is correctly (completely) formatted, and we define the elements that should be standardised with CSS.

For example, http://opendevelopmentmekong.net/topics/hydropower/ or http://opendevelopmentmekong.net/topics/forests-and-forestry/

Element styling to be standardised:

Title
Subheadings
Body text font and size
Caption style
Image container dimensions
Embedded visualisation dimensions
Reference style
'Related pages' link styling -- a bulleted list of URLs (no feature box)

**Comment by Huyeng** [comment]
Can i close this issue?

**Comment by acorbi** [comment]
@Huyeng Is this code integrated in the production instance (http://opendevelopmentmekong.net) already? In that case I would close the Issue and re-open if necessary.

@DBishton Have the contents of the topic pages being reviewed already?
