### ISSUE TITLE
'Related Resources' CKAN item integration on Briefing pages

### ISSUE THREAD

**Issue by mishari** [OpenDevelopmentMekong/opendev-wptheme#13]
<a href="https://github.com/DBishton"><img src="https://avatars.githubusercontent.com/u/1206387?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [DBishton](https://github.com/DBishton)**
_Tuesday Feb 10, 2015 at 10:01 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/oeco/opendev-wptheme/issues/22_

---

This feature is working well, but requires a little tweaking in terms of display and functionality. Currently the 'Read More...' link takes users to the top of the page they are currently on, which makes it appear to do nothing. Please clarify the intended operation, and perhaps remove this link in the interim.

This is also the current behaviour when a user clicks on the title of a CKAN dataset. E.g. 'The Lower Mekong Dry Forest Ecoregion'. Suggest this takes the user directly to that dataset on CKAN rather than the current page. 

![image](https://cloud.githubusercontent.com/assets/1206387/6125218/69e5fbd6-b146-11e4-8534-f550e5e4b37b.png)

Items in more than one CKAN group are also appearing twice in this group.

See example at: http://opendevelopmentmekong.net/briefings/forests-and-forestry/

**Comment by mishari** [comment]
<a href="https://github.com/miguelpeixe"><img src="https://avatars.githubusercontent.com/u/820752?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [miguelpeixe](https://github.com/miguelpeixe)**
_Thursday Feb 12, 2015 at 21:39 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

---

Hi @DBishton 

This duplication of datasets is a bigger design issue. I thought the groups were more of a major categorization, that datasets wouldn't be part of multiple groups. Not being the case, we might need to think other visualization for this section. This design only makes sense if we see a clear separation between the datasets, something that doesn't intersect. Not only the duplication of content, but "Cambodia" and "Library" being in the same taxonomy group of this section is a bit strange looking.

**Comment by mishari** [comment]
<a href="https://github.com/DBishton"><img src="https://avatars.githubusercontent.com/u/1206387?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [DBishton](https://github.com/DBishton)**
_Thursday Feb 26, 2015 at 12:06 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

---

Hi @miguelpeixe, we do need to resolve this duplication issue, and present these resources in a way that does not take up so much screen real estate. @acorbi -- do you have a suggestion on the duplication issue? My suggestion for the screen space would be a more 'collapsed' view as default?

See the screenshot below when many items are associated with a briefing page -- some content of the page needs to be visible, regardless of the number of related resources.

![image](https://cloud.githubusercontent.com/assets/1206387/6391605/94b84d2c-bdea-11e4-83af-708377703dea.png)

**Comment by mishari** [comment]
<a href="https://github.com/WillieShubert"><img src="https://avatars.githubusercontent.com/u/3870349?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [WillieShubert](https://github.com/WillieShubert)**
_Friday Feb 27, 2015 at 21:57 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

---

As Miguel noted, the duplication of content in CKAN is the bigger issue causing the duplication since the same content can be found across multiple folders. This is not a design issue nor is it a JEO issue but rather a content structure issue that must be addressed by the persons responsible for CKAN content management. 

Trying to solve this issue with a design change will result in the reduction in the quality of two systems  (Wordpress and CKAN) in order to cover over the problem about how content is organized in CKAN.

**Comment by mishari** [comment]
<a href="https://github.com/acorbi"><img src="https://avatars.githubusercontent.com/u/384894?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [acorbi](https://github.com/acorbi)**
_Monday Mar 02, 2015 at 08:22 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

---

@DBishton yeah, this is a tricky one. As i see it (and @WillieShubert stated), it would be complex to solve this programatically. On the other hand i do not see clearly how contents could be re-structured in CKAN in order to remove this duplicity ( Currently it is quite consistent that datasets are assigned to a thematic group, such as Laws, and to the country group they belong to, in this example Cambodia)

@miguelpeixe Any ideas for implementing a filter that removes duplicates while retrieving datasets from CKAN per plugin's shortcodes?

**Comment by mishari** [comment]
<a href="https://github.com/acorbi"><img src="https://avatars.githubusercontent.com/u/384894?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [acorbi](https://github.com/acorbi)**
_Tuesday Mar 03, 2015 at 07:11 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

---

During discussion with @WillieShubert, we came up with a possible solution which might involve using the CKAN dataset's extra fields to store the location the information is related to in order to filter out the contents by this field and not by group, as it is currently happening. This will involve updating the wpckan with the feature described in https://github.com/OpenDevelopmentMekong/wpckan/issues/73.

The current workflow offers editors a **spatial range** field (http://wiki.opendevelopmentmekong.net/metadata#open_development_network_metadata_template) while creating/editing datasets on CKAN and content in Wordpress is being already geotagged thanks to JEO's provided functionalities.

**Comment by acorbi** [comment]
Ok, so here is what needs to be done in order to close this Issue:

**1.Decide which extra field is going to be used for geotagging:** Currently, the OD Metadata template has the **spatial range** which could be used. This field could be implemented with a multiselect dropdown box with limited input options for data consistency (Cambodia, Laos, etc...), the same as the tags are currently implemented with. 

**2. Geotag the current contents on CKAN:** For this, the import scripts on odm_utils need to be modified so every imported dataset gets the value "Cambodia" on the field described above. The script should be run again for Laws, Maps. Library should be done manually in case not all contents relate to cambodia.

**3. Change the queries on the front-end:** So the filter by field functionality implemented in https://github.com/OpenDevelopmentMekong/wpckan is used to retrieve only datasets corresponding to the country in question. I personally do not know how complex it would be to modify the child theme to do this, but I guess is no big deal.

See https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/31

**Comment by acorbi** [comment]
@DBishton @Huyeng  Regarding 2: Do you know or can you ask Margaget or Saing Chou whether the library records currently available ONLY relate to cambodia or whether some of them [also] relate to other countries.

**Comment by acorbi** [comment]
Please see also https://github.com/OpenDevelopmentMekong/ckanext-odm_theme/issues/53 and https://github.com/OpenDevelopmentMekong/ckanext-odm_utils/issues/83

**Comment by mishari** [comment]
@acorbi is this closed?

**Comment by acorbi** [comment]
@mishari @Huyeng In my understanding, this Issue would be fixed once https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/31 is fixed.

**Comment by acorbi** [comment]
@Huyeng @mishari This box is not appearing in the theme anywhere. Has it been commented? Has a decision have been taken in regads to wether if it should be re-enabled?
By the moment, and until clarified, I am taking out this Issue from the Milestone 1.2.0.

**Comment by Huyeng** [comment]
As I remembered, someone requested to disable the box because it displayed incorrectly.  
I think that we should close this issue and then post the other new one if needs.

**Comment by acorbi** [comment]
Ok, closing this Issue. Templates for Topic pages are going to be new defined.
