### ISSUE TITLE
Call to undefined function button_user_feedback_form()

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#146]
![bildschirmfoto 2015-06-14 um 21 16 51](https://cloud.githubusercontent.com/assets/384894/8150058/c24ea93a-12da-11e5-9c72-2143facab623.png)

@Huyeng everytime you call a function which is specific of a plugin, you should first check if it is available. For that you can use the function_exists function as follows:

``` php
if( function_exists('button_user_feedback_form') ){
  button_user_feedback_form();
}
```

Activating the User Feedback Form plugin makes the error dissapear, but still we should fix this Bug. Im assigning it to you.

**Comment by Huyeng** [comment]
Thanks @Alex that let me know. 
I have already updated the part by using the function_exists, but maybe in wrong place. I will fix and push the change. thanks.

**Comment by Huyeng** [comment]
fixed.
