### ISSUE TITLE
Improve news container

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#149]
Break news into categories, filter those Posts by tag ( cambodia, vietnam, laos, ... )
- [ ] Check if the current tags on WP are being used or not http://opendevelopmentmekong.net/wp-admin/edit-tags.php?taxonomy=post_tag&paged=2
- [ ] Define 6 Tags (Mekong, Cambodia, Vietnam....)

The news container should be configured to consider specific tags and create one tab for each of them.
Posts imported from RSS Feeds will be tagged automatically by country and one tab will be offered for each of the tags.
Increase the number of headlines shown at the same time
Add thumbnails for those 
Optimally present also 3/4 news below the map

The idea is to replace the way news are being presented now and integrate them into the map box.
![hackpad com_r0bhpof1xeb_p 221970_1433924071167_bildschirmfoto 2015-06-10 um 10 14 14](https://cloud.githubusercontent.com/assets/384894/8159385/636de9a8-1366-11e5-9ed3-3424974b124f.png)
![hackpad com_r0bhpof1xeb_p 221970_1433925051369_bildschirmfoto 2015-06-10 um 10 29 37](https://cloud.githubusercontent.com/assets/384894/8159387/65f12d48-1366-11e5-9224-58e74cec53d8.png)

**Comment by Huyeng** [comment]
Here is new look of news container: 
![screenshot_25](https://cloud.githubusercontent.com/assets/6613530/8423082/40ccf368-1f0e-11e5-8d4a-1f58e1232f6b.jpg)
