### ISSUE TITLE
Appearance > OD > Menus: Search function for categories does not reflect all categories

### ISSUE THREAD

**Issue by mishari** [OpenDevelopmentMekong/opendev-wptheme#15]
<a href="https://github.com/DBishton"><img src="https://avatars.githubusercontent.com/u/1206387?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [DBishton](https://github.com/DBishton)**
_Wednesday Feb 25, 2015 at 11:41 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/oeco/opendev-wptheme/issues/27_

---

Some post categories that have been created in WordPress are not discoverable in the search function of Appearance > OD > Menus when adding category items.

![image](https://cloud.githubusercontent.com/assets/1206387/6369942/bdc0890a-bd1d-11e4-9703-acbd3c92fe26.png)

Category appears when searched elsewhere:
![image](https://cloud.githubusercontent.com/assets/1206387/6369957/ed37ba46-bd1d-11e4-8c87-e977024bdfc6.png)

**Comment by mishari** [comment]
<a href="https://github.com/miguelpeixe"><img src="https://avatars.githubusercontent.com/u/820752?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [miguelpeixe](https://github.com/miguelpeixe)**
_Friday Feb 27, 2015 at 18:52 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

---

I think you got the first screenshot wrong. Can you confirm that? I didn't understand the issue.

**Comment by mishari** [comment]
<a href="https://github.com/DBishton"><img src="https://avatars.githubusercontent.com/u/1206387?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [DBishton](https://github.com/DBishton)**
_Tuesday Mar 03, 2015 at 05:47 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

---

Hi @miguelpeixe,

That was indeed the wrong screenshot, my apologies. Please see below. Not all categories are found by the search function in the OD > Menus admin screen. For the example in these screen shots, I have tried search terms "Marriage", "Marr" and "Marriage and Divorce" with the same results: no results found. 

![image](https://cloud.githubusercontent.com/assets/1206387/6457138/698fe7a6-c1a3-11e4-916a-0e9ff18622fa.png)

**Comment by WillieShubert** [comment]
Are they present in the why you select view all categories?

**Comment by Huyeng** [comment]
It is wordpress function issue. It search only the top level. Yes, like Willie said, it can find in "View All."
@Dan, could we close this issue.

**Comment by acorbi** [comment]
@DBishton @Huyeng @Numnov This Issue looks like can be closed....

**Comment by DBishton** [comment]
@Huyeng @acorbi So, only parent categories can be searched in that interface, and that is a WordPress limitation? If so, this can be closed.

**Comment by acorbi** [comment]
Let's close the Issue. If Categories can be found within the "View All" view, then there is a way to workaround the problem.
