### ISSUE TITLE
Inform the user when clicking a link that takes to the Datahub

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#156]
In order to avoid confusion, users should be informed whenever they are clicking a link that will take them to https://data.opendevelopmentmekong.net. Concretelly, those links are:

The DATA and LIBRARY buttos on the main menu
![screenshot from 2015-06-18 19 43 56](https://cloud.githubusercontent.com/assets/384894/8237865/69f137a6-15f2-11e5-8a6a-c70de1894e31.png)
- [ ] Identify other buttons
## possible solutions
1. Use the tooltip used for the "Coming Soon" message presented on the top menu when the "Site in development" configuration is enabled.
2. Present a big popup message which informs the user with a text and redirects to the link after 5 seconds or so automatically.

**Comment by Huyeng** [comment]
Please give me the texts.

**Comment by Huyeng** [comment]
Which solution is chosen?

**Comment by DBishton** [comment]
@Huyeng , @acorbi: My suggestion would be that we set the target attribute of these links to "_blank" so that CKAN opens in a new tab. Then use the tooltip solution suggested by Alex above to display the following texts:

Library: "This link will take you to the Library section of the Open Development Data Hub. This will open in a new window."

Data: "This link will take you to the Open Development's datasets on the Open Development Data Hub. This will open in a new window."

Just FYI, there may be some changes to these menu items in upcoming days, but this is my suggestion for the menu items we have currently, and it will be good to test if this solution is nice from a user's perspective.

Thanks!

**Comment by acorbi** [comment]
@Huyeng While you implement this, please mind that in the future we might want to use this tooltip in other links across the wordpress frontend. An idea would be to set a particular class to those links that will show the tooltip on hover.

**Comment by Huyeng** [comment]
@acorbi, Any recommendation to implement the tooltip accross the frontend?

**Comment by Huyeng** [comment]
Add the three text boxes of tooltip the into the Open Development Setting to enter the text messages that will be pop up once hover on menu items. 
- Menu Name Box: the name of menu item in nav-menu bar that wanted the message showing once mouse hover such as Data, Library and Map Explorer.
- Text Message: the information will be showed one mouse hover.
  ![screenshot_9](https://cloud.githubusercontent.com/assets/6613530/8303514/a2887c44-19c8-11e5-9ca0-410569c905bb.jpg)

Expected Result:
![library-message](https://cloud.githubusercontent.com/assets/6613530/8281312/c9d00604-1910-11e5-85e5-e4ff15601a2f.jpg)

**Comment by acorbi** [comment]
@Huyeng That's cool. But what happens when we want to use that tooltip in other new elements that come up in the future.... In order to make this a more sustainable solution I would define a default text that will be presented for every element marked with a particular CSS class.

Suggestion for text: "This link will take you to the Open Development Data Hub. A new window will be openend"

Suggestion for class name: link-to-hub

Please, ping me on skype If you wanna discuss or you are not clear of what I mean

**Comment by Huyeng** [comment]
Good point, @acorbi. I though about this too. With this three boxes, they can add the tooltip message to specify menu item by menu label if they want. In additional, they also can the tooltip message to any element on the menu navigation by adding class 'tooltip' to menu items and add "Tooltip" into menu box name. Thus, all menu items which have class 'tooltip' will pop up the message of Tooltip.
In some case, the element on menu bar may link to the site/page beside the Data Hub. If need only a box of the tooltip, please let me know, I can comment them out.

![screenshot_10](https://cloud.githubusercontent.com/assets/6613530/8304341/1c7a9e32-19cf-11e5-8efa-7b15cf40be23.jpg)
![screenshot_11](https://cloud.githubusercontent.com/assets/6613530/8304340/1c6d996c-19cf-11e5-87a2-b18dcb7d223e.jpg)

**Comment by acorbi** [comment]
Yeah, this sounds good. Just one message for those links which take the user to the DAtahub, we do not need many different messages.

**Comment by Huyeng** [comment]
:+1:
