### ISSUE TITLE
Edits to Introductory Tiles

### ISSUE THREAD

**Issue by mishari** [OpenDevelopmentMekong/opendev-wptheme#16]
<a href="https://github.com/Numnov"><img src="https://avatars.githubusercontent.com/u/4859982?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Numnov](https://github.com/Numnov)**
_Thursday Feb 26, 2015 at 10:59 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/oeco/opendev-wptheme/issues/30_

---

Move 'introductory' tiles back to original position so that taxonomy topics can be displayed there as an interim presentation, add functionality to allow icons to be replaced.

**Comment by mishari** [comment]
<a href="https://github.com/WillieShubert"><img src="https://avatars.githubusercontent.com/u/3870349?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [WillieShubert](https://github.com/WillieShubert)**
_Friday Feb 27, 2015 at 20:49 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

---

This is a quick change. For ediging icons we propose integrating the entypo font set for changing the icons. http://www.entypo.com/ 

Please confirm that this is an acceptable solution for changing the icons. Custom icons would be a different story.

**Comment by mishari** [comment]
<a href="https://github.com/miguelpeixe"><img src="https://avatars.githubusercontent.com/u/820752?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [miguelpeixe](https://github.com/miguelpeixe)**
_Friday Feb 27, 2015 at 20:56 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

---

This is how it looks on the dashboard (the interrogation mark leads to a PDF containing all the available icons with the respective label.

![intro_text_icon_1](https://cloud.githubusercontent.com/assets/820752/6421015/d8140ace-bea9-11e4-96f2-4d7d687a3a60.png)

![intro_text_icon_2](https://cloud.githubusercontent.com/assets/820752/6421018/dc03d4ac-bea9-11e4-8491-e2272c575c06.png)

**Comment by mishari** [comment]
<a href="https://github.com/DBishton"><img src="https://avatars.githubusercontent.com/u/1206387?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [DBishton](https://github.com/DBishton)**
_Thursday Mar 05, 2015 at 11:51 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

---

Thanks @miguelpeixe,

The changes are working well and will be a nice presentation for our topical landing pages. One more critical change we need in regard to this feature is a change of location on the home page, this bar needs to appear above the geolocated news container.

![image](https://cloud.githubusercontent.com/assets/1206387/6504341/ad0a572a-c368-11e4-9318-a1d5a583ee12.png)

**Comment by mishari** [comment]
@DBishton is this what you're looking for?
![open_development_mekong](https://cloud.githubusercontent.com/assets/503018/6637167/2d82e67a-c9b2-11e4-9d35-696a2e5a9db1.png)

**Comment by DBishton** [comment]
@mishari Yes, precisely.
