### ISSUE TITLE
Some ODI content taxonomy widget URLs inactive

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#163]
Hi @Huyeng, currently two URLs are not active in the ODI content taxonomy widget.

"Infrastructure" and "Economy and Commerce" are not active. The names and slugs for the categories and topics have not been changed, and are consistent with each other. Please investigate.

![image](https://cloud.githubusercontent.com/assets/1206387/8266148/d8188d06-1746-11e5-87c4-4ca00bfb94c3.png)

**Comment by Huyeng** [comment]
The error caused by the translation tag. fixed!

**Comment by DBishton** [comment]
Hi @Huyeng,

I've noticed another, very similar symptom to the issue above, that I think may be related. Forests and Forestry page (https://opendevelopmentmekong.net/topics/forests-and-forestry/) is now not accessible via the widget. URL does not appear.

![image](https://cloud.githubusercontent.com/assets/1206387/8283139/99b028f0-191f-11e5-823b-06f9998c41e1.png)

**Comment by Huyeng** [comment]
There is no post categorized into Forests and forestry taxonomy. It means that the empty taxonomy will not appear in the widget. I noticed that the topic Forests and forestry has been categorized into the Environment and natural resources, but not  Forests and forestry.
