### ISSUE TITLE
Maps: problem behaviours

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#174]
Maps are currently displaying some problematic behaviours:

1) RSS feed items displaying:

![image](https://cloud.githubusercontent.com/assets/1206387/8374765/45bcddaa-1c22-11e5-99b2-621b8c6077fe.png)

2) Legends not appearing

3) Layers not switchable -- no controls available

4) Unrelated articles appearing -- can you investigate how these are related to the map?

![image](https://cloud.githubusercontent.com/assets/1206387/8374814/adeca0cc-1c22-11e5-8f34-2dac212b966a.png)

Map used for example above: 
https://opendevelopmentmekong.net/maps/hansen-forest-cover/#!/map=352539&story=post-348962&loc=-4.58737615344969,108.555908203125,6

**Comment by DBishton** [comment]
There are a few things going on here.

Priority should be on the RSS items, then the legends.

**Comment by acorbi** [comment]
@Huyeng @DBishton What is the status of this Issue? Are RSS Items being still shown? What about the other problems? I understand this affects the visualization of Map items (i.e https://opendevelopmentmekong.net/maps/hansen-forest-cover) but not the map explorer. Correct? How are this map pages being used? Are they part of the workflow? If they are not being used, we might consider ignoring them.

**Comment by Huyeng** [comment]
It is old issue, and also fixed.
