### ISSUE TITLE
OD Vietnam and OD Laos colour scheme changes

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#178]
Hi @Huyeng, we need to change the colour scheme for OD Vietnam and OD Laos WordPress instances.

OD Laos should receive the colour scheme that OD Vietnam currently has:
![image](https://cloud.githubusercontent.com/assets/1206387/8390909/48150c5e-1cd5-11e5-871b-780a3081bf98.png)

OD Vietnam should be updated with the colours in this logo below:
![image](https://cloud.githubusercontent.com/assets/1206387/8390914/66e41a08-1cd5-11e5-8b46-161aad27c4fb.png)

Thanks!

**Comment by Huyeng** [comment]
Color scheme of Laos and Vietnam are changed.
