### ISSUE TITLE
Update filter attribute functionality

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#181]
Attributes required to reflect updates to Datawrapper charts are being stripped by WordPress.

This is required to make adjustments to the charts.

E.g. this code:

< iframe src="//datawrapper.dwcdn.net/c1H3z/3/" frameborder="0" allowtransparency="true" allowfullscreen="allowfullscreen" webkitallowfullscreen="webkitallowfullscreen" mozallowfullscreen="mozallowfullscreen" oallowfullscreen="oallowfullscreen" msallowfullscreen="msallowfullscreen" width="100%" height="450" ></ iframe >

becomes
< iframe frameborder="0" height="450" src="//datawrapper.dwcdn.net/c1H3z/3/" width="100%" ></ iframe >

**Comment by DBishton** [comment]
@Huyeng  Have updated my comment for tags and script to display.

**Comment by Huyeng** [comment]
Fixed!
