### ISSUE TITLE
Heading tags appear incorrect

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#189]
On the Population topic page, < H4 > tags appear to apply < H3 > formatting to text.

![image](https://cloud.githubusercontent.com/assets/1206387/8407036/e9c2af26-1e8c-11e5-80af-5c4aa482d8ca.png)

![image](https://cloud.githubusercontent.com/assets/1206387/8407051/162a6aea-1e8d-11e5-9e61-0e063c757c5b.png)

**Comment by Huyeng** [comment]
@DBishton, I have checked the font of H3 and H4, their side is a bit different.
The font size of H3 is 28px while H4 is 25px.

Please have a look the image below of the two headline screenshot comparison:
![screenshot_24](https://cloud.githubusercontent.com/assets/6613530/8409325/45c42eb2-1ea1-11e5-864d-e4c9eb6ebadf.jpg)

They are different sizes. However, if you think that the headline H4 should change to be smaller, please let me know.

**Comment by DBishton** [comment]
@Huyeng Thanks for clarifying! I don't think any changes are necessary, we just may choose H5 for chart titles to differentiate them from the topic page subheadings, and save any confusion. Cheers.
