### ISSUE TITLE
WP Notice: Undefined property: WP_Query_Multisite::$loop_end 

### ISSUE THREAD

**Issue by mishari** [OpenDevelopmentMekong/opendev-wptheme#19]
<a href="https://github.com/Huyeng"><img src="https://avatars.githubusercontent.com/u/6613530?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Huyeng](https://github.com/Huyeng)**
_Wednesday Mar 04, 2015 at 09:08 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/oeco/opendev-wptheme/issues/38_

---

FYI: 
The messages below are appeared if define('WP_DEBUG', true);

Strict Standards: Declaration of Admin_Page_Framework_Walker_Category_Checklist::start_el() should be compatible with Walker_Category::start_el(&$output, $category, $depth = 0, $args = Array, $id = 0) in wp-content\themes\jeo\inc\admin\admin-page-framework.php on line 2599

Notice: Undefined index: opendev_filter_ in D:\www\ODM\wp-content\themes\jeo-odm\functions.php on line 94

Notice: Undefined property: WP_Query_Multisite::$loop_end in wp-content\themes\jeo-odm\inc\query-multisite.php on line 104

**Comment by Huyeng** [comment]
I don't think the issue still exist.

**Comment by The-Andrew-Vincent** [comment]
Yep. It does.
