### ISSUE TITLE
Remove square bullets on list of tags

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#191]
On post's pages such as https://opendevelopmentmekong.net/laos-works-to-strengthen-smes-prior-to-aec-integration/#!/story=post-352750 the list of tags is being presented on the top of the screen.

Currently, there is squared bullets being attached to the left of each bubble and should be removed by modifying the CSS and specify: `list-type-style: none;`

![bildschirmfoto 2015-06-30 um 12 23 36](https://cloud.githubusercontent.com/assets/384894/8429418/c019c3f8-1f27-11e5-88eb-e618d620b1a3.png)

@Huyeng @DBishton Do we need those bubbles there? Topic pages do not have that element... maybe just removing it is what we want.

**Comment by Huyeng** [comment]
This is the list of categories not tags. Anyways, the bullets should remove.

**Comment by acorbi** [comment]
@Huyeng got it. @DBishton Do we actually need them? Don't we want to remove them? We are providing the same information on the sidebar. In case we want to keep them, I would put them underneath the post title and also show them in the topic pages for consistency.
![bildschirmfoto 2015-07-01 um 08 38 17](https://cloud.githubusercontent.com/assets/384894/8448889/95169ae6-1fcc-11e5-8ada-a26cf13cd99a.png)

**Comment by DBishton** [comment]
Hi @acorbi and @Huyeng. We do want to keep these. They're basically breadcrumbs that help orientate a user, in addition to the taxonomy widget on the right sidebar. We want users to explore further using that one, but the breadcrumb style presentation is one that is innately familiar to a lot of users to help orientate themselves as they navigate through a site -- it shows where they've been.

I agree that we should also apply it to topic pages, but it may look a little odd just below the title and above the opening paragraph on the page -- but if you want to trial this layout, let's give it a go!

**Comment by acorbi** [comment]
@Huyeng @DBishton I have updated the code on production, this is how it looks in posts and topic pages:
![screenshot from 2015-07-01 15 43 43](https://cloud.githubusercontent.com/assets/384894/8455895/2dab839e-2008-11e5-8cf0-175db6ef6d39.png)
![screenshot from 2015-07-01 15 44 24](https://cloud.githubusercontent.com/assets/384894/8455897/3022a60c-2008-11e5-8311-605cccc636f1.png)
