### ISSUE TITLE
Design changes to "Related resources" widget

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#196]
Please update the design of the related resources widget to display CKAN issues by group. Please do this for:

"policies, laws and agreements"
"maps and data"
"publications"
"Photos and videos"

This is not necessary for news, as there is another widget that displays related news published on WP.

These groups or content types should not display if there are no records of that type associated with the page. Having the groups/content types be expandable/collapsible would be a "nice to have" feature but could be a future enhancement. 

This builds on the functionality enabled by #113

**Comment by acorbi** [comment]
@DBishton For fixing this issue, besides changing the code a bit, a series of **OD Related resources** widgets needed to be added to the **Topic sidebar** widget area https://opendevelopmentmekong.net/wp-admin/widgets.php
![screenshot from 2015-07-01 14 24 35](https://cloud.githubusercontent.com/assets/384894/8455802/8647f2c2-2007-11e5-91b5-95f2a9933029.png)
