### ISSUE TITLE
Strip out the table and list in the content after update the page or switching from html to virsual editor

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/opendev-wptheme#197]
Table that created:
![screenshot_7](https://cloud.githubusercontent.com/assets/6613530/8451813/41ff492c-2010-11e5-954d-4de17ba1b354.jpg)

Result after updating:
![screenshot_8](https://cloud.githubusercontent.com/assets/6613530/8451817/4ab3688c-2010-11e5-97da-e40213b61e07.jpg)

**Comment by Huyeng** [comment]
The problem can be solved if using this plugin: Tinymce Advanced Plugin: https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/192 as it has an option to disable removing tags.

**Comment by acorbi** [comment]
@Huyeng  By installing that plugin, would we also fix https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/181 ? In this case, we should definitely install it.

**Comment by Huyeng** [comment]
No, it doesn't solve the iframe issue, but the problem can be solved by updating the tinyMCE setting in function.php. However, the Tinymce Advanced Plugin help to prevent from striping out of the line break. It also provide the controller of table and other tool that editor easy to use without html knowledge.

**Comment by Huyeng** [comment]
The issue is not completely solved.

**Comment by Huyeng** [comment]
Fixed!
