### ISSUE TITLE
Language picker of English is disappeared once switch to other languages (Khmer)

### ISSUE THREAD

**Issue by mishari** [OpenDevelopmentMekong/opendev-wptheme#20]
<a href="https://github.com/Huyeng"><img src="https://avatars.githubusercontent.com/u/6613530?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Huyeng](https://github.com/Huyeng)**
_Thursday Mar 05, 2015 at 02:07 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/oeco/opendev-wptheme/issues/39_

---

The language option (English) on header menu is disappeared when switching to Khmer site, it displays only Khmer option. See the screenshot: 

![screenshot_4](https://cloud.githubusercontent.com/assets/6613530/6497742/4bf9f8a2-c316-11e4-83b9-c47debe12696.jpg)

**Comment by Huyeng** [comment]
Error stylesheet in opendev.css line:355. Fixed by adding "display:inline" in to #od-head #main-nav .qtrans_language_chooser li { }
