### ISSUE TITLE
Read more/Share buttons on news items appear inconsistently

### ISSUE THREAD

**Issue by mishari** [OpenDevelopmentMekong/opendev-wptheme#21]
<a href="https://github.com/DBishton"><img src="https://avatars.githubusercontent.com/u/1206387?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [DBishton](https://github.com/DBishton)**
_Thursday Mar 05, 2015 at 12:09 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/oeco/opendev-wptheme/issues/40_

---

Please see screenshot below. What causes this discrepancy?

![image](https://cloud.githubusercontent.com/assets/1206387/6504543/20243f9e-c36b-11e4-8449-b31014b21448.png)

**Comment by Huyeng** [comment]
For those news articles which have Geo location, the share buttons will be appeared, for those no geo location, only "Read More".
Should me take the share button off to make it be consistent?

**Comment by DBishton** [comment]
@Huyeng Nice work. I think it should stay as is, it's good functionality to have. As all news now being produced will be geo-located, the inconsistent presentation shouldn't be a problem. Thanks!

**Comment by Huyeng** [comment]
Ok. If so, I think the issue can close.
