### ISSUE TITLE
Menu items do not change language

### ISSUE THREAD

**Issue by mishari** [OpenDevelopmentMekong/opendev-wptheme#22]
<a href="https://github.com/DBishton"><img src="https://avatars.githubusercontent.com/u/1206387?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [DBishton](https://github.com/DBishton)**
_Thursday Mar 05, 2015 at 12:27 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/oeco/opendev-wptheme/issues/41_

---

Please see highlighted and numbered items below. ODI will provide Khmer text for items 1,2,3,5 and 6. 
![image](https://cloud.githubusercontent.com/assets/1206387/6504790/8b204dc2-c36d-11e4-88ec-af906bdca4bd.png)
![image](https://cloud.githubusercontent.com/assets/1206387/6504795/92482520-c36d-11e4-9448-3439069de429.png)

**Comment by Huyeng** [comment]
All the menu items are localized, accept the "Share a Map" that need to update small thing in parent Theme function.

**Comment by Huyeng** [comment]
All English menu items on Khmer site are translated.
