### ISSUE TITLE
Map explorer display issue for country-level WP instances

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#227]
Hi @acorbi,

There is a minor formatting issue on the map explorer for the Laos site. We have not tested the other country instances but we should check them once the cause is determined.

OD Mekong (correct) 

![image](https://cloud.githubusercontent.com/assets/1206387/8670287/e1d593ae-2a45-11e5-8142-43c73c7ce360.png)

OD Laos (incorrect)

![map explorer formatting issues odm](https://cloud.githubusercontent.com/assets/1206387/8670303/019ffbfc-2a46-11e5-8dd0-2aa56039e4a2.png)

**Comment by acorbi** [comment]
This Issue was probably related to https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/228 and now its fixed
