### ISSUE TITLE
Currently selected multisite instance should highlight in menu

### ISSUE THREAD

**Issue by mishari** [OpenDevelopmentMekong/opendev-wptheme#23]
<a href="https://github.com/DBishton"><img src="https://avatars.githubusercontent.com/u/1206387?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [DBishton](https://github.com/DBishton)**
_Thursday Mar 05, 2015 at 12:37 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/oeco/opendev-wptheme/issues/42_

---

We would like the currently selected OD instance to be highlighted in the menu. We suggest that the 'secondary' colour of each theme should be used for this -- so lime green from the logo in the example below.

![image](https://cloud.githubusercontent.com/assets/1206387/6504920/03d08cea-c36f-11e4-92d0-c28de1777a2f.png)

**Comment by Huyeng** [comment]
Fixed.
