### ISSUE TITLE
Category widget displays erroneous categories

### ISSUE THREAD

**Issue by mishari** [OpenDevelopmentMekong/opendev-wptheme#24]
<a href="https://github.com/DBishton"><img src="https://avatars.githubusercontent.com/u/1206387?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [DBishton](https://github.com/DBishton)**
_Thursday Mar 05, 2015 at 13:51 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/oeco/opendev-wptheme/issues/43_

---

Category widget displays more categories than are relevant to the given page. This feature appeared to be working correctly, but after some testing now displays as in screenshot 1. Our understanding is that it should display only selected category for the page -- the relevant categories for the briefing in the example are shown in screenshot 2. Please clarify if this understanding is incorrect.
![image](https://cloud.githubusercontent.com/assets/1206387/6505910/42def9ee-c379-11e4-9c59-c05a99e24747.png)
![image](https://cloud.githubusercontent.com/assets/1206387/6505918/59012094-c379-11e4-9ddd-6007e3967f43.png)

**Comment by mishari** [comment]
@DBishton I cannot reproduce this in my development environment. Perhaps we can deploy the latest version and see what happens?

**Comment by Numnov** [comment]
@mishari, I'll be working on this issue with you now, for the soft launch, can we get this to display  only categories relevant to the page at hand, and other top level categories. Links to category pages needs to be disabled.

**Comment by Huyeng** [comment]
I view the briefing page, I think it has a list of the category twice, one is on the top and one is on the right sidebar. @DBishton, could you explain what are the different? 

![screenshot_7](https://cloud.githubusercontent.com/assets/6613530/7020947/301b039c-dd47-11e4-8076-e93dba4e51b9.jpg)

**Comment by DBishton** [comment]
Hi @Huyeng,

I believe the categories displayed at the top of the page are the
categories that have been selected for the page. In this case, an editor
would have checked "Electricity", "Energy", "Energy policy and
Administration" for this briefing.

The bar on the should always show:
- Categories which have no parents (top level categories)
- An 'expanded' hierarchical view of all categories in the current top
  level category (e.g. every category under "Energy" in the example above)
- Highlighting of the categories applied to the page (e.g. "Electricity",
  "Energy", "Energy policy and Administration" in the example above)

Thanks!

On Tue, Apr 7, 2015 at 5:01 PM, Huyeng notifications@github.com wrote:

> I view the briefing page, I think it has a list of the category twice, one
> is on the top and one is on the right sidebar. @DBishton
> https://github.com/DBishton, could you explain what are the different?
> 
> [image: screenshot_7]
> https://cloud.githubusercontent.com/assets/6613530/7020947/301b039c-dd47-11e4-8076-e93dba4e51b9.jpg
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/24#issuecomment-90493711
> .

## 

_Daniel Bishtonmobile:  +855968153317 | Twitter:
http://twitter.com/DanielBishton http://twitter.com/DanielBishton |
LinkedIn: http://linkd.in/Uf2YKt http://linkd.in/Uf2YKt_

**Comment by mishari** [comment]
This is a problem with the configuration itself.
Before:
![widgets_ _open_development_mekong_ _wordpress](https://cloud.githubusercontent.com/assets/503018/7030381/60245966-dd8e-11e4-94a0-bf5584a141a8.png)
After:
![widgets_ _open_development_mekong_ _wordpress](https://cloud.githubusercontent.com/assets/503018/7030393/7b7574b6-dd8e-11e4-8a81-b4cc63fe5424.png)
![hydropower___open_development_mekong](https://cloud.githubusercontent.com/assets/503018/7030397/866180b8-dd8e-11e4-95ef-b0aa34260f0c.png)

**Comment by DBishton** [comment]
Thanks @mishari, 

That may explain some of the inconsistencies we were witnessing previously. However, the "OD Taxonomy" widget does not perform the functions we need it to -- please see my comment to Huy Eng above for the intended behaviour.
