### ISSUE TITLE
ODI Taxonomy widget: add bolding to URLs

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#245]
Hi @Huyeng,

Currently the ODI taconomy widget only highlights categories applied to the current page. We would like to add bold styling for other entries that are URLs, so that users can see what is accessible without having to mouse-over the whole list of items.

See screenshot below: "Forests and forestry" is a URL but this is not visually represented.

![image](https://cloud.githubusercontent.com/assets/1206387/8746306/2708d22e-2cb2-11e5-849d-764cc91d24b7.png)

**Comment by Huyeng** [comment]
There are two options to identify the taxonomy which has the hyperlink, boding or coloring style.
Please me know if the boding style is still preferred. 

![screenshot_13](https://cloud.githubusercontent.com/assets/6613530/8820421/8249406c-307f-11e5-8a37-b668db12c20f.jpg)

---

![screenshot_9](https://cloud.githubusercontent.com/assets/6613530/8820320/8dc991b8-307e-11e5-97c4-8f6a946eed3f.jpg)

**Comment by DBishton** [comment]
Hi @Huyeng, thanks for presenting these options. Looking at your two examples, I think first screenshot -- using link colors to show clickable items, and bolding to show the current page -- is the more logical and visually appealing of the two.

**Comment by Huyeng** [comment]
Done!
