### ISSUE TITLE
Related resources widget should hide file type if null or unknown

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#249]
Currently, the relted resources widget displays an empty 'bubble' if the record does not have an entered file type.

![image](https://cloud.githubusercontent.com/assets/1206387/8901317/1790823e-3472-11e5-835b-363d64ed1031.png)

This 'bubble' should not display if file type is unknown or not entered.

This can be seen on the following page: https://opendevelopmentmekong.net/topics/urban-administration-and-development/

For this CKAN record: https://data.opendevelopmentmekong.net/dataset/the-interdependence-of-transport-and-housing-development-in-the-transition-of-ho-chi-minh-city

**Comment by Huyeng** [comment]
Pleas define the type of the uploaded data source, then the issue will be solved.
https://data.opendevelopmentmekong.net/dataset/the-interdependence-of-transport-and-housing-development-in-the-transition-of-ho-chi-minh-city/resource_edit/2b9b9af5-6e86-4897-a66d-b877120f50bf

**Comment by Huyeng** [comment]
@Dan, should we close this issue?
