### ISSUE TITLE
Disable URLs on subheadings on topic pages

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#250]
Hi @Huyeng, we need to disable the automatic URLs that appear on text with <Hx></Hx> tags in topic pages. They add confusion to the page. They should remain clickable in the 'On this page' widget but be disabled in the page body.

![image](https://cloud.githubusercontent.com/assets/1206387/8902494/4944a004-347b-11e5-85b5-c73811d4dd16.png)

**Comment by Huyeng** [comment]
fixed!
