### ISSUE TITLE
Sidebar widgets appear in italic font

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#251]
On the "Environment and natural resources" topic page, the sidebar widgets currently display in italic font. https://opendevelopmentmekong.net/topics/environment-and-natural-resources/

![image](https://cloud.githubusercontent.com/assets/1206387/8949827/a8a8c97c-35e2-11e5-8c59-60964b1579c9.png)

Although it looks quite nice, this is inconsistent from the other pages. I've gone through the page content and no italics tags are being used. @Huyeng please investigate.

**Comment by HengChamroeun** [comment]
The problem is that, The article miss some HTML close tag, thus it cause the layout like that.
