### ISSUE TITLE
Add option to remove "Share a Map" item from menus

### ISSUE THREAD

**Issue by mishari** [OpenDevelopmentMekong/opendev-wptheme#28]
<a href="https://github.com/DBishton"><img src="https://avatars.githubusercontent.com/u/1206387?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [DBishton](https://github.com/DBishton)**
_Thursday Mar 05, 2015 at 14:51 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/oeco/opendev-wptheme/issues/47_

---

Currently this item appears in both header and footer menus and can not be removed. Please add the option to edit as with other menu items. Many thanks.

**Comment by Huyeng** [comment]
I found where we can disable this button. We have to go  to the Jeo Setting and Map Embedded Tool. Then, I uncheck the "Enable embed tool".

![share-map](https://cloud.githubusercontent.com/assets/6613530/6822879/96704d46-d315-11e4-8913-799ec382ad27.jpg)
