### ISSUE TITLE
Child map layer categories do not appear on the map explorer

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#285]
Hi @Huyeng, currently map layer categories that have a parent category are not appearing on the map explorer. We would like this ability -- please investigate. @acorbi if you have any knowledge of this issue or directions that may help @Huyeng solve this, please comment. Many thanks both.

**Comment by acorbi** [comment]
@Huyeng an idea would be to look into the function that returns the different categories on the map layers which is used to create the different sections on the map explorer's sidebar.

**Comment by Huyeng** [comment]
It was fixed with the last updated of new template of map explorer.
