### ISSUE TITLE
Option to remove 'Related Resources' box from briefing pages

### ISSUE THREAD

**Issue by mishari** [OpenDevelopmentMekong/opendev-wptheme#29]
<a href="https://github.com/DBishton"><img src="https://avatars.githubusercontent.com/u/1206387?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [DBishton](https://github.com/DBishton)**
_Friday Mar 06, 2015 at 06:23 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/oeco/opendev-wptheme/issues/48_

---

Also rased in issue #22, the Related Resources box takes up far too much screen space. The (fantastic) Related Resources widget offers the ability to get around this issue, but currently there is no option to remove the large box at the top of the page. This is a big usability issue, please add the ability to hide this from the page.

![image](https://cloud.githubusercontent.com/assets/1206387/6521057/d3448d52-c403-11e4-95f6-02c55240d8d3.png)

![image](https://cloud.githubusercontent.com/assets/1206387/6521063/eeda542a-c403-11e4-84b0-e62eef17af14.png)

**Comment by WillieShubert** [comment]
I don't believe that it is possible to remove the related resources window from individual pages. There are two options for keeping a resources window off of the top of the page. 
1. Don't tag any resources via the CKAN plug-in
2. Chose either sidebar or top of page presentation for all briefings pages..

It appears in the screenshot that the full view of the resources window is open rather than showing the condensed version.

**Comment by mishari** [comment]
@DBishton Could you kindly provide a URL where this happens?

**Comment by DBishton** [comment]
@mishari Sure, here: http://opendevelopmentmekong.net/briefings/forests-and-forestry/

**Comment by DBishton** [comment]
@WillieShubert Hi Willie, can you describe where it is possible to choose between sidebar and top of page presentation? In our testing we have found we are able to add or remove the sidebar widget from pages, but no option to de-select or hide the top of page presentation. Thank you.

**Comment by WillieShubert** [comment]
@DBishton I believe the selection for the sidebar vs top bar presentation is in this menu:  appearances --> widgets. I can't say for sure since I no longer have access to the site.

**Comment by Numnov** [comment]
@mishari , This is not configurable in the OD admin interface -- please temporarily hide Related Resources from the page until the feature can be added.

**Comment by mishari** [comment]
@DBishton so just to confirm, this is the behaviour that you would like me to enable?
![forests_and_forestry___open_development_mekong](https://cloud.githubusercontent.com/assets/503018/6917175/73dbf968-d7cc-11e4-9484-c05e5ac43ae0.png)

**Comment by DBishton** [comment]
@mishari Exactly. Thanks!

On Tue, Mar 31, 2015 at 5:37 PM, Mishari Muqbil notifications@github.com
wrote:

> @DBishton https://github.com/DBishton so just to confirm, this is the
> behaviour that you would like me to enable?
> [image: forests_and_forestry___open_development_mekong]
> https://cloud.githubusercontent.com/assets/503018/6917175/73dbf968-d7cc-11e4-9484-c05e5ac43ae0.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/29#issuecomment-88036337
> .

## 

_Daniel Bishtonmobile:  +855968153317 | Twitter:
http://twitter.com/DanielBishton http://twitter.com/DanielBishton |
LinkedIn: http://linkd.in/Uf2YKt http://linkd.in/Uf2YKt_
