### ISSUE TITLE
News Explorer link on picture & share not working

### ISSUE THREAD

**Issue by chris-aeviator** [OpenDevelopmentMekong/opendev-wptheme#321]
When clicking on the new's picture in news explorer, the user is redirected to "undefined" url and see's the 404 Page.

When clicking on the picture, the user should be redirected to the news article, as it happens when clicking on the title or read more button.

Same happens when clicking the share button.

**Comment by Huyeng** [comment]
the function of sharing post on the NE doesn't work well, so I decide to turn it off and use social icon of Facebook, Tweet and G+ instead. Let me know if you all thought that they should take away.
