### ISSUE TITLE
Searchbar visual fixing

### ISSUE THREAD

**Issue by kathi-aeviator** [OpenDevelopmentMekong/opendev-wptheme#326]
1. background-color should be white --> see ckan search-bar
2. search icon instead of "SEARCH" --> see ckan search-bar
3. BUG: after using the search once icon is visable

@chris-aeviator the best option would be to "integrate" (not technically) the ckan searchbar on wp --> please adapt the visuality!

<img width="406" alt="bildschirmfoto 2016-01-05 um 10 57 57" src="https://cloud.githubusercontent.com/assets/15011163/12112197/4f5ab31c-b39b-11e5-9881-69486d00469d.png">

blindtext should be e.g. : "search all ..."

**Comment by Huyeng** [comment]
Fixed in issue: #355
