### ISSUE TITLE
Cleanup unused configuration variables

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#328]
After the implementation of the new navigation concept, some configuration variables for the wordpress theme are not used anymore, clean up..
- Site in development
- Message for site constructing
- Tooltip Message 1
- Notice Message appear above the slider
- Message for pages constructing
- Enable dropdown box of the country menu
- Show site intro texts
- Introduction texts
- Introduction text 1
- Introduction text 2
- Introduction text 3

**Comment by Huyeng** [comment]
All the configuration variables can remove, but the  "Tooltip Message" and "Notice Message appear above the slider" should keep them, they will need in used in some times.

**Comment by acorbi** [comment]
thanks @Huyeng! I will ammend the PR then...
