### ISSUE TITLE
Integrate language switcher on top bar

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#329]
WP websites can have multiple languages. In those sites with multiple languages, analog to the current ODC site, there should be a language switcher on the topbar.

![screenshot from 2016-01-05 11-03-41](https://cloud.githubusercontent.com/assets/384894/12112309/18b21660-b39c-11e5-9c31-5082ad1382a1.png)

This issue is related to https://github.com/OpenDevelopmentMekong/ckanext-odm_nav/issues/9

**Comment by chris-aeviator** [comment]
Let's coordinate on -->

https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/541
