### ISSUE TITLE
Styling Newscontainer

### ISSUE THREAD

**Issue by kathi-aeviator** [OpenDevelopmentMekong/opendev-wptheme#331]
1. chronologically arrange of separate entries showen in layout:

<img width="945" alt="151216_news_01" src="https://cloud.githubusercontent.com/assets/15011163/12112631/1b3ca7b8-b39e-11e5-9dd3-475571932c0d.png">
<img width="968" alt="151216_news_02" src="https://cloud.githubusercontent.com/assets/15011163/12112632/1b457ca8-b39e-11e5-8957-9c25b5313c25.png">
- changing basemap is optional

**Comment by Huyeng** [comment]
I think I can close it now. if there is an issue relevant, please create new one.

**Comment by kathi-aeviator** [comment]
Closed issue.
