### ISSUE TITLE
Insert blip of the Logo to country navigation [optional]

### ISSUE THREAD

**Issue by kathi-aeviator** [OpenDevelopmentMekong/opendev-wptheme#333]
Insert blip of the Logo to country navigation for each country on the right side of it

<img width="142" alt="bildschirmfoto 2016-01-05 um 11 28 44" src="https://cloud.githubusercontent.com/assets/15011163/12112894/b167ec60-b39f-11e5-8682-3fd03781c464.png">

Fast scribble:
<img width="155" alt="bildschirmfoto 2016-01-05 um 11 46 07" src="https://cloud.githubusercontent.com/assets/15011163/12113274/fcdcf7b0-b3a1-11e5-8f26-0a87292ca437.png">

**Comment by acorbi** [comment]
@kathi-aeviator can you please post a screenshot of the "blip" ?

**Comment by kathi-aeviator** [comment]
@acorbi  screenshot is coming!

**Comment by kathi-aeviator** [comment]
@acorbi screenshot is updated!

**Comment by chris-aeviator** [comment]
@kathi-aeviator @DBishton 

is this still on the table/wanted?

**Comment by prustar** [comment]
@chris-aeviator there has been discussions over emails, I'm not sure what the final decision is on this. There have been two different specs offered by @Huyeng and @jpeizer1 see below. I suggested having a 'tour' function to explain the site to users but not sure if this is within the remaining scope of your work. 

![update-odm-homepage 1](https://cloud.githubusercontent.com/assets/14996905/13596003/d6ede22c-e50f-11e5-8d5d-8cf28f88c01e.jpg)
![descriptive-strawman](https://cloud.githubusercontent.com/assets/14996905/13596012/e5884458-e50f-11e5-829a-47d24a459dfb.jpg)

**Comment by chris-aeviator** [comment]
A tour would have to be implemented more interactively, as nobody is going to read introduction text. But out of the scope of this issue. 

@DBishton what is the outcome of the small logo discussion?
