### ISSUE TITLE
Laws Page: Make pagination prev/next global for all tables

### ISSUE THREAD

**Issue by chris-aeviator** [OpenDevelopmentMekong/opendev-wptheme#336]
On laws page Prev/Next function should be implemented like "show x entries" function.

The laws page consists of single tables which are controlled by datatables jquery plugin.

The show entries is a simple html dropdown which changes the value of all (hidden) "show entries" in the single tables by jquery.

Same functionality should by applied to prev/next function

![image](https://cloud.githubusercontent.com/assets/11522213/12113933/759bfde6-b3a6-11e5-97a3-dd9249aadfe3.png)

**Comment by acorbi** [comment]
Fixed via https://github.com/OpenDevelopmentMekong/opendev-wptheme/commit/b69cd9d3570ca6ea56b20605eda5dbaf7f9532dc
