### ISSUE TITLE
Non logical hover function on ODC

### ISSUE THREAD

**Issue by kathi-aeviator** [OpenDevelopmentMekong/opendev-wptheme#337]
When hovering the "Opendevelopment" of the logo on ODC there is a minimal color changing thats not logical – please delete that.

<img width="647" alt="bildschirmfoto 2016-01-05 um 12 24 06" src="https://cloud.githubusercontent.com/assets/15011163/12114118/a058c7c0-b3a7-11e5-8acc-1332531e1844.png">

**Comment by chris-aeviator** [comment]
fixed, also checked other country sites
