### ISSUE TITLE
Undefined line on Myanmar,Thailand und Vietnam, Laos

### ISSUE THREAD

**Issue by kathi-aeviator** [OpenDevelopmentMekong/opendev-wptheme#339]
<img width="1132" alt="bildschirmfoto 2016-01-05 um 12 30 29" src="https://cloud.githubusercontent.com/assets/15011163/12114211/46d3ca46-b3a8-11e5-9c87-917cce0687b8.png">

**Comment by chris-aeviator** [comment]
fixed by https://github.com/OpenDevelopmentMekong/opendev-wptheme/commit/0fc06806644b7cf8c715c96d61481cbea07596ab
