### ISSUE TITLE
Adapt content area to small screen sizes

### ISSUE THREAD

**Issue by chris-aeviator** [OpenDevelopmentMekong/opendev-wptheme#344]
![image](https://cloud.githubusercontent.com/assets/11522213/12114986/c19b9ece-b3ae-11e5-9345-031b57864f50.png)

Like in the screenshot the content area should be centered also on small screen sizes

**Comment by kathi-aeviator** [comment]
@chris-aeviator please declare every issue into Milestone 1.3.0!

**Comment by acorbi** [comment]
![screenshot from 2016-01-10 14-55-14](https://cloud.githubusercontent.com/assets/384894/12221816/46008414-b7aa-11e5-85d0-cd41ff625d03.png)

On my laptop 1340px width, the layout seems to be stripped on the right.

**Comment by kathi-aeviator** [comment]
@acorbi you can adjust that on your viewportsize by narrow the first column . If there are problems with the width with the headlines - is it possible from your size to shorten the headline-text with "..."?
I think that would be the clearest and fastet way.

**Comment by chris-aeviator** [comment]
**lets follow up on https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/346**

**Comment by chris-aeviator** [comment]
fixed all header specific bug's on window-width-reduction, issues described in this topic have mainly been fixed with #346

_before fix_
![bildschirmfoto 2016-02-29 um 17 25 42](https://cloud.githubusercontent.com/assets/11522213/13400968/85610e6c-df0a-11e5-85f0-aad2cebe37da.png)

_after fix_
![bildschirmfoto 2016-02-29 um 17 26 09](https://cloud.githubusercontent.com/assets/11522213/13400973/8a493c2e-df0a-11e5-8d4d-21b82a6f8e25.png)
