### ISSUE TITLE
Thin Grey Line

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#345]
![grayline](https://cloud.githubusercontent.com/assets/16559612/12118026/35e86770-b392-11e5-8b16-65b6839a46b2.JPG)

Note that right under the icons (Tree,Gear, Human) that a thin gray line appears across the white space of the middle frame and this happens across all countries.

**Comment by kathi-aeviator** [comment]
@jpeizer1 @acorbi  I noted this issue before #339

**Comment by kathi-aeviator** [comment]
@acorbi  so how can we handle that? should I proof everything and delete the once we already have?

**Comment by kathi-aeviator** [comment]
@jpeizer1 please declare every issue to Milestone 1.3.0! you can find it on the right side of a new github issue above the "labels". its easier for sorting it in this way.

**Comment by jpeizer1** [comment]
Got it!

RGDS

JP

**Comment by kathi-aeviator** [comment]
@jpeizer1 Great! I have the best overview at the moment what issues we already have so feel free to add everything and 
I will delete the double issues after. I think thats the safest way not to forget anything.

-- 
Katharina Veitengruber
www.aeviator.cc

Am 5. Januar 2016 bei 16:30:32, jpeizer1 (notifications@github.com) schrieb:

Got it!

RGDS

JP

**Comment by kathi-aeviator** [comment]
duplicated on #339, closing
