### ISSUE TITLE
Reduce padding around "Introduction texts" Blue bar

### ISSUE THREAD

**Issue by Numnov** [OpenDevelopmentMekong/opendev-wptheme#35]
@mishari ,we would like the top and bottom padding reduced to half or less of its current value to conserve screen real estate on the home page.

![blue bar to fix](https://cloud.githubusercontent.com/assets/4859982/6890481/898521d2-d6d6-11e4-87bc-316b645250d5.png)

**Comment by mishari** [comment]
This is a fix made by modifying opendev.css line 560 padding to 20px 0px 0px please let me know if this is ok.
![open_development_mekong](https://cloud.githubusercontent.com/assets/503018/6917887/104106c6-d7d3-11e4-8172-9ba391061083.png)

**Comment by DBishton** [comment]
@mishari Much better and great for our purposes. Thanks!
