### ISSUE TITLE
Dissapearing images - https://pp.opendevelopmentmekong.net/background/

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#353]
https://pp.opendevelopmentmekong.net/background/

There are clickable Images? and items on this page that are invisible. I see "OD-Mekong Logo" and "ODV-Logo" and it looks like the "alt=" text for images in html is being used rather  than the real images.  But none of the images are showing up.

Not sure if this is just a testing environment issus
![dissaperingimage](https://cloud.githubusercontent.com/assets/16559612/12215810/e15f79d6-b699-11e5-9073-f80faafb1cd9.JPG)

**Comment by kathi-aeviator** [comment]
@chris-aeviator, @acorbi is it because of the PP-system? can you figure out this problem?

**Comment by acorbi** [comment]
@chris-aeviator @kathi-aeviator @jpeizer1 most probably because of PP-system. Error cannot be reproduced on Production (https://opendevelopmentmekong.net/background/). Changing priority to p3, let's keep this issue open so we do not forget to check on PROD once we deploy

**Comment by Huyeng** [comment]
That's because of the no images are migrated. Fixed.
