### ISSUE TITLE
Search formatting issue - Search has now become UNUSEABLE after Production Move

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#355]
Am not sure why there is shaded box around first row of items -- are they most relevant or? Nevertheless 
1. the Title depicting what type of data the second row items are NEWS NEWS NEWS are in that shaded box as if they are a part of the first row rather than articles under it.
2. Why are none of the thumbnails not showing -- if the reason is there aren't thumbnails why do some items of the same category (NEWS) show a blank thumbnail box next to the item while others do not have a box at all? 

(If something is showing a blank thumbnail i'd say its either better to not show the blank thumbnail at all or possibly put a thumbnail logo of the country there (Cambodia, Thailand, laos etc) so that a different color logo for each would identify the item as being from that country.

![search-formatting](https://cloud.githubusercontent.com/assets/16559612/12215847/257e96c8-b69b-11e5-98bf-416e7276ff3d.png)

**Comment by kathi-aeviator** [comment]
Not part of milestone 7

**Comment by jpeizer1** [comment]
@kathi-aeviator I'm sorry but this looks like a blatant problem that will look pretty terrible with the new implementation - is it really that time consuming to move the titles from the second row out of the first row box at least?? What is that,  like putting an extra <br> in the code?

**Comment by jpeizer1** [comment]
You know what let me just talk to alex.....

**Comment by jpeizer1** [comment]
@DBishton  @kathi-aeviator @chris-aeviator @acorbi  Spoke  to Dan about this and he seemed to think it was in scope. Please see what the production site search looks like (IMAGE BELOW) (no shaded box over first line entries that also encompasses second line of Title labels, images are showing, etc..)

If we end up with the SAME search that is currently in production I am fine and we can close this. If search ends up like above its going backwards and a problem

![prod-site-search](https://cloud.githubusercontent.com/assets/16559612/12275572/ba276f66-b93e-11e5-9da1-85b42825819b.JPG)

**Comment by kathi-aeviator** [comment]
Ok. Sorry JP. You are right. Didn't noticed! We have to declare it as a bug!

**Comment by kathi-aeviator** [comment]
@acorbi @chris-aeviator @Huyeng could someone fix that bug -> change back as it is on production side!

**Comment by jpeizer1** [comment]
After Moving  to production- Search 

![search-shit](https://cloud.githubusercontent.com/assets/16559612/12425886/ebe00c28-bea4-11e5-845a-be61fed3ae8f.JPG)

**Comment by Huyeng** [comment]
Are those screenshot above viewed and tested on the Pre-Production site? 
On the pre-production site, there is no images are migrated to.  The blank of thumbnails on the searching results because of images are added to the post/news, but no image files, but on the production site the problem won't exist.  However, I noticed that there some errors with styling issue. I'm working on to fix it now.
