### ISSUE TITLE
Suggested Structure For X Country Specific ENTRY MENU ITEM

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#356]
This is the proposed solution to help Populate the Extra Button on the top menu and providing easier consistent access to info at the screen bottom and also to our legacy 
Cambodia data. The assumption is that as the country partners were added we'd add Background, Parters, etc. to their submenus... And if we integrated more old Cambodia data into the
new system (like forest cover, census, etc) those items would be taken off these submenu's later.

Top menu Item   X COUNTRY SPECIFIC ENTRY   (Change label to MORE INFORMATION)
# For Mekong:

MORE INFORMATION -> Sub Menu ABOUT (should look like - drop down menu DATA - RECORDS BY TYPE entry with further subdrop downs that have links)

Sub-Sub Item Label 1: BACKGROUND Link: https://pp.opendevelopmentmekong.net/background/
Sub-Sub Item Label 2: CONTACT    Link: https://pp.opendevelopmentmekong.net/contact/
Sub-Sub Item Label 3: DISCLAIMER Link: https://pp.opendevelopmentmekong.net/disclaimer/
# For Cambodia: (Cambodia More Info will have two subsections)

MORE INFORMATION -> Sub Menu ABOUT (should look like - drop down menu DATA - RECORDS BY TYPE entry with further subdrop downs that have links)

Sub-Sub Item Label 1: BACKGROUND Link: https://pp-cambodia.opendevelopmentmekong.net/about/background/
Sub-Sub Item Label 2: PARTNERS   Link: https://pp-cambodia.opendevelopmentmekong.net/about/partnerships/
Sub-Sub Item Label 3: CONTACT    Link: https://pp-cambodia.opendevelopmentmekong.net/contact/
Sub-Sub Item Label 4: HELP   Link: https://pp-cambodia.opendevelopmentmekong.net/help/
Sub-Sub Item Label 3: DISCLAIMER Link: https://pp-cambodia.opendevelopmentmekong.net/disclaimer-2/

MORE INFORMATION -> Sub Menu ARCHIVED DATA (should look like - drop down menu DATA - RECORDS BY TYPE entry with further subdrop downs that have links)

Sub-Sub Item Label 1: 2008 CENSUS             Link: http://www.opendevelopmentcambodia.net/census-data/
Sub-Sub Item Label 2: 2013 ELECTION            Link: http://www.opendevelopmentcambodia.net/election/
Sub-Sub Item Label 3: 2014 FOREST COVER  Link: http://www.opendevelopmentcambodia.net/briefing/forest-cover/
# For Laos:

MORE INFORMATION -> Sub Menu ABOUT (should look like - drop down menu DATA - RECORDS BY TYPE entry with further subdrop downs that have links)

Sub-Sub Item Label 3: DISCLAIMER Link: https://pp-laos.opendevelopmentmekong.net/disclaimer/
# For Myanmar:

MORE INFORMATION -> Sub Menu ABOUT (should look like - drop down menu DATA - RECORDS BY TYPE entry with further subdrop downs that have links)

Sub-Sub Item Label 3: DISCLAIMER Link: https://pp-myanmar.opendevelopmentmekong.net/disclaimer/
# For Thailand:

MORE INFORMATION -> Sub Menu ABOUT (should look like - drop down menu DATA - RECORDS BY TYPE entry with further subdrop downs that have links)

Sub-Sub Item Label 3: DISCLAIMER Link: https://pp-thailand.opendevelopmentmekong.net/disclaimer/
# For Vietnam:

MORE INFORMATION -> Sub Menu ABOUT (should look like - drop down menu DATA - RECORDS BY TYPE entry with further subdrop downs that have links)

Sub-Sub Item Label 3: DISCLAIMER Link: https://pp-vietnam.opendevelopmentmekong.net/disclaimer/

**Comment by kathi-aeviator** [comment]
We had a team-disscusion about that and the solution was to put the "about" topic into the footer. 

-> deleted Milestone from this issue

**Comment by jpeizer1** [comment]
@kathi there is no problem having it at the bottom of the items that's ok. But we now have this extra button at the top menu that I want to populate with relevant information so if About  appears at bottom as part of design and also as a submenu item for people to find it more easily in this generic other info button that's fine. The issue people had was too many top menu buttons but now we have _one_ generic button and we can put some relevant stuff in it as submenus

**Comment by jpeizer1** [comment]
@acorbi @kathi-aeviator @chris-aeviator I implemented these changes above. Please note:

1- PROBLEM I understood from Chris classes have to be created for these submenus -- So I could not preview the links i created IN WP -- But when I looked in the DATA menu under CKAN all these submenus that I had created that were not (but supposed to be) showing up VERTICALLY under the MORE INFO button in WP were instead showing up horizontally across the CKAN menus for each country
![submenu-issue](https://cloud.githubusercontent.com/assets/16559612/12274410/cee2d63a-b938-11e5-92ba-5b786d1882cf.JPG)
1. Another problem is that the sub menu items cause the extension of the mouseover color in the top menu item MORE INFORMATION on the WP menu. The more submenus I have for the item the longer the mouseover color bar extension. So it differs for Mekong, Cambodia and the other countries.
   3- I used the production site links not the pp-links
   4- The MORE INFORMATION top Button on each menu now has no link -- the submenu link under it does. Also  In Cambodia the MORE INFO and the two SUBMENU's don't have links - The SUB-SUB Menus do. Which is consistent with how the  - DATA MENU works

**Comment by kathi-aeviator** [comment]
@chris-aeviator please review!

**Comment by jpeizer1** [comment]
@chris-aeviator @kathi-aeviator @DBishton   Dan and I have spoken and if it is actually too technically complicated for you to do a menu with two sub-levels configured similarly to the DATA menu just right two buttons away then create one level in MORE INFORMATION for Cambodia and use:

Sub-Sub Item Label 1: 2008 CENSUS Link: http://www.opendevelopmentcambodia.net/census-data/
Sub-Sub Item Label 2: 2013 ELECTION Link: http://www.opendevelopmentcambodia.net/election/
Sub-Sub Item Label 3: 2014 FOREST COVER Link: http://www.opendevelopmentcambodia.net/briefing/forest-cover/

in that level. For the other country menus use exactly what is above and is already a single level for each country

**Comment by jpeizer1** [comment]
I need a Cambodia menu configured like this under more information LINK and the formatting should be fixed. What we are trying to demonstrate here CRITICALLY is the ability to access Legacy Cambodia data that could not be immediately migrated because of some custom work done previously that we can still access.

Sub-Sub Item Label 1: 2008 CENSUS Link: http://www.opendevelopmentcambodia.net/census-data/
Sub-Sub Item Label 2: 2013 ELECTION Link: http://www.opendevelopmentcambodia.net/election/
Sub-Sub Item Label 3: 2014 FOREST COVER Link: http://www.opendevelopmentcambodia.net/briefing/forest-cover/

This is THE MOST critical menu. the rest were basically supplementary to this with the unique info being created. 

![000034](https://cloud.githubusercontent.com/assets/16559612/12397571/01f4ee76-bddc-11e5-96c4-f102c9a3b488.png)

**Comment by jpeizer1** [comment]
So the menu functions and -- that's really great - but there is still an issue with submenu items being shown with bar extended in the wrong direction vis-a-vis all other submenu items.

![000038](https://cloud.githubusercontent.com/assets/16559612/12401094/456a9c62-bdf2-11e5-93d4-6eb801aebf1c.png)

**Comment by gimmemochi** [comment]
Remove MORE INFORMATION menu. The link to the legacy projects/pages will be added on the relevant pages. e.g. a feature box for 1970-2014 Forest cover study will be added to the "Forest cover reporting" page the new site. We could also add a slider for this legacy project on the home page.

**Comment by chris-aeviator** [comment]
@OpenDevelopmentMekong/cambodia @OpenDevelopmentMekong/core @DBishton @jpeizer1 

**_IMPORTANT NOTICE**_

do not use the `custom link` feature, as all links will be **_non-consistent**_ between staging - PreProd - Prod.

Instead use the list on the left to pick the desired sites from WP content directly.

![bildschirmfoto 2016-01-19 um 16 55 37](https://cloud.githubusercontent.com/assets/11522213/12415424/3dd4158c-bece-11e5-9013-963a5044803e.png)

Only use case for `custom link`feature is linking to external sites or the datahub
