### ISSUE TITLE
Side menu issue -- Inaccessible Link - Cambodia

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#357]
![sidemenu-issue](https://cloud.githubusercontent.com/assets/16559612/12216283/01c061ee-b6aa-11e5-91de-8d8bc454ad9a.JPG)

I just noticed that if i go into AGRICULTURE and then I jump to any other submenu link Like  ENERGY just as an example... or AID and DEVELOPMENT The AGRICULTURE link is no longer accessible as a link from the ENERGY or any other Menu item page.

**Comment by DBishton** [comment]
There is some inconsistent behaviour of this sort on https://cambodia.opendevelopmentmekong.net which seems to vary by page.

@acorbi @jpeizer1 it's password protected and not public-facing right now but Pinkie showed me this morning.

@gimmemochi can you post some examples? I don't have access to the pages.

**Comment by kathi-aeviator** [comment]
@DBishton @Huyeng what aout this issue? Did you solve it so we can close or is it still open?
