### ISSUE TITLE
Map Explorer - Layer Labels & Mouseovers

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#366]
@chris-aeviator  I note you say - layer catalog  needs to be responsive and not breaking into 2 rows
So this may be a related issue

Can the layer labels be a 
            -smaller font size, 
            - a slightly darker shade of grey  (so even if they are smaller they are still easy to read)
            - Text closer to DOT (to provide more room for text on line)
            - Dot smaller (to compliment smaller text)

![000028](https://cloud.githubusercontent.com/assets/16559612/12220207/eb8c91ae-b735-11e5-8bb0-36e27c53427c.png)

**Comment by kathi-aeviator** [comment]
good points but
the ME dev is not finalised jet its just the actuell status - please have a look in the concept you will find it in
https://hackpad.com/Feedback-for-PKG3-Map-Explorer-oLapLqCuWD7

**Comment by jpeizer1** [comment]
If Final looks like https://hackpad.com/Feedback-for-PKG3-Map-Explorer-oLapLqCuWD7  my issues will be addressed and you can close this.

**Comment by chris-aeviator** [comment]
@jpeizer1 
We can keep it open till implemented

**Comment by prustar** [comment]
Can I also add line space between each layer title, should be reduced a little to save more space.
