### ISSUE TITLE
Map Explorer - The dots 

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#367]
@DBishton  @chris-aeviator 
I wonder... The dots don't react to mouseover but change color when a layer is chosen..

Instinctively the dot feels to me like an on/off switch... And humans like to toggle on off switches... But if you mouse over the dot it doesn't change. You have to click the words instead. 
1. Should the dot be clickable too along with the words?
2. The words change color when you mouseover them but when you have to click them to turn the dot on and off the words  stay one dark color while the button changes state 

I wonder if there should be three colors for the words and two for Dots with the ability to click on both text and dot to change state:

Layer Not selected color #1 (lt grey)   -- Dot and Text
Mouseover color   #2                          -- Text only (so dot always clearly shows if on or off state) 
Layer Selected     Color  #3                -- Dot and Text  (Current selected colors)

  Dan should we ask Pyrou... or what do you think? 

![000028](https://cloud.githubusercontent.com/assets/16559612/12220226/d07df708-b736-11e5-8f96-f75047dca3ce.png)

**Comment by acorbi** [comment]
@jpeizer1 Please check https://cloud.aeviator.cc/public.php?service=files&t=1f6b24dd8bdc99c36a6d2b14400d7e21&path=%2FPK3-Map_Explorer for agreed UI proposal from @kathi-aeviator , the implementation of the map explorer should tend towards that

**Comment by jpeizer1** [comment]
@acorbi  If I look at this UI proposal both the dot and the text turn a particular color with mouseover. and the button actually changes shape when selected or deselected. The issue I have is that its all being done with color now and no shape changes. So if thats the case -- the State change from Mouseover to Selected/deselected is not immediately obvious as the Color does not change on the text.

**Comment by kathi-aeviator** [comment]
@jpeizer1 the actuell status is not finalized we are now working on the features and after that will fix of the design and make the fine finish.

**Comment by jpeizer1** [comment]
@kathi-aeviator   If the end result really looks like:
https://cloud.aeviator.cc/public.php?service=files&t=1f6b24dd8bdc99c36a6d2b14400d7e21&path=%2FPK3-Map_Explorer

It will satisfy all my concerns for this item and you can close it.

**Comment by kathi-aeviator** [comment]
Dots are not finalized! Reopened

**Comment by prustar** [comment]
Sorry for late response to this issue, I agree with JP and as long as the proposed functionality is realised then I don't see immediate issue with it - until testing.

**Comment by Huyeng** [comment]
The template of map explorer is changed, so the issue doesn't exist anymore.
