### ISSUE TITLE
Map Explorer - Titles

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#368]
@chris-aeviator 

Am not sure if this: 
- position of the layer catalogue needs to be fixed to the bottom, scrolling will be disabled
  identifies the problem below of the menu's not being fixed to the bottom for the different country maps.

![000027](https://cloud.githubusercontent.com/assets/16559612/12220284/66067112-b73a-11e5-8fa6-15180e852778.png)

**Comment by kathi-aeviator** [comment]
@chris-aeviator please fix that bug i will hightlight it as a bug

**Comment by chris-aeviator** [comment]
@kathi-aeviator working on this at the moment, will be deployed today

**Comment by kathi-aeviator** [comment]
that issue is fixed! deploying the status of mapexplorer in about an hour.
