### ISSUE TITLE
Map Explorer -- Laos, Myanmar, Thailand, Vietnam - No Base maps.

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#369]
I see only blank white space  and the layers I select for  Laos, Myanmar, Thailand, Vietnam
![000029](https://cloud.githubusercontent.com/assets/16559612/12220300/212e5036-b73b-11e5-8502-29f8afcca107.png)

**Comment by acorbi** [comment]
@jpeizer1 fixed, was config issue on PP. closing
