### ISSUE TITLE
Map Explorer - The Categories, Layers and Sorts

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#370]
1. What happens when there are more than four categories of Layers for a country
2. What happens when there are so many layers per category that there are too many to fit in the screen (Scroll bar? - is there enough room on side of layer selection for scroll bar?)
3. How are layer sorted?

**Comment by kathi-aeviator** [comment]
We should definately figure out a scroll-bar @chris-aeviator please note!

**Comment by chris-aeviator** [comment]
@jpeizer1 
Answered all your questions in response to your private eMail
I would like to file those as separate issue, from my understanding it would be:
1. make active layer boxes scrollable
2. Implement functionality to sort layers

**Comment by prustar** [comment]
![catmenu](https://cloud.githubusercontent.com/assets/14996905/12376939/e2d854ae-bd0b-11e5-9551-7ffd2d7fe417.JPG)

**Comment by prustar** [comment]
@kathi-aeviator @chris-aeviator Please see above screen capture. Now that you can see how many layers there may be in one category it's really important to reduce the line/paragraph space between layer names and have a scroll function.

**Comment by kathi-aeviator** [comment]
@prustar: Question: how many layers and how many categories you want to add in in final before launch?
It's unfortunately not as useful to put in more scrollbars. Could be confusing the user on one hand and design (including colours,...) is not layouted for more than 4-5 categories

**Comment by prustar** [comment]
@kathi-aeviator due to limitations in this design I'm going to reduce as best I can to 4-5 catagories for now for the launch. I will also have to cut number of layers down as well so that it's visually more appealing. This is not ideal overall and will need a re-think after we launch.

**Comment by jpeizer1** [comment]
Could I suggest something?  Right now you have words underneath the color bars... But what if the words were IN THE COLOR BARS - wouldn't that provide you enough space for two rows of four?

Another possibility is the following: your top row of bars at the bottom currently sit _IN_ the map. If your color bars had the words in them you could in fact place four rows of color bars at the top of the map and four rows of color bars at the bottom of the map.

**Comment by kathi-aeviator** [comment]
@prustar you can use us as many layers as you want there is just limitation of categories! So best would be to have topic-categories and add layers into it! But we should definatly find better solution after launch!
@jpeizer to use more than four categories came up after presenting concept for mapexplorer. That's the reason why it's not so easy to change something before launch. We will see if we have enough time to implement your feedback! But in the end it's not depending on the number of layers - they will be scrollable anyway in the end.

**Comment by chris-aeviator** [comment]
solved for now,  see current implementation!

![bildschirmfoto 2016-01-18 um 17 07 46](https://cloud.githubusercontent.com/assets/11522213/12388864/05f09346-be08-11e5-9dd6-f3a919eda7c4.png)
