### ISSUE TITLE
Rendering problems on current map explorer

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#371]
Country-level map explorers do not render their basemaps and seem to exhibit other rendering issues.

Affected URLs are:
https://myanmar.opendevelopmentmekong.net/map-explorer/
https://thailand.opendevelopmentmekong.net/map-explorer/
https://vietnam.opendevelopmentmekong.net/map-explorer/
https://laos.opendevelopmentmekong.net/map-explorer/

@Huyeng please investigate with respect to other similar problems in the past.

@chris-aeviator @kathi-aeviator  Please be aware of this issue and solution when found as it may impact new-gen map explorer development.

Thanks all.
![mapexplorerrenderfail](https://cloud.githubusercontent.com/assets/1206387/12221424/b3150d78-b7cc-11e5-9d0b-2adc5a56c4be.png)
![mapexplorerrenderfail2](https://cloud.githubusercontent.com/assets/1206387/12221432/39f5ef92-b7cd-11e5-906c-3d5d0b17855c.png)

**Comment by Huyeng** [comment]
Fixed
