### ISSUE TITLE
Make map explorer catalogue color-bars configurable

### ISSUE THREAD

**Issue by chris-aeviator** [OpenDevelopmentMekong/opendev-wptheme#373]
The color bars for different layer categories are hardcoded at the moment. 

Every new layer category that is added in WP get's a standard color of 'red'.

It would be benefitial to the mappers/editors if they could configure a color value in the layer-category edit page which set's the color in the map explorer.

![bildschirmfoto 2016-01-10 um 22 02 01](https://cloud.githubusercontent.com/assets/11522213/12222135/d7dd30f4-b7e5-11e5-8e9e-4fa76bf0201d.png)

**Comment by prustar** [comment]
Please also switch the colours for the categories ensuring that Environment is green, hydrology - blue at the minimum - I don't have preference for allocating colours to the other catagories.

**Comment by acorbi** [comment]
@prustar @chris-aeviator I would say those category selection areas should be shorter and offer scrolling possibilities

**Comment by kathi-aeviator** [comment]
@acorbi the width of the categories bars depends on the content shown in the layers so we can't shorten them! Just click on one categorie then choose one layer at click more information...

**Comment by prustar** [comment]
@ Chris - this is what I see in the layer category: 
![image](https://cloud.githubusercontent.com/assets/14996905/12779143/bc699194-ca66-11e5-92ca-dea6d293a06d.png)

Where do I assign the labels for colour like you suggested?

**Comment by chris-aeviator** [comment]
@prustar
Currently this issue is still open and presented functionality needs to be implemented. 
The color's are currently in the code and selected by the slug name (you can see the value in your screenshot). Important to notice if you change the slug of an already defined item (e.g. Environment-and-nat...) the color value cannot anymore be applied to it and will be shown in the default value:red

If you have a defined set of colors for given categories you can paste them here and we can implement them as long as the functionality is missing.
