### ISSUE TITLE
Changing font-sizes

### ISSUE THREAD

**Issue by kathi-aeviator** [OpenDevelopmentMekong/opendev-wptheme#376]
![image](https://cloud.githubusercontent.com/assets/15011163/12222509/d59298ce-b7be-11e5-99da-1e667aedf27a.png)

-> 1. changing font-size of the "Showing 1 to 25 of 588 entries"

.container .five.social, .container .six.columns, .contentNavigation {
position: relative;
font-size: 10px; 
}

-> 2.  changing font-size of "Previous12345…24Next Title"
into 10px

-> 3. discription part (title, docnumber,etc)

font-size: 10px;

**Comment by acorbi** [comment]
@kathi-aeviator like this?? not too small?? what about the Show X entries text?

![screenshot from 2016-01-10 22-04-57](https://cloud.githubusercontent.com/assets/384894/12223990/3f057c5a-b7e6-11e5-927f-1ec046533799.png)

**Comment by kathi-aeviator** [comment]
yes! much better with the fontsizes alex thanks! @jpeizer1 @DBishton can you please allthough review alex fixes above and comment below!

**Comment by kathi-aeviator** [comment]
sorry guys reviewd again and there are some design failures coming up:

@alex please adapt the design as showen in the layout! The differences are:

-> the headlines of the topics don't have the right bg-color -> please change as it was before!=dark colour-not grey!
-> the description section (title, docnumer, etc) should written above the headlines without background-color!

**Comment by jpeizer1** [comment]
@acorbi @kathi-aeviator 
Assuming I should be looking at: https://pp.opendevelopmentmekong.net/laws
the font sizes are better but in firefox you still see these formatting issues:

1 The "Type of Laws" side bar still has text outside of background box
2 the search field is still outside of background box
3 I think its reasonable to have the Previous 12345...24 be a bit smaller in keeping with the Show XX Entries box to its left and the numbers a slightly bit better spaced out although this is less critical than #1 and #2

![search-pages](https://cloud.githubusercontent.com/assets/16559612/12229491/48bacd9c-b816-11e5-8739-16dbf285be43.JPG)

![lawsoutofbox](https://cloud.githubusercontent.com/assets/16559612/12229438/af80cca8-b815-11e5-8840-bce130ccb683.JPG)

**Comment by kathi-aeviator** [comment]
Ok. Agree with JP! 
About the 123456 thing:

-> please add a "," between the numbers!

-> shorten the searchbar!

@acorbi should I make a new issue for that or should we use this one?

**Comment by acorbi** [comment]
@kathi-aeviator @jpeizer1 thanks for your feedback. I will implement your suggestions within this Issue, no need to open a new one.

**Comment by jpeizer1** [comment]
@kathi-aeviator  You can do a comma or even just a little more blank space between the numbers is fine.  Perhaps instead of 12345…24   you have 1 2 3...24  or 1,2,3...24  (so not 1-5 showing but 1-3)

Please note that if you click 5   -- the next number that show are 6,7,8   -- eg. only three numbers. So it is more consistent to show  1,2,3..  and if someone clicks 3  then 4,5,6 is shown

**Comment by kathi-aeviator** [comment]
I agree with JP! But from my side a "," is much more effective visually and in a typographically logic as well. @acorbi please can you implement this?
