### ISSUE TITLE
Funny Word wrap - Transferred From law section

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#377]
![funy-wordwrap](https://cloud.githubusercontent.com/assets/16559612/12183614/e3d19a2e-b55d-11e5-8854-18cbe7e8f9f7.JPG)

Note above (and below) the LOGO in left column that word wrap for title of law is odd

@DBishton  Is it really necessary to have the title even show up there? I mean its at the top as a breadcrumb right above it, and its also next to it in the middle screen as a title, and the PDF is named the same thing. Its four instances of the same title... I think they get it ;-)

**Comment by acorbi** [comment]
@jpeizer1 @DBishton I suggest to remove that title from there as well. There are other elements coming there as part of the Law section concept. https://cloud.aeviator.cc/public.php?service=files&t=1f6b24dd8bdc99c36a6d2b14400d7e21&path=%2FPK2-ODM_LAWS
