### ISSUE TITLE
Adapt the Download buttons

### ISSUE THREAD

**Issue by kathi-aeviator** [OpenDevelopmentMekong/opendev-wptheme#379]
The language download-buttons should adapt. 
- centering 
- no square

**Comment by acorbi** [comment]
@kathi-aeviator can you please post screenshots, on my side the buttons are centered and round

**Comment by kathi-aeviator** [comment]
@acorbi I'm working with a a ubuntu mini machine at the moment. the screen could be the problem. 
@DBishton @jpeizer1 can you check that on yours, please?

**Comment by kathi-aeviator** [comment]
ok did the review of the side at another machine and its working fine. @acorbi a we should keep that in mind for responsive action! Close issue.
