### ISSUE TITLE
Category "tags" on Briefing Pages should appear in heirachical order

### ISSUE THREAD

**Issue by Numnov** [OpenDevelopmentMekong/opendev-wptheme#38]
@mishari , we would like the "tag" presentation above titles on "briefing" post types to appear hierarchically based on taxonomy, rather than alphabetically.

![screen shot 2015-03-30 at 5 58 34 pm](https://cloud.githubusercontent.com/assets/4859982/6895232/2b4771d8-d708-11e4-9102-53c9f3e02e41.png)

**Comment by mishari** [comment]
@DBishton I'm not sure how to present this information as a hierarchy rather than a flat text, any ideas on how to do so? Or would you just like me to change the ordering and that's it?

**Comment by DBishton** [comment]
@mishari Just changing ordering is good. Ordered according to category
hierarchy (which mirrors taxonomy hierarchy) is the end result we had in
mind for this particular issue.

On Tue, Mar 31, 2015 at 5:39 PM, Mishari Muqbil notifications@github.com
wrote:

> @DBishton https://github.com/DBishton I'm not sure how to present this
> information as a hierarchy rather than a flat text, any ideas on how to do
> so? Or would you just like me to change the ordering and that's it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/38#issuecomment-88036839
> .

## 

_Daniel Bishtonmobile:  +855968153317 | Twitter:
http://twitter.com/DanielBishton http://twitter.com/DanielBishton |
LinkedIn: http://linkd.in/Uf2YKt http://linkd.in/Uf2YKt_

**Comment by mishari** [comment]
I just took a closer, I'm not too sure what the correct ordering if this would be. I looked at the post Categories and saw this:
![edit_briefing_ _some_title_ _wordpress](https://cloud.githubusercontent.com/assets/503018/7030010/c52e847e-dd8b-11e4-979f-cb97ab05d0db.png)
Which is the same as what appears on the page.
![hydropower___some_title](https://cloud.githubusercontent.com/assets/503018/7030020/de5afacc-dd8b-11e4-90c3-857c8177faf3.png)

What is the expected behaviour for this?

**Comment by mishari** [comment]
It seems that this is implemented by the_category https://github.com/OpenDevelopmentMekong/opendev-wptheme/blob/master/single-briefing.php#L9 which is a WP built in function. The entire function will need to be re-implemented with this functionality.

**Comment by Huyeng** [comment]
I have updated the functionality to fix this issue, now it was fixed.  See the screenshot if it is what you expected. Please test or check on the live site also. Please let me know for some comments. 
![screenshot_9](https://cloud.githubusercontent.com/assets/6613530/7246064/3852b994-e821-11e4-86df-2ab69951b773.jpg)

**Comment by mishari** [comment]
@Huyeng can we close this issue?

**Comment by DBishton** [comment]
@mishari  @Huyeng This is exactly what we were looking for -- closed.
