### ISSUE TITLE
Filter laws by country

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#380]
Records on the law page should display the geographic range of the record and be filterable by it.

Ideally, displayed records reflect the geographic area (spatial range) of the OD site the user is on: Cambodia, Myanmar, Laos, Vietnam, Thailand.

Behaviour for Mekong can be discussed: I think it should be all records,  but alternatively it could be records with any spatial range other than those five countries -- ASEAN, Greater Mekong Subregion, and so on. @gimmemochi @jpeizer1 @acorbi opinions welcome on this. 

Defaults less important than being visually prominent and easy to use -- perhaps something like a RHS widget with buttons that can be toggled.

**Comment by kathi-aeviator** [comment]
@acorbi can you give short answer or suggestion on that issue?

**Comment by chris-aeviator** [comment]
closing this as the current implementation is working like described (cambodian law page shows only cambodian laws) . 

At the moment we don't have a mekong law's section active, this ability to filter by country (sort by country is already implemented) needs to be included into the next release!
