### ISSUE TITLE
Pages/Search Box Formatting

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#381]
It looks to me like the search box is a bit off center/bit too long for its background box -- I am in Firefox BTW

Also wonder of pages links 12345...24 couldnt have  bit more space between the numbers on top and bottom

![pages-search-formatting](https://cloud.githubusercontent.com/assets/16559612/12222956/e2042486-b798-11e5-966f-eaa040dc1829.JPG)

**Comment by acorbi** [comment]
@kathi-aeviator can you propose CSS values modification?? thx!

**Comment by kathi-aeviator** [comment]
closing issue - double issue -> #376
