### ISSUE TITLE
NEWS-Explorer // Change basemap into "Dark Matter"

### ISSUE THREAD

**Issue by kathi-aeviator** [OpenDevelopmentMekong/opendev-wptheme#382]
Setup in Wordpress -> Maps -> Edit map:
http://a.basemaps.cartocdn.com/dark_all /{z}/{x}/{y}.png

**Comment by acorbi** [comment]
@kathi-aeviator @chris-aeviator same for map explorer?

**Comment by kathi-aeviator** [comment]
@acorbi no. just for newsexplorer to hightlight it

**Comment by Huyeng** [comment]
Since ODI run on the https, so the base map should request from https too: http://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png

**Comment by kathi-aeviator** [comment]
ah sorry you are right. Thanks.
