### ISSUE TITLE
NEWS-Explorer // Change Order

### ISSUE THREAD

**Issue by kathi-aeviator** [OpenDevelopmentMekong/opendev-wptheme#384]
It has to be chronological order. If it is like that its fine, but I'm not sure yet.

**Comment by Huyeng** [comment]
What did you refer to the chronological order?

**Comment by acorbi** [comment]
@Huyeng I guess it is meant that the news should be sorted by publication date

**Comment by kathi-aeviator** [comment]
@Huyeng @acorbi yes. alex is right. It has to be sorted by publication date. First is biggest.

**Comment by Huyeng** [comment]
Yes, of course. As the default, they sorted by the published date, but if there are some posts are stick, they will show first.

**Comment by kathi-aeviator** [comment]
Ok allright. Can we close this issue then HE?
