### ISSUE TITLE
NEWS-Explorer // add icons

### ISSUE THREAD

**Issue by kathi-aeviator** [OpenDevelopmentMekong/opendev-wptheme#388]
add icons to the list items. Choose the share icon from the icomoon set and use "more" instead of the info-icon as written in the feedback of NE in hackpad.

**Comment by Huyeng** [comment]
Sharing function on the NE is not working. It works depend on the Embedded sharing map. However the sharing embedded map is disable for a while. 

I tried to test the sharing function by enable the "sharing embedded map" option, but the function doesn't working well, got 404 when shared link is clicked. 

What do you think if we use the function of sharing social media on right side of topic page:
https://opendevelopmentmekong.net/topics/environment-and-natural-resources/
![screenshot_7](https://cloud.githubusercontent.com/assets/6613530/12314881/a3fcdaa4-baa7-11e5-80b2-5da2f5fa116e.jpg)

**Comment by Huyeng** [comment]
It seems to me that the Hyperlink label of reading more article link is not consistent on the sites. 
@DBishton or @gimmemochi, could you both identify this issue whether we should use "read more...", "more..." or "Keep reading..."?

**Comment by DBishton** [comment]
@Huyeng The standard we have been using on ODM has been "Keep reading".

On Thu, Jan 14, 2016 at 10:59 AM, Huyeng notifications@github.com wrote:

> It seems to me that the Hyperlink label of reading more article link is
> not consistent on the sites.
> @DBishton https://github.com/DBishton or @gimmemochi
> https://github.com/gimmemochi, could you both identify this issue
> whether we should use "read more...", "more..." or "Keep reading..."?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/388#issuecomment-171522203
> .

## 

_Daniel Bishtonmobile:  +855968153317 | Twitter:
http://twitter.com/DanielBishton http://twitter.com/DanielBishton |
LinkedIn: http://linkd.in/Uf2YKt http://linkd.in/Uf2YKt_

**Comment by Huyeng** [comment]
Great, thanks @DBishton. I will use "Keep reading".

**Comment by kathi-aeviator** [comment]
@Huyeng @DBishton sorry for late answer but its realy important to use just "more"! we will have problems for mobile and small screens after. So please HE change that once again please. @dan Do you argree with that in trust of me?;)

**Comment by kathi-aeviator** [comment]
please exchange the social-button icons! Take the icomoon icons there:

![bildschirmfoto 2016-01-15 um 14 39 22](https://cloud.githubusercontent.com/assets/15011163/12347985/ce00eb44-bb95-11e5-9785-e8fab1e1715c.png)
![bildschirmfoto 2016-01-15 um 14 39 13](https://cloud.githubusercontent.com/assets/15011163/12347986/ce08bf54-bb95-11e5-9e8a-72f153d9a313.png)
![bildschirmfoto 2016-01-15 um 14 41 18](https://cloud.githubusercontent.com/assets/15011163/12348021/150879f8-bb96-11e5-99aa-5b140ca0d60c.png)

I now that the function is "sharing" but we have to safe that place.

**Comment by Huyeng** [comment]
I used these icons as they already used on the topic page: https://opendevelopmentmekong.net/topics/economy-and-commerce
If change them, so we need to change those icons on the topic pages to make it consistency. 

If it is not necessary, I suggest to do it after launching because there are a lot of tasks need to complete for lauching.

**Comment by kathi-aeviator** [comment]
Ok. Agree with doing after launch. Labeled to P2
