### ISSUE TITLE
NEWS-Explorer // keep date

### ISSUE THREAD

**Issue by kathi-aeviator** [OpenDevelopmentMekong/opendev-wptheme#389]
keep date of NE as it is - just change font size 

.post-header .date, .single-post-header .date, .date
 { font-size: 10px; }

**Comment by Huyeng** [comment]
I thought that it is too same size. Let see the default current size I have, if you think that the size of date should reduce than, I will do it. (Note, I will pull the update soon.)

**Comment by kathi-aeviator** [comment]
yes. thank you Huy Eng! We do it like this. Closing issue.
