### ISSUE TITLE
WorldPress Editor toobar lacks some functions: justify, supscript and subsript

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/opendev-wptheme#39]
The button of justify, superscript and subscript are missed, the editor need them for the briefing content. 

![screenshot_6](https://cloud.githubusercontent.com/assets/6613530/6914192/5575e19c-d7b2-11e4-9907-e84e18c715b8.jpg)

**Comment by DBishton** [comment]
Thanks @Huyeng. From an editor's point of view, we witnessed that formatting styles available in WordPress did not display on the page when published -- for example, caption text for image assets, and superscript formatting of text in posts.

**Comment by Huyeng** [comment]
Fixed.

**Comment by Huyeng** [comment]
The Editor need the option to change the font size on the Editor Toolbar.

**Comment by Huyeng** [comment]
Added.
