### ISSUE TITLE
Implement breadcrumbs and titles

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#391]
@chris-aeviator @kathi-aeviator  Breadcrumbs and titles are present all over the Wordpress frontend and should be designed and implemented with a global scope. Initially, this Issue was added to PK2 but it actually belongs to PK1, thus changing label.

![screenshot from 2016-01-13 18-08-05](https://cloud.githubusercontent.com/assets/384894/12301493/a1c6709c-ba20-11e5-8bca-e0303f62db52.png)

My recommendation here is that the CSS properties are defined globally, and not specifically for every component which leads to unreadable, redundant and difficult to maintain code.

This issue is related to https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/335
https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/292

**Comment by kathi-aeviator** [comment]
Yes @acorbi it should be one design/css stile on CKAN and WP. I agree with css recommendation! Choose fastet way to implement. Most prio is here to make it global - more than right color-size! 

Keep in mind: please use the right logo-icon from icomoon:

![image](https://cloud.githubusercontent.com/assets/15011163/12349497/6b078c2a-bb70-11e5-9549-6b217fa0cb13.png)

**Comment by acorbi** [comment]
@kathi-aeviator I would be happy to undertake this, but I am prioiritising PK2 (profile pages) and I do not expect to have time for more. This is part of PK1.

**Comment by kathi-aeviator** [comment]
Ok. I'll keep it in mind.

**Comment by acorbi** [comment]
@chris-aeviator I could not implement this tonight. Please address as part of finalization of navigation concept

**Comment by kathi-aeviator** [comment]
@chris-aeviator please review.
