### ISSUE TITLE
Map Explorer -- categories don't always collapse

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#392]
See screenshot below: "infrastructure" layer category does not collapse after a layer is activated ("GMS rail links"). There is also an "environment" layer activated ("Hydro basins level 3"), but this one has collapsed correctly.

![mapexplorercategorynortetract](https://cloud.githubusercontent.com/assets/1206387/12228230/e78d164c-b86a-11e5-9212-a480ee8b2c76.png)

**Comment by chris-aeviator** [comment]
@DBishton @kathi-aeviator 

Currently you are able to keep the categories open by clicking on the name of the category instead of hovering it. Should this behaviour be maintained?
