### ISSUE TITLE
The function of Map Group is not work properly

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/opendev-wptheme#4]
Creating a map group on odmekong.geojournalism.org as well ad cambodia.odm webiste, the map groups is not showed or viewable. Please have a look at the links below for testing. Any comments or suggestion are highly appreciated. 

http://odmekong.geojournalism.org/mapgroup/natural-resource/
http://cambodia.opendevelopmentmekong.net/mapgroup/test-group/

**Comment by WillieShubert** [comment]
Hi Huyeng, 
I think this is a misunderstanding about the role of map groups. These map groups control the tabbed navigation on top of the geolocated news functionality. They are not used to organize map content in any other way. This feature is tested and functional. 

The purpose of map groups in relationship to layers and maps is described in the documentation here. 
http://geojournalism.org/2015/02/using-jeos-content-type/#data-visualization-content-types

**Comment by Huyeng** [comment]
It is the same as https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/6
Right, the map group is working well.
