### ISSUE TITLE
Records by type should not rely on WP groups

### ISSUE THREAD

**Issue by kathi-aeviator** [OpenDevelopmentMekong/opendev-wptheme#400]
Same issue as happend in CKAN musst be done for WP.

You can see here:

https://github.com/OpenDevelopmentMekong/ckanext-odm_nav/issues/13#

**Comment by acorbi** [comment]
Did already on https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/396, this is duplicated. closing.

**Comment by kathi-aeviator** [comment]
tno.
