### ISSUE TITLE
Search Site Text

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#403]
Because you just implemented a Menu at the top in CKAN with a SEARCH FIELD that says Search Datasets...

I think the SEARCH field in the WORDPRESS front end should say SEARCH SITE or SEARCH FULL SITE   -- just so the difference is clear

![search-site](https://cloud.githubusercontent.com/assets/16559612/12274650/d72a9124-b939-11e5-87fc-bb1cf0150365.JPG)

**Comment by kathi-aeviator** [comment]
Thank you @jpeizer1 I made an issue for that days ago and we tried to fix it but there is still a Problem with the upper and lowercases. I will label that as a bug.

so changings are:
1. using lower cases for Searchbar example text before before
2. changing text into "search site..."
3. changing background of the searchbar into #FFFF

**Comment by jpeizer1** [comment]
@kathi-aeviator Lower case "search site..."  -- the meaning of the words are most important to describe what people can expect.  

If the bug is really a problem that proves very time consuming to fix may I suggest just changing CKAN search field to say  "search datasets..." so the letter case is consistent in the two search boxes -- this is the more important thing I think.

**Comment by kathi-aeviator** [comment]
Ok thanks JP. I'll coordinate that tomorrow! Last thing of the day: deploying changes of mapexplorer and logo-changes.

**Comment by jpeizer1** [comment]
Search site text on HOME PAGES should read  "search site..."  to conform to "search datasets..." message in CKAN

**Comment by Huyeng** [comment]
I have already change the texts in search field to "search site..." in lowercase on WP. Please update texts on CKAN to lowercase too.
