### ISSUE TITLE
Map Explorer on MEKONG CKAN menu is a bad link - Server not found

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#404]
https://pp-mekong.opendevelopmentmekong.net/map-explorer

![me-mekong-ckan-error](https://cloud.githubusercontent.com/assets/16559612/12274869/ee10efae-b93a-11e5-8d91-fca3a29d56f3.JPG)

**Comment by acorbi** [comment]
Fixed via https://github.com/OpenDevelopmentMekong/ckanext-odm_nav/commit/9af3dd726486ffc83797af8998d60742a456b283
