### ISSUE TITLE
Map Explorer -- 12.1.15

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#405]
Is there a better place to move CONTACT Button so that it doesn't overlap a key - and/or really reduce it?

![bildschirmfoto 2016-01-13 um 01 13 04](https://cloud.githubusercontent.com/assets/16559612/12275410/015ad982-b93e-11e5-869a-c95a8ae56008.png)

**Comment by acorbi** [comment]
@jpeizer1 @chris-aeviator @kathi-aeviator I would suggest somewhere on the left sidebar.

**Comment by chris-aeviator** [comment]
@jpeizer1 we are aware of that issue, thanks for reporting!

---

Von unterwegs gesendet

**Comment by jpeizer1** [comment]
This CONTACT FORM Tab seem to really be making a nuisance of itself ;-)

I am wondering if it would be better to move it up just below the blue frame at the top of the map and just above above the first key box which always seems to appear in the same place on the right of the map when a layer is chosen. If we shortend the width of the contact form just a little and it lived inthat top corner of the map it wouldn't overlap anything - or maybe just a little... 

![contactform](https://cloud.githubusercontent.com/assets/16559612/12379394/ddefd6f8-bd27-11e5-926b-866e2378b88b.JPG)

**Comment by chris-aeviator** [comment]
contact form removed for map explorer, thanks dan, jp for that suggestion :)
