### ISSUE TITLE
CCS Link Text Issue - Cambodia

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#406]
I know I have posted this before - The issues is still a problem and I can;t find a closed issue for it.

The LInk text for Cambodia site is the same color as the background font making it impossible to see. 
Also For Vietnam, Thailand and Thailand the link text color chosen is really quite light -- any possibility of checking and darkening a few shades.

![css-link-text](https://cloud.githubusercontent.com/assets/16559612/12276162/47ffc6b4-b942-11e5-9864-260fd6c26d51.JPG)
![link-text-examp](https://cloud.githubusercontent.com/assets/16559612/12276188/735bfb66-b942-11e5-8d76-dfa274e453b1.JPG)

![screenshot from 2016-01-05 12-29-32](https://cloud.githubusercontent.com/assets/384894/12114176/0b6b0f96-b3a8-11e5-9116-417770bdb88a.png)

Currently, links are just visible on hover.

**Comment by acorbi** [comment]
@jpeizer1 the related issue you saw is https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/338, i have closed and moved my infos from there to here.

**Comment by Huyeng** [comment]
Fixed!
