### ISSUE TITLE
Broken Thumbnails

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#407]
While reviewing 

https://pp-data.opendevelopmentmekong.net/dataset?extras_odm_spatial_range=cambodia

I noticed lots of broken thumbs on the returned search list, but if you click on a  record in the list with a borken thumbnail (whether the record has 1 or multiple attached documents -- the thumbnails actually displays correctly)

![brokenthumbs](https://cloud.githubusercontent.com/assets/16559612/12287631/11bddb0e-b99c-11e5-9eca-7f1b7fc7df5b.JPG)

**Comment by acorbi** [comment]
@jpeizer1 the reason for this is (old) images being referenced by http (new ones are behind https) which causes a **Loading mixed (insecure) display content** warning on the browser

![screenshot from 2016-01-13 11-35-10](https://cloud.githubusercontent.com/assets/384894/12291860/e7df90d6-b9e9-11e5-9808-bd945f5f3978.png)

The same problem should happen on prod.

Possible solutions: 
1.  Do a redirection on the sys-admin side ( coordinate with proteus )
2. Re-upload the images
3. Replace the urls on the database via SQL query

Probably I would go for 3. but needs to be done carefully
