### ISSUE TITLE
Load translated texts into WP

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#412]
UI elements for the laws pages have already been translated for Khmer on https://www.transifex.com/open-development-mekong/odm-wp-laws-pages/dashboard/, the translated strings should be loaded into WP

**Comment by acorbi** [comment]
@chris-aeviator the same should be done for Map explorer. Let's coordiante gathering the newly-added strings on the MP explorer UI and its localization

**Comment by Huyeng** [comment]
What are the translating strings use for. The current Khmer law page are already translated, see this.
https://cambodia.opendevelopmentmekong.net/kh/laws
