### ISSUE TITLE
Finalize layout and usability for tabular form in Laws Page

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#415]
@kathi-aeviator Taking your comment in https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/376#issuecomment-170460572 as starting point, I am opening this Issue to discuss the finalization of the layout and the definition on how the user interacts on the Laws Page's table. That other Issue was related to font-sizes so i find more convenient address this topic in a separate thread.

On your comment, you suggest that the headings [Doc number], [Date] and [Download] are in line with the [Document type], as pictured below.
![screenshot from 2016-01-13 18-30-56](https://cloud.githubusercontent.com/assets/384894/12302150/0ab34168-ba24-11e5-8e2f-4f437c7254cb.png)

Allthough definitely possible to implement ( specially in normal timeline conditions ), this approach represents following disadvantage:

If you visit the current implementation of the Laws page on https://pp.opendevelopmentmekong.net/laws, you will see that you are able to click on the headings in order to sort the data by those elements. In my opinion, being able to sort the provided data is of great importance and it is a feature which is currently present on the table on http://www.opendevelopmentcambodia.net/laws_and_regulations/agriculture-and-fishing/?post_type=law

If we would like to implement your approach, and as I see things, we would need either:
1. To remove the possibility of sorting data as I describe above
2. To create several different tables ( one for each document type ) which brings us again to the paginations problems derived of maintaining several different tables.

Alternatively, we could go with the current approach or the one which was deployed before ( pictured below) which implies having a full-width row with the type of document.
![screenshot from 2016-01-13 18-38-51](https://cloud.githubusercontent.com/assets/384894/12302440/73743d78-ba25-11e5-8ee5-12d326b7ace2.png)

Or would you solve it differently? Im open for other approaches, as long as there is enough time to implement.

**Comment by acorbi** [comment]
@DBishton @jpeizer1 your opinion is also welcome here.

**Comment by kathi-aeviator** [comment]
First of all - some questions for @acorbi 

In the sceershot as you seen here

![image](https://cloud.githubusercontent.com/assets/15011163/12321713/f1900428-baaf-11e5-9251-e60e0238bffb.png)
1. what is the "undefined" line for? maybe a bug?
2. please fix that issue: https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/423
3. the download buttons for KH should be all in one line
4. Please fix that bug allthought - announcement is braking out of the box

![image](https://cloud.githubusercontent.com/assets/15011163/12321925/2e56524e-bab1-11e5-8db9-d48461aabc1b.png)

**Comment by kathi-aeviator** [comment]
@acorbi 

what's the problem with the pagination? The tables (as we gave them to you) have been separate tables for each and every document type. Pagination should work with a global 'controller' element that set's the corresponding choice on all tables pagination elements

**Comment by kathi-aeviator** [comment]
@acorbi 

just saw, current iteration looks fine!

**Comment by acorbi** [comment]
@kathi-aeviator 

> what is the "undefined" line for? maybe a bug?

FIxed

>  please fix that issue: #423

Fixed

>  the download buttons for KH should be all in one line

Can you provide a mockup or describe your suggestion? I do not understand what you mean exactly, the download buttons are all in one line.

> Please fix that bug allthought - announcement is braking out of the box

Is this Issue still present? I cannot reproduce it, see below:

![screenshot from 2016-01-15 01-09-48](https://cloud.githubusercontent.com/assets/384894/12341827/c18f81ca-bb24-11e5-8129-a42dd44abb93.png)

**Comment by acorbi** [comment]
@kathi-aeviator should we close this issue and move forward with the current layout?

**Comment by acorbi** [comment]
@kathi-aeviator  in order to ensure responsiveness in the layout and better data functionalities, I have implemented a different approach without grouping entries by document type. See current implementation in PP. http://pp.opendevelopmentmekong.net/laws/

![screenshot from 2016-01-18 00-24-57](https://cloud.githubusercontent.com/assets/384894/12380728/276992c2-bd7a-11e5-98fd-ea430d3f57c3.png)

**Comment by acorbi** [comment]
Im closing this issue

**Comment by kathi-aeviator** [comment]
Yeah thanks. Agreed!
