### ISSUE TITLE
Please hid 'Share A Map' tab in the sub-bar

### ISSUE THREAD

**Issue by Numnov** [OpenDevelopmentMekong/opendev-wptheme#42]
@mishari , can you please hid tab in the sub-tab bar?  If possible, please complete this by COB tomorrow.

Thanks!

**Comment by mishari** [comment]
@Numnov sorry no idea what you're talking about, illustrations please?

**Comment by Huyeng** [comment]
@Numnov, do you mean the "Share A Map" on the screenshot below: 
![screenshot_8](https://cloud.githubusercontent.com/assets/6613530/7037736/826e9098-ddd1-11e4-90d9-46774ac67367.jpg)

Well, for this issue, you can hide and show it through the JEO setting as the image below. For now, I it has been disable, so there is no the item on the second menu tab.
![screenshot_10](https://cloud.githubusercontent.com/assets/6613530/7037759/dcd3b9fa-ddd1-11e4-86d6-7675ec4f9d71.jpg)

**Comment by Numnov** [comment]
@Huyeng , yes, that is it. Thanks for working on it. I see that it is now hidden.
