### ISSUE TITLE
Header is destructered! CSS problems

### ISSUE THREAD

**Issue by kathi-aeviator** [OpenDevelopmentMekong/opendev-wptheme#421]
Something went wrong on 
https://pp.opendevelopmentmekong.net/#!/

see screenshot below.
1. the header is destructured 
2. logo is missing

![image](https://cloud.githubusercontent.com/assets/15011163/12320440/0a3a24e2-baa9-11e5-86a7-bbf73c2c36cc.png)

**Comment by Huyeng** [comment]
it looks fine to me. Does anyone have the same problem? 
![screenshot_3](https://cloud.githubusercontent.com/assets/6613530/12320531/b12c57ca-badb-11e5-8922-2fd1dd66c5ad.jpg)

**Comment by acorbi** [comment]
## Looks like this on mine

![screenshot from 2016-01-14 10-29-00](https://cloud.githubusercontent.com/assets/384894/12320576/ab34a16a-baa9-11e5-8faa-7d58f84be6ab.png)

## News explorer looks good

![screenshot from 2016-01-14 10-31-33](https://cloud.githubusercontent.com/assets/384894/12320650/07b243f2-baaa-11e5-9bd0-2246edfe60d0.png)

## View zoomed out

![screenshot from 2016-01-14 10-31-21](https://cloud.githubusercontent.com/assets/384894/12320648/0650ba2a-baaa-11e5-8cd5-d1f50b01878b.png)

**Comment by kathi-aeviator** [comment]
We still have that problem! alltough the sidebar is overlapping the newscontainer!

**Comment by acorbi** [comment]
Seems to me like the approach is basically check the css of the header and fix the issue, no? News explorer looks good

**Comment by kathi-aeviator** [comment]
HE what browser do you use?

**Comment by Huyeng** [comment]
I tested with both Chrome and Firefox.

**Comment by Huyeng** [comment]
Local screenshot: 
![screenshot_4](https://cloud.githubusercontent.com/assets/6613530/12320802/3704b062-badd-11e5-86e3-c42dbc683cb2.jpg)

**Comment by kathi-aeviator** [comment]
Problem solved thanks to alex. closed!

**Comment by chris-aeviator** [comment]
Re-opened this one as there are still problems on cambodia-pp.opendevelopmentmekong.net
![bildschirmfoto 2016-01-15 um 01 42 29](https://cloud.githubusercontent.com/assets/11522213/12333868/4b9e3920-bb29-11e5-8522-b265f737ac7c.png)
