### ISSUE TITLE
Perfomance Issues on news explorer

### ISSUE THREAD

**Issue by chris-aeviator** [OpenDevelopmentMekong/opendev-wptheme#422]
On our smallest machine, performance of the news explorer is very poor.

Please check if javascript/jQuery functions that are manupulating the height of every `div.sticky-item`` ( about every second) is neccessary, as it might influence performance in a bad way.

**Comment by acorbi** [comment]
@chris-aeviator good point

**Comment by Huyeng** [comment]
what does it mean "manupulating the height of every div.sticky-item"?

**Comment by chris-aeviator** [comment]
@Huyeng 
`.sticky-item` is the div of every news-item

The yellow highlighted height value's are changed through a jquery script. Please try to unload it and ask if you have any questions or if it takes too much time for you to find out

![bildschirmfoto 2016-01-14 um 21 49 57](https://cloud.githubusercontent.com/assets/11522213/12327405/ef92745e-bb08-11e5-8772-501316434a12.png)

**Comment by kathi-aeviator** [comment]
@Huyeng please give a short update about that issue!

**Comment by Huyeng** [comment]
This is the performance to set equal height of the Dev item in each line once the map is rotated. Otherwise, the div item will mix up.
![screenshot_21](https://cloud.githubusercontent.com/assets/6613530/12396497/56d0dd0c-be3a-11e5-8d15-cde6a45aa780.jpg)

**Comment by kathi-aeviator** [comment]
The feature you are talking about is not in use anymore...every dig stays the same height always. It can be removed. With performence is ment that it Takes way to much time to load the hole site. After deleting non relevant Feature the Performance will be much better/faster!

**Comment by chris-aeviator** [comment]
Tested, clean & **fast**  now !
Thanks :+1:
