### ISSUE TITLE
WP-Navigation // Changing the a word

### ISSUE THREAD

**Issue by kathi-aeviator** [OpenDevelopmentMekong/opendev-wptheme#424]
@acorbi @chris-aeviator 

After discussion with dan we came to the point to choose "maps" instead of "map explorer"

-> please change that! 

I made a seperate issue to change it in CKAN here:
https://github.com/OpenDevelopmentMekong/ckanext-odm_nav/issues/37

**Comment by Huyeng** [comment]
I saw that the Map explorer has changed to map on WP, but not on CKAN. Please change it to be consistent.
