### ISSUE TITLE
News-Explorer // Change color of the Pins

### ISSUE THREAD

**Issue by kathi-aeviator** [OpenDevelopmentMekong/opendev-wptheme#426]
![image](https://cloud.githubusercontent.com/assets/15011163/12327581/ad52dbd2-bad7-11e5-85ef-dd7a7fcaa005.png)

Please change the color of the not actual pins 

RGB (235,100,32)

**Comment by kathi-aeviator** [comment]
@Huyeng  please implement issue and close after.

**Comment by kathi-aeviator** [comment]
@ HE Can not see the implementation on pp! Did you implement the color?

**Comment by Huyeng** [comment]
The pin color has changed following the country color:
![screenshot_1](https://cloud.githubusercontent.com/assets/6613530/12392938/35957676-be25-11e5-98c7-4210d735bc96.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/6613530/12392979/75ef04a8-be25-11e5-8aa0-04463648f811.png)
