### ISSUE TITLE
VIETNAM WP-home-side

### ISSUE THREAD

**Issue by kathi-aeviator** [OpenDevelopmentMekong/opendev-wptheme#427]
![image](https://cloud.githubusercontent.com/assets/15011163/12329873/a84b2a9e-bae2-11e5-9cfa-674654759001.png)

Notes from JP:

MOCKUP -- I understand MEKONG and CAMBODIA will go live with these type of page I suggest (with Slider and Huy Engs new News container). VIETNAM is a partner country and if you look at their Production page right now you will see an equivalent type of page - It has a slider on top, and a map/news container under it and one extra widget (events?) under that. It is my impression then that when we go live with the configuration I suggested for MEKONG and CAMBODIA that VIETNAM has it too. I would just like @DBishton to confirm and also ask what he feels we should do about their extra widget at the bottom.

**Comment by kathi-aeviator** [comment]
@jpeizer1 

Dan is going to speak to Open Development Vietnam Team to coordinate with us about inputing theier content into PP Wordpress.

All features are available to all country sites, but they need to be activated!

**Comment by Huyeng** [comment]
I will do it for cambodia site in PP. 
However, I have a few comments for the mockup above. 
- Does the news feature slider is required to show on the homepage?
  ![screenshot_8](https://cloud.githubusercontent.com/assets/6613530/12343711/d7030ae2-bb68-11e5-9758-07501e52413c.jpg)
- The news posts on the News feature Slider are also listed in the NE. 
  On the product site, according to the script, the news feature slider will be replaced by the Feature slider likes the tested on the https://pp-cambodia.opendevelopmentmekong.net/#!/. Please have a look.

**Comment by DBishton** [comment]
@Huyeng Thank you for clarifying!

**Comment by Huyeng** [comment]
Can the issue close?

**Comment by kathi-aeviator** [comment]
@DBishton please close issue if finished.

**Comment by Huyeng** [comment]
This is the homepage of Vietnam looks like: 

![screenshot_4](https://cloud.githubusercontent.com/assets/6613530/12507276/475ef616-c127-11e5-9c26-b93c7cb09eaf.jpg)

**Comment by DBishton** [comment]
Thanks for clarifying all -- it's looking good.
