### ISSUE TITLE
Correct format of Legend in Hydropower interactive Map

### ISSUE THREAD

**Issue by Numnov** [OpenDevelopmentMekong/opendev-wptheme#43]
@mishari would you be able to format the legend so everything looks neat and is aligned?

![screen shot 2015-04-07 at 7 13 46 pm](https://cloud.githubusercontent.com/assets/4859982/7022892/da1c2bc4-dd5a-11e4-9418-c01dead7648a.png)

Here is the name of the layer: Layer title: Greater Mekong Hydropower dam projects 2014

Here is the CartoDB where it is hosted: http://dbishton.cartodb.com/api/v2/viz/7d320d44-aac8-11e4-9bb9-0e0c41326911/viz.json

Here is the code:

 HTML for legend:

"<div class='cartodb-legend custom'> 

<div class="legend-title">Status</div>

<ul>
  <li>
    <div class="bullet" style="background:#229a00"></div>
    Operating 
  </li>
  <li>
    <div class="bullet" style="background:#ff5c00"></div>
    Underway
  </li>
  <li>
    <div class="bullet" style="background:#ffcc00"></div>
    Planned  
  </li>
  <li>
    <div class="bullet" style="background:#b40903"></div>
    Cancelled  
  </li>
  <li>
    <div class="bullet" style="background:#3b007f"></div>
    Suspended  
  </li>
  <li>
    <div class="bullet" style="background:#2e5387"></div>
    Unknown  
  </li>
  <li>
    <div class="bullet" style="background:#918f88"></div>
    No data  
  </li>
  <li>
  < 11.4
  </li>
  <li class="graph">
    <div class="bubbles"></div>
  </li>
  <li>
  5850 >
  </li>
</ul>

</div>"

**Comment by Huyeng** [comment]
Fixed it. This is new looks like. @Numnov or @DBishton, please close the issue if you think it fixed. 

![screenshot_11](https://cloud.githubusercontent.com/assets/6613530/7038812/7299ea40-dde1-11e4-83ef-c4806ca02fa1.jpg)

**Comment by Huyeng** [comment]
Fixed.
