### ISSUE TITLE
Logo misspositioning on certain firefox versions

### ISSUE THREAD

**Issue by chris-aeviator** [OpenDevelopmentMekong/opendev-wptheme#431]
@acorbi @DBishton @jpeizer1 @kathi-aeviator 
Please test on all firefox systems available 

logo correct placed

![bildschirmfoto 2016-01-15 um 01 26 31](https://cloud.githubusercontent.com/assets/11522213/12333494/0e25bc1e-bb27-11e5-9e04-52f66f0b5719.png)

Logo displaced (screenshot from alex' linux firefox)
![photo_2016-01-15_01-27-11](https://cloud.githubusercontent.com/assets/11522213/12333509/21966ed8-bb27-11e5-8acf-907d49191b7a.jpg)
- confirmed

**Comment by DBishton** [comment]
@chris-aeviator 
On my Windows 10 machine, monitor is 1440x900 with Firefox 43.0.4:
![ppodmhomepagefirefox4304](https://cloud.githubusercontent.com/assets/1206387/12347304/48b0c9f6-bb8f-11e5-8b31-1739351e7eb8.png)

Same machine and monitor, Chrome 47.0.2526.111 m: 
![ppodmhomepagechrome47](https://cloud.githubusercontent.com/assets/1206387/12347362/978cb418-bb8f-11e5-8a4d-2465a0cade79.png)

On my 1366x768 laptop screen, the gap between logo and title is smaller on both browsers.

**Comment by jpeizer1** [comment]
![logo-terry](https://cloud.githubusercontent.com/assets/16559612/12436614/df43618c-bee4-11e5-9418-e61a22c3c488.JPG)

**Comment by jpeizer1** [comment]
![sc](https://cloud.githubusercontent.com/assets/16559612/12436696/8fa1e5b2-bee5-11e5-8137-a3e719b9e378.JPG)

**Comment by jpeizer1** [comment]
![capture](https://cloud.githubusercontent.com/assets/16559612/12436768/2146e562-bee6-11e5-8e44-a3b3ccd0445b.JPG)

**Comment by kathi-aeviator** [comment]
@jpeizer1 please write down specific information as you can see in dans comments above (screensize, browser,...)
