### ISSUE TITLE
Map Explorer: Make Key Labels on Right scrollable

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#433]
I brought up multiple map layer categories just to see what would happen if you opened multiple maps in different categories 
![mexplore](https://cloud.githubusercontent.com/assets/16559612/12336765/268896a8-bad4-11e5-97ee-6d20dc23fe9d.JPG)

Note that the bottom-most Open Layer Indicator Category LAND (in BLUE) falls off the bottom of the screen when space runs out for a new layer to be added

**Comment by acorbi** [comment]
Being able to scroll vertically through those boxes would be great IMO... something like a transparent scrollable area
