### ISSUE TITLE
How to navigate back from new law section 

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#434]
I just went into the new laws and agreements front end 
![lawnavi](https://cloud.githubusercontent.com/assets/16559612/12337445/28859ae2-bad8-11e5-8a31-7b79b5cccb62.JPG)

and pressed the first subdecree link in 
https://pp.opendevelopmentmekong.net/laws/?odm_taxonomy=Social%20development

Now the problem is how do i get back? I am now in CKAN and I look at the screen and intuitively press LAWS and AGREEMENTS (which is the same Menu Item I came from in the same place) at the top -- but that takes me into the CKAN search filter for Laws https://pp-data.opendevelopmentmekong.net/laws_record.   I try Home ICON - and that doesn;t work either, I click LAWS breadcrumb and that doesn't take me back. 

Shouldnt the LAWS and AGREEMENTS menu take one to the same place in either wordpress or Ckan

![howtonavback](https://cloud.githubusercontent.com/assets/16559612/12337481/51daf77a-bad8-11e5-9ce3-e9685a0a03c4.JPG)

**Comment by acorbi** [comment]
@jpeizer1 this is related to navigation and to https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/391, you marked it correctly with PK1.

**Comment by acorbi** [comment]
@chris-aeviator I could not implement this tonight. please address it as part of finalization of navigation concept.

**Comment by kathi-aeviator** [comment]
@chris-aeviator please implement.

**Comment by acorbi** [comment]
Breadcrumbs have been fixed now
