### ISSUE TITLE
Line spacing broken by superscript

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#442]
Adding superscript text (our standard for footnotes) causes a misalignment of line spacing, as in the image below:

![linespacing](https://cloud.githubusercontent.com/assets/1206387/12346911/290730ee-bb8b-11e5-9d0e-f4d134dbeb1a.png)

This could be resolved by adjusting the line spacing for all text to be slightly greater.

**Comment by kathi-aeviator** [comment]
@chris-aeviator @acorbi can you fix that bug? - please allthough label this as the correct milestone (I'm not able to do this with my account, cannot fix it - please keep in mind)

**Comment by Huyeng** [comment]
Fixed!
