### ISSUE TITLE
Country-specific menu submenu items behave incorrectly

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#443]
When configuring a country-specific menu item, sub items are currently not appearing on WordPress, but the highlighted area for that area is expanded when submenu items are added:

![headermenuitemerror](https://cloud.githubusercontent.com/assets/1206387/12347774/a84b7f42-bb93-11e5-86f8-4517ceec7903.png)

On CKAN the country-specific menu items currently don't display at all:

![headerckanitemmissing](https://cloud.githubusercontent.com/assets/1206387/12347796/e8417f7a-bb93-11e5-9dac-e747d1362eb6.png)

**Comment by kathi-aeviator** [comment]
add on to this issue from design-side:

please correct the width of the "more information" button! Depends allthough on css classes.
