### ISSUE TITLE
NEWS-EXPLORER // Wrong border set

### ISSUE THREAD

**Issue by chris-aeviator** [OpenDevelopmentMekong/opendev-wptheme#446]
when not all news articles are present the box in the 2nd row does not have a border at the bottom.

![bildschirmfoto 2016-01-15 um 15 34 08](https://cloud.githubusercontent.com/assets/11522213/12348891/edea2a30-bb9d-11e5-8a8e-1276a6dac1e3.png)

**Comment by kathi-aeviator** [comment]
@Huyeng please review and close issue.
