### ISSUE TITLE
TOPIC AREAS: appears in English on the Khmer site

### ISSUE THREAD

**Issue by gimmemochi** [OpenDevelopmentMekong/opendev-wptheme#448]
![screen shot 2016-01-15 at 5 03 34 pm](https://cloud.githubusercontent.com/assets/6489398/12350529/257d9a3e-bbaa-11e5-84d9-66593a509286.png)

Make it appear in Khmer on ODC Khmer page.

**Comment by acorbi** [comment]
Analog to 1 in https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/450 ( see my comment) the string "TOPIC AREAS" should be added to the localization workflow, translated (if not done yet) and deployed

**Comment by Huyeng** [comment]
should the country navigation need to translate too, right? If so, I need to wrap the text in gettext function.
 ![screenshot_16](https://cloud.githubusercontent.com/assets/6613530/12376027/0dfca710-bd12-11e5-9d47-770e7ead4319.jpg)

**Comment by Huyeng** [comment]
The issue of country navigation is created, see: https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/489
