### ISSUE TITLE
NEWS-EXPLORER // Strange scrolling

### ISSUE THREAD

**Issue by chris-aeviator** [OpenDevelopmentMekong/opendev-wptheme#451]
Currently scrolling on News Explorer feels "un-natural", if you scroll just a little bit from the bottom (tested on a macbook touchpad) you wil be moved almost to the top. This makes it almost impossible to scroll to a selected news entry.
![ne_scroll_bug](https://cloud.githubusercontent.com/assets/11522213/12352991/2b0b0faa-bbbd-11e5-9b15-d8409db1f075.gif)

Please bring back the standard scrolling behaviour or adapt the speed of the plugin controlling it. Also please make the scrollbar more wide, to enable the user to click on the scrollbar more easy.

**Comment by kathi-aeviator** [comment]
@Huyeng did you see that issue and is it possible to change that with same function and design like other scrollbars in this project?!

**Comment by Huyeng** [comment]
Well, I will fix it soon.

**Comment by Huyeng** [comment]
I have already disable it now. Please check it.

**Comment by acorbi** [comment]
@Huyeng @kathi-aeviator is this fixed? BTW @Huyeng do you deploy your changes on PP? do you use the odm-automation or do it manually?

**Comment by kathi-aeviator** [comment]
@Huyeng please review and close!

**Comment by Huyeng** [comment]
@Alex, I don't use the odm-automation. I'm not familiar with it yet, I will use it later. 
@kathi-aeviator, I fixed it, but i don't have the macbook test to test,if the issue is fixed. It would be better if you could check it, and close it if fixed.

**Comment by acorbi** [comment]
@Huyeng :+1:

**Comment by kathi-aeviator** [comment]
@Huyeng Is this issue fixed? Please review again and close issue.

**Comment by Huyeng** [comment]
The issue is on Macbook, not in window. I'm using the window, so I don't have the problem like this. 
However, i have disable the js, so i thought that it fixed. It would be better if someone use Macbook test and confirm it.

**Comment by kathi-aeviator** [comment]
@chris-aeviator please review again and close after!

**Comment by chris-aeviator** [comment]
Working perfect, thank you !
:+1:
