### ISSUE TITLE
LAWS PAGES: Downloadbutton in one line

### ISSUE THREAD

**Issue by kathi-aeviator** [OpenDevelopmentMekong/opendev-wptheme#470]
@acorbi please list every downloadbutton from laws-page list in one line below each other. So KHs are one line, EN -one line, ...

**Comment by acorbi** [comment]
@kathi-aeviator with the current size of the buttons that would make the rows longer in height. Also, in the other elements of the system resource download buttons are always arranged horizontally.

![screenshot from 2016-01-17 16-40-54](https://cloud.githubusercontent.com/assets/384894/12378276/273ed4ec-bd39-11e5-97e3-2c128a9d6082.png)
![screenshot from 2016-01-17 16-41-06](https://cloud.githubusercontent.com/assets/384894/12378275/273be304-bd39-11e5-86ee-0acb3a36f7d8.png)

I would suggest to leave them in the same row and close this issue. please provide feedback

**Comment by acorbi** [comment]
Closing this issue.

**Comment by kathi-aeviator** [comment]
these are not meant @acorbi we are already talking about this (I commented it in some issues before)

![image](https://cloud.githubusercontent.com/assets/15011163/12412000/709372b0-be83-11e5-8edd-4aa4228f2585.png)

as you can see in this screenshot the "KM" and the "EN" download-buttons are not vertically in one line. but should be. it was in the deployment chris gave you in the right way. Now its visually confusing. Please change.

**Comment by acorbi** [comment]
@kathi-aeviator what do you think about having them horizontally aligned on other parts of the system but not here? ( See 2 comments :top: ) isn't that more confusing? Also if you see your original design proposal they are horizontally aligned in it:

![publicpreview](https://cloud.githubusercontent.com/assets/384894/12413130/e3f8db56-be8c-11e5-9271-8b577819bc69.png)

I am confused..... :confused:

**Comment by kathi-aeviator** [comment]
@acorbi Ok. Now I know why you are confused! In my last comment it should meant "vertically". I 'll change that directly! BUt is that more clear for you now?

**Comment by kathi-aeviator** [comment]
Anyway in that layout its correct it is correct but not on PP. It looks like my last screenshot!

**Comment by acorbi** [comment]
@kathi-aeviator I understood your intention perfectly, you want the download buttons to be one below the other, as in:

[EN]
[KM]

But what it is not clear is why you want them that way so much, since the download buttons for resources are everywhere horizontally aligned and even your proposed design indicates that they should be horizontally aligned. Please elaborate on this

**Comment by kathi-aeviator** [comment]
what i mean is aligning the columns of the dataset's download buttons like so:

[EN] [KH] [TH]
[EN] [KH] [TH]
        [KH] [TH]
[EN] [KH]
[EN]         [TH]
[EN] [KH] [TH]
[EN] [KH] [TH]

**Comment by kathi-aeviator** [comment]
@acorbi awhat i mean is aligning the columns of the dataset's download buttons like so:

```
[EN] [KH] [TH]
[EN] [KH] [TH]
[KH]      [TH]
[EN] [KH]
[EN]      [TH]
[EN] [KH] [TH]
     [KH] [TH]
```

**Comment by acorbi** [comment]
ahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh got it. Unfortunate, I do not have time to implement that :disappointed:

**Comment by kathi-aeviator** [comment]
@acorbi  ?? Takes 5 min to set column width! Just play around with your browser ;P

**Comment by Huyeng** [comment]
Updated! see this.
![screenshot_1](https://cloud.githubusercontent.com/assets/6613530/13044044/89a7b85c-d3fe-11e5-9f7d-bf6eae777b29.jpg)
