### ISSUE TITLE
LAWS PAGES: final arrangement of HL and subHL

### ISSUE THREAD

**Issue by kathi-aeviator** [OpenDevelopmentMekong/opendev-wptheme#471]
https://pp.opendevelopmentmekong.net/laws
@acorbi css proposals for this issue:
1. please delete the margin top! 
   .row {margin-top: 0px;} 
2. lower distance between "LAWS" HL and info class

**Comment by acorbi** [comment]
@kathi-aeviator this is not an Issue specific to the Laws pages and as described in https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/391 this should be approached as part of PK1. Closing...
