### ISSUE TITLE
Navigation -- wrong turn?

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#473]
While perusing laws I clicked on KH (587) in Country section navigation (on left)
![navigation-issue1](https://cloud.githubusercontent.com/assets/16559612/12374059/56b22fac-bc5e-11e5-9f69-65fae2d0fd00.JPG)

I ended up here - in datasets with a different number of non-law (11) datasets
![navigation-issue2](https://cloud.githubusercontent.com/assets/16559612/12374061/5cf9aef8-bc5e-11e5-9c41-b52ae78c5ee1.JPG)

**Comment by acorbi** [comment]
@jpeizer1 This is a good spot, i believe I know the fix but please move this to https://github.com/OpenDevelopmentMekong/ckanext-odm_dataset, it belongs there. thanks

**Comment by jpeizer1** [comment]
Alex I needed to get out a few hours  I have to move when I get back or please close move if if issue  sent by phone. Jp

**Comment by acorbi** [comment]
OK , i close it myself and moved to https://github.com/OpenDevelopmentMekong/ckanext-odm_dataset/issues/254
