### ISSUE TITLE
Navigation: What is the more information under the top topic navigation

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/opendev-wptheme#477]
If mouse hover on the icons of the topics, there is a words "MORE INFORMATION" overlap the list of the topic, see the screenshot below.  Please remove it if not necessary. 
![screenshot_15](https://cloud.githubusercontent.com/assets/6613530/12375904/4f1ba49c-bd0a-11e5-8616-d7ab62d83d98.jpg)
![screenshot_14](https://cloud.githubusercontent.com/assets/6613530/12375903/4f10358a-bd0a-11e5-8082-9c46b5bc4fce.jpg)

**Comment by jpeizer1** [comment]
@Huyeng @chris-aeviator @kathi-aeviator This is related to still unresolved issue of the more information map and its lack of a class its now wrapping into tjhe next line and overlaying other items...
https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/356

**Comment by kathi-aeviator** [comment]
This is although one point for responsive implementation. Thanks for the note

**Comment by gimmemochi** [comment]
MORE INFORMATION should be removed from the homepage or the header menu items. A feature box for the census data, election page, and forest cover pages will be added to the relevant topic/landing pages.

**Comment by kathi-aeviator** [comment]
@DBishton can you please coordinate that issue!

**Comment by DBishton** [comment]
@kathi-aeviator @gimmemochi is correct -- we will lose the country-specific menu for Cambodia

**Comment by chris-aeviator** [comment]
closed with current implementation
