### ISSUE TITLE
Map Explorer: Implement loading indicator for layers

### ISSUE THREAD

**Issue by chris-aeviator** [OpenDevelopmentMekong/opendev-wptheme#483]
When loading a layer takes too long the user is confused by the not appearing/late appearing layer. It would be benefitial to the user if layer loading would be indicated by a 'spinner' or something similar.

**Comment by chris-aeviator** [comment]
_removing label p2 as map explorer development is on freeze for V2 development_

**Comment by Huyeng** [comment]
@prustar does issue still exist?

**Comment by prustar** [comment]
@Huyeng Yes this is still an issue and needs to be included somehow. The layers are taking so long to load and would be good to let people know that something is happening even if slow.

**Comment by jpeizer1** [comment]
Agreed -- I've had this issue too, you don't know if its working or not. If you are a user with a fast pc its particularly disconcerting because you just assume its not working.

**Comment by acorbi** [comment]
Fixed via 050704a44ecbf28c1f4ee0e29b50b1b18fb9a02a
