### ISSUE TITLE
Map explorer: Map covering topics menu

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#494]
![screenshot from 2016-01-17 10-16-02](https://cloud.githubusercontent.com/assets/384894/12376742/fc2a881c-bd03-11e5-9ffb-ec9560db772d.png)

**Comment by chris-aeviator** [comment]
closing, 

duplicate of https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/478
