### ISSUE TITLE
ELC-Downloads CSV, GeoJson, KML

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#498]
CSV provides download screen when clicked -- GeoJson, KML send user back to 
https://pp.opendevelopmentmekong.net/economic-land-concessions

![elc-downloads](https://cloud.githubusercontent.com/assets/16559612/12377741/8b1fbc2c-bcf5-11e5-90af-52b0a43622a0.JPG)

**Comment by jpeizer1** [comment]
https://cambodia.opendevelopmentmekong.net/company-profiles/economic-land-concessions/

Am looking at ELC and the download just for the CSV files brings up a 404 --
https://data.opendevelopmentmekong.net/dataset/1cd6c00a-867b-4e90-887b-f47a55fb87a3/resource/3b817bce-9823-493b-8429-e5233ba3bd87/download/elcen.csv

CAV -- 404 Error
![csv-404](https://cloud.githubusercontent.com/assets/16559612/12401312/986a8e76-bdf3-11e5-8369-a863ed9b529b.JPG)

**Comment by kathi-aeviator** [comment]
@acorbi did you solve that problem?

**Comment by acorbi** [comment]
Fixed via e61311790c7488b7e436a2d253f1cae9b5782297
