### ISSUE TITLE
ELC - White buttons

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#499]
In Firefox the buttons for sharing and zooming maps are blank in both individual ELC's and scroll list of ELC's 

![elc-navback](https://cloud.githubusercontent.com/assets/16559612/12377751/fd9a2a62-bcf5-11e5-8e97-40efa409debb.JPG)
![elc-wb2](https://cloud.githubusercontent.com/assets/16559612/12377754/2bc1bb9e-bcf6-11e5-9312-781591cfaf2f.JPG)

**Comment by acorbi** [comment]
Fixed via 1453696ad52738d9cf377634a3b3df0217ae9b60
