### ISSUE TITLE
ELC-Navigation back - Breadcrumb Navback issue?

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#500]
When in an individual concession record I see no easy way back to 
https://pp.opendevelopmentmekong.net/economic-land-concessions
Unless I hit back on browser  -- Shouldn't the breadcrumb for an individual land concession have clickable links where:
1. the last part of crumb is the Title (or partial title...) of individual record you are in 
2. the one prior is Economic Land Concessions which clicks back to ELC home page? 
3. And Home (which is only clickable link now) takes you back to top of site (Which actually should be Cambodia.opendevelopmentmekong.net because the ELC implementation is for Cambodia (@acorbi @dbishton - from my understanding from you)

![elc-navback](https://cloud.githubusercontent.com/assets/16559612/12377772/15f6eb3a-bcf7-11e5-9411-c13e784dc147.JPG)

**Comment by acorbi** [comment]
This issue is related to https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/434 and https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/391. It should be addressed together with the finalization of the navigation concept.

**Comment by Huyeng** [comment]
The breadcrumb is enhanced as the screenshot below:
![screenshot_6](https://cloud.githubusercontent.com/assets/6613530/12813230/41b4d702-cb69-11e5-9e97-9a3d63de0445.jpg)

**Comment by Huyeng** [comment]
Can I close this issue?

**Comment by chris-aeviator** [comment]
@Huyeng 

looks perfect, thanks!
