### ISSUE TITLE
ELC -- Cambodia?

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#501]
@acorbi @DBishton Just want to be sure we are all on the same page. E.g. That the:

Final ELC implementation will show up as a menu item only on Cambodia, not Mekong or in other countries? Dan please confirm.

**Comment by acorbi** [comment]
@jpeizer1 @DBishton yes, please dan confirm

**Comment by DBishton** [comment]
@acorbi @jpeizer1 Correct. We currently only have concessions data for
Cambodia, and will only give acess to this functionality from the Cambodia
instance.

On Sun, Jan 17, 2016 at 10:38 PM, Alex Corbi notifications@github.com
wrote:

> @jpeizer1 https://github.com/jpeizer1 @DBishton
> https://github.com/DBishton yes, please dan confirm
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/501#issuecomment-172342184
> .

## 

_Daniel Bishtonmobile:  +855968153317 | Twitter:
http://twitter.com/DanielBishton http://twitter.com/DanielBishton |
LinkedIn: http://linkd.in/Uf2YKt http://linkd.in/Uf2YKt_

**Comment by acorbi** [comment]
:+1:

**Comment by acorbi** [comment]
Fixed. ELC pages can be added as a page on wordpress and referenced within the country specific menu of the cambodia site. See example in staging http://cambodia.opendevelopmentmekong.net/
