### ISSUE TITLE
Map Explorer- Main Menu Navigation Glitch -- Submenus

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#508]
I note that the DATA menu/submenu is not working just on mapexplorer page -- I assume that when the MORE INFORMATION menu is complete the same issue will have to be addressed with the submenu dysfunction
![000030](https://cloud.githubusercontent.com/assets/16559612/12378656/52442a6e-bd13-11e5-907d-b1be4252ac33.png)

**Comment by chris-aeviator** [comment]
will be addressed all at once it's an issue with the plugin map, tried the usual stuff but could not implement a quick fix.

Please follow up on https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/478
