### ISSUE TITLE
Map Explorer: WMS shadow 

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/opendev-wptheme#509]
When a WMS layer is activated and subsequently deactivated the info windows are still clickable. 
![map-explorer1](https://cloud.githubusercontent.com/assets/14996905/12378715/33ecf044-bd47-11e5-8331-0c6a948d8306.JPG)
The layer has been switched off yet the info window is stilled displayed: 

![map-explorer4](https://cloud.githubusercontent.com/assets/14996905/12380768/2fe37b92-bd7b-11e5-87b9-9c92ab18756d.JPG)

Pig distribution is the layer selected by the shadow from the previous layer is still visible and brings up the info window content of that previous layer. 
![map-explorer5](https://cloud.githubusercontent.com/assets/14996905/12380769/2fe569e8-bd7b-11e5-9f4e-8d2a2608fc46.JPG)

**Comment by Huyeng** [comment]
The highlighted will disable temporary, and it will enable when I find the way to fix it.
