### ISSUE TITLE
MAP Explorer: Full screen function

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/opendev-wptheme#511]
Expanding to full map view the menu options disappear. It would be nice to be able to play with layers in the full view as the smaller view can get a little cramped. 
![map-explorer2](https://cloud.githubusercontent.com/assets/14996905/12378923/a41c1f42-bd4d-11e5-9150-83df017933b6.JPG)

**Comment by kathi-aeviator** [comment]
As requested by terry the full view should be an option to see map without any categories. You can "close" fullcreen option and will have again lots of place to play.

**Comment by prustar** [comment]
There should be options to expand the map to full view while still being able to utilise the menu functions. This will enable users to use the ME during presentations where loading layers allows for narration.

**Comment by kathi-aeviator** [comment]
@chris-aeviator can you please make a proposal on that issue.

**Comment by chris-aeviator** [comment]
The proposed solution is making the layer catalogue available at the bottom in Full screen view

**Comment by Huyeng** [comment]
It was fixed.
