### ISSUE TITLE
MAP EXPLORER: long string text from CartoDB legend not displaying correctly

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/opendev-wptheme#526]
There formatting needs to be fix to allow for long string text: 

![image](https://cloud.githubusercontent.com/assets/14996905/12387406/974c9d08-bdcc-11e5-94bd-a7763060c5d1.png)

**Comment by kathi-aeviator** [comment]
This prolem is solved in other issue. Closed
