### ISSUE TITLE
Required new components by site

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#529]
Mekong: news explorer, map explorer

Cambodia: news explorer, map explorer, laws page, profiles page

Vietnam: news explorer, map explorer, topic page links disabled

Laos: news explorer, map explorer, topic page links disabled (home page behind placeholder)

Thailand:  news explorer, map explorer, topic page links disabled (home page behind placeholder)

Myanmar:  news explorer, map explorer, topic page links disabled (home page behind placeholder)

**Comment by chris-aeviator** [comment]
@DBishton 

top topic menus disabled by https://github.com/OpenDevelopmentMekong/opendev-wptheme/pull/565

**Comment by chris-aeviator** [comment]
#Status

## Mekong
- [x] News Explorer
- [x] Map Explorer

## Cambodia
- [x] News Explorer
- [x] Map Explorer
- [x] Laws Page
- [x] Profiles Page

## Vietnam
- [ ] News Explorer
- [ ] Map Explorer
- [x] topic page links disabled

## Laos
- [ ] News Explorer
- [ ] Map Explorer
- [x] topic page links disabled

## Thailand
- [ ] News Explorer
- [ ] Map Explorer
- [x] topic page links disabled

## Myanmar
- [ ] News Explorer
- [ ] Map Explorer
- [x] topic page links disabled

**Comment by chris-aeviator** [comment]
@DBishton 

Can we coordinate with the other country teams (?) on filling their subsites to enable the featured list content ?
