### ISSUE TITLE
LAWS-Page 404 on Cambodia laws page

### ISSUE THREAD

**Issue by kathi-aeviator** [OpenDevelopmentMekong/opendev-wptheme#530]
There is 404 for https://pp-cambodia.opendevelopmentmekong.net/laws

**Comment by acorbi** [comment]
FIxed, created a new Page with template "profile pages" https://pp-cambodia.opendevelopmentmekong.net/laws/

**Comment by kathi-aeviator** [comment]
@dbriston please notice!
