### ISSUE TITLE
What MYANMAR, LAOS, THAILAND front pages should look like

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#532]
@Huyeng 

I visited MYANMAR, LAOS, THAILAND pages on staging server
https://myanmar.opendevelopmentmekong.net/
https://laos.opendevelopmentmekong.net/
https://thailand.opendevelopmentmekong.net/
1. Myanmar has smaller width for all items on the page -- please make Laos and Thailand like this
2. The Pikto map has the last line of statistics cut off for all countries right now -- Please make sure the last line of statistics are showing for each country...(please see attached) 

![likethis](https://cloud.githubusercontent.com/assets/16559612/12393659/14ba0f80-bdc5-11e5-995f-1ee9e586b0bc.jpg)

**Comment by Huyeng** [comment]
I have checked the homepage of the three countries, width for all items on the page are the same. Could you please check it again please.

The Pikto map has the last line of statistics of three charts are showed up. Sorry for that.

**Comment by jpeizer1** [comment]
Huy Eng I think its ok for what we need to present tomorrow....
