### ISSUE TITLE
ELC-KEY - Formating is REALLY problemmatic - We want to show this at presentation 

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#533]
ELC land concession key on front page comes up with items overlapping

![elc-key](https://cloud.githubusercontent.com/assets/16559612/12394180/4b9285b6-bdc8-11e5-8832-050c75aacbe6.JPG)

**Comment by acorbi** [comment]
HTML tweaking on the legends can be done directly on the cartodb map. NO need for touching the code on our servers

![screenshot from 2016-01-18 16-32-15](https://cloud.githubusercontent.com/assets/384894/12395310/24f6e152-be01-11e5-83da-70e4b5b605ff.png)

**Comment by kathi-aeviator** [comment]
Sorry @Arbigkung for assigning you. Happens while using mobile version on GitHub!

**Comment by chris-aeviator** [comment]
@kathi-aeviator 

please see review folowing proposal and reopen the issue if necessary 

![bildschirmfoto 2016-01-19 um 01 13 16](https://cloud.githubusercontent.com/assets/11522213/12398988/ec850f8a-be49-11e5-89dd-0257011b2677.png)

https://pp-cambodia.opendevelopmentmekong.net/economic-land-concessions-profiles

**Comment by jpeizer1** [comment]
This looks great

**Comment by kathi-aeviator** [comment]
Thanks agree with that.

**Comment by chris-aeviator** [comment]
Thank you for confirming !
:+1:
