### ISSUE TITLE
MAP EXPLORER- category bars still configured with multiple words other than Cambodia 

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#537]
In Mekong, Myanmer, Vietnam ect. I see multiple word bars that are overhanging their color bars and screwing up the UI

![mapserver-menu-items](https://cloud.githubusercontent.com/assets/16559612/12397065/c89073b0-bdd8-11e5-902f-a33bf9c7d03d.JPG)

**Comment by chris-aeviator** [comment]
we're coordinating with pyrou already about it

**Comment by prustar** [comment]
I just checked them all again and I they are all fixed now.
