### ISSUE TITLE
Language picker control missing

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#541]
from the header in Cambodia and Vietnam instances on staging and pre-production servers.

**Comment by chris-aeviator** [comment]
translation plugin is not working --> https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/545

**Comment by chris-aeviator** [comment]
assigned correct system user 

before:

````
drwxr-xr-x 1 root     root       110 Jan 18 18:43 .
drwxr-xr-x 1 www-data www-data   126 Jan 18 01:20 ..
-rw-r--r-- 1 root     root       647 Jan 17 07:57 en_US.mo
-rw-r--r-- 1 root     root     63785 Jan 17 07:57 en_US.po
-rw-r--r-- 1 root     root      5097 Jan 17 07:57 kh.mo
-rw-r--r-- 1 root     root     66113 Jan 17 07:57 kh.po
-rw-r--r-- 1 root     root       414 Jan 17 07:57 odm-localization-templete.php
````
after:
````
drwxr-xr-x 1 www-data www-data   110 Jan 18 18:43 .
drwxr-xr-x 1 www-data www-data   126 Jan 18 01:20 ..
-rw-r--r-- 1 www-data www-data   647 Jan 17 07:57 en_US.mo
-rw-r--r-- 1 www-data www-data 63785 Jan 17 07:57 en_US.po
-rw-r--r-- 1 www-data www-data  5097 Jan 17 07:57 kh.mo
-rw-r--r-- 1 www-data www-data 66113 Jan 17 07:57 kh.po
-rw-r--r-- 1 www-data www-data   414 Jan 17 07:57 odm-localization-templete.php
````

**Comment by chris-aeviator** [comment]
language switcher available on 

https://pp-cambodia.opendevelopmentmekong.net/

![bildschirmfoto 2016-01-19 um 02 55 04](https://cloud.githubusercontent.com/assets/11522213/12401294/1edb7f42-be58-11e5-8aff-946b39c5f4d1.png)

@kathi-aeviator please make proposal for optimal position

@DBishton please coordinate on language settings and translation

**Comment by kathi-aeviator** [comment]
@chris-aeviator please but the language picker above the searchbar.

**Comment by Huyeng** [comment]
Fixed
