### ISSUE TITLE
Front-facing strings need translation

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#544]
Currently the following interface strings need to be translated into Khmer and added to the interface:

Header menu:
Laws, policies and agreements
Publications library
Data hub
Maps
Map explorer
Economic land concession profiles

Footer menu:
About us
Disclaimer
Terms of use

Disclaimer text: 
By accessing this website or database, you indicate your agreement with our terms and conditions of use, which among other things, generally allow conditional non-commercial use of what you see on the site. For more information on how our open data approach benefits you, please see our terms of use page.

Map Explorer categories:
Environment
Hydrology

@gimmemochi Can you assign coordinate this with someone in the ODC team and paste the results as a comment? Please re-assign issue to @chris-aeviator when complete.

**Comment by kathi-aeviator** [comment]
@gimmemochi do you have any results for this issue?

**Comment by acorbi** [comment]
Fixed via da2910c1b58da43845c95328550429374887ad9a
