### ISSUE TITLE
MAP EXPLORER: Horizontal scroll bar, i info icon and active window bugs

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/opendev-wptheme#548]
There shouldn't be a need for the horizontal scroll bar if the 'i' info is moved a little the the left. In all categories there should be space if the distance between the point and text is reduced slightly. In the active window there is plenty of space to eliminate the horizontal bar and fit the download and info icons in. 

![map-explorer9](https://cloud.githubusercontent.com/assets/14996905/12401211/558fec2c-be25-11e5-812b-c93d79c80bb3.JPG)
![map-explorer8](https://cloud.githubusercontent.com/assets/14996905/12401261/9603dfd4-be25-11e5-975b-1da22e474c3d.JPG)

Info displays seems random at the moment. If you have only one window up sometimes you can select the i icon for more info but I had to select it on average 3 times before it displayed the extra information. If you also then expand the legend and then close the info text the legend stays open. 

![map-explorer10](https://cloud.githubusercontent.com/assets/14996905/12401502/10beec5e-be27-11e5-93b3-3e7b71ad190f.JPG)

**Comment by kathi-aeviator** [comment]
The once on the bottom are fixed the once on the right site not. @chris-aeviator please implement the right site if possible.

**Comment by chris-aeviator** [comment]
@prustar can you confirm they are gone for the bottom layert categories? I never saw the horizontal bar on my machine...active layer boxes (right side ) will be fixed

**Comment by kathi-aeviator** [comment]
@jpeizer1 are you able to confirm?

**Comment by prustar** [comment]
In Mekong the horizontal bar is still present: 

![map-explorer14](https://cloud.githubusercontent.com/assets/14996905/12432842/f328b44a-befd-11e5-90f2-d18fb9d78bf0.JPG)

**Comment by prustar** [comment]
I take it back the horizontal bar is still in ODC but seems to be random depending upon how many layers are up: 

![map-explorer15](https://cloud.githubusercontent.com/assets/14996905/12433617/633e9fd4-bf02-11e5-96d0-4a6b2b809230.JPG)
![map-explorer16](https://cloud.githubusercontent.com/assets/14996905/12433642/7c812c46-bf02-11e5-8003-4f665c9a0c22.JPG)

**Comment by chris-aeviator** [comment]
@prustar @jpeizer1 

can you confirm the issue still exist for you:
- horizontal scrolling in active layer box (right side) still present – y/n?
- vertical scrollbar in active layer box (right side) still overlapping the icons – y/n?
- horizontal scrollbar in layer catalogue (bottom) still present – y/n?
- vertical scrollbar in layer catalogue (bottom) still overlapping icons – y/n?

I tested in all of my browser's and it's note the case for any of those points.

**Comment by chris-aeviator** [comment]
_removing label p1 as map explorer development is on freeze for V2 development_
