### ISSUE TITLE
Deployment process and impact on menu items -- dead links on pre-production

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#549]
There are currently some inconsistencies between anchor targets for menu item URLs on staging and pre-production. We need to test them thoroughly but also require clarification on menu items first.

My understanding is that:
1. Country-specific menu items (those created by Wordpress admins) would be migrated and would hence remain on staging if added there.
2. Menu items in code on pre-production (all items besides country-specific menu items) would overwrite the values on staging

On pre production, there are problems with some of the data hub menu items -- e.g. clicking the "data" menu item (https://pp-data.opendevelopmentmekong.net/dataset?extras_odm_spatial_range=kh) throws a 502 error. The equivalent URL on staging does not throw this error: https://data.opendevelopmentmekong.net/dataset?extras_odm_spatial_range=kh

@acorbi @chris-aeviator Please clarify.

**Comment by chris-aeviator** [comment]
https://pp-data.opendevelopmentmekong.net/dataset?extras_odm_spatial_range=kh

is working for me, seems to be the server issue.

As long as country-specific menus are not set using "custom link" everything will be smothely migrated.
