### ISSUE TITLE
New features for OD Content Taxonomy widget

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#55]
Hi @mishari,

Please add/subtract the following functionality to/from the OD Content Taxonomy widget:
1. Title for the widget: "Topic areas"
2. Make text static -- users should not be able to click through to category pages.
3. Hide "Uncategorized" briefing category from widget.

Cheers,
Dan

**Comment by Huyeng** [comment]
The functionality of the OD Content Taxonomy widget has been updated to provide the ability to enter the title as well as include and exclude the category by the ID. If the excluded/included IDs more than one, so separated by commas, eg 1,16,22,35

Here is the new feature of OD Content Taxonomy widget:
![screenshot_4](https://cloud.githubusercontent.com/assets/6613530/7085267/46f77af0-df9f-11e4-834f-4c75c151b9bd.jpg)
