### ISSUE TITLE
OD Cambodia menu items: clarification

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#550]
Please clarify final wording and targets for desired menu items on OD Cambodia:
https://cambodia.opendevelopmentmekong.net/kh/

Also indicate if you would like the "data" menu item to point to:
https://data.opendevelopmentmekong.net/dataset?extras_odm_spatial_range=kh
or
https://data.opendevelopmentmekong.net/

**Comment by chris-aeviator** [comment]
data link **needs** to point to 
https://data.opendevelopmentmekong.net/dataset?extras_odm_spatial_range=kh , but please do not set any absoulute links, the links are generated from php code. 

Targets in wp should be set using the wordpress page selector on the left and not by custom link.
