### ISSUE TITLE
Word wrap - Under logo issue on data records

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#551]
This is still not looking right -- Wordwrap of organization 

OPEN DEVELOPMENT C
AMBODIA 

under logo on the records. Other countries too?

![logo-wordwrap](https://cloud.githubusercontent.com/assets/16559612/12401578/5ae20cf8-bdf5-11e5-971b-3a35596f4bc5.JPG)

**Comment by kathi-aeviator** [comment]
@jpeizer1 do you mean that the "c" from "cambodia" is broken - written in 2 lines?

**Comment by kathi-aeviator** [comment]
@jpeizer1 you labeled this issue in "PK1" but I guess you meen first priory, did you? "PK1" = "package 1" and "p1" = first priority! Please note!

**Comment by jpeizer1** [comment]
Kathi, honestly...... What did you think I meant? The title is:
Word wrap - Under logo issue on data records

I described the problem as

OPEN DEVELOPMENT C
AMBODIA 

And sent a picture.

**Comment by acorbi** [comment]
Fixed
