### ISSUE TITLE
Headline and Navigation Menu have not translated in Khmer site

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/opendev-wptheme#552]
The navigation menu items should be translated in Khmer language once switch to Khmer site.
![screenshot_22](https://cloud.githubusercontent.com/assets/6613530/12407698/184cc832-be8c-11e5-9145-1b309cf80a81.jpg)

**Comment by acorbi** [comment]
@Huyeng the code contains calls to gettext translation function ( _e() ) so it indicates that those translations are not in the .po files integrated with the wordpress theme

**Comment by acorbi** [comment]
@Huyeng I saw you did https://github.com/OpenDevelopmentMekong/opendev-wptheme/pull/553#event-518673886 , so,.... is this fixed?
