### ISSUE TITLE
Navigation: make the width of menu navigation wide across the site wide

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/opendev-wptheme#555]
![screenshot_23](https://cloud.githubusercontent.com/assets/6613530/12412028/23df512c-beb6-11e5-8f2f-bf2013546465.jpg)

**Comment by chris-aeviator** [comment]
this is caused by your commit in https://github.com/OpenDevelopmentMekong/opendev-wptheme/commit/a6086e49f7348e1c3c17d8c77251493a83ed9b10#diff-cf7ccbf757dd3a0c3ff92c85efc4f847R558

when you remove those css lines again it's working fine!

**Comment by chris-aeviator** [comment]
oh sorry..was already assigned to you :)

**Comment by Huyeng** [comment]
I knew that's why I assigned to myself. I will fix it soon.

**Comment by Huyeng** [comment]
Fixed.
