### ISSUE TITLE
MAPEXPLORER: specified colors for categories

### ISSUE THREAD

**Issue by kathi-aeviator** [OpenDevelopmentMekong/opendev-wptheme#557]
# 0EB20B
# FFEE07
# FF8600
# FF003E
# 2E0CCC
# 00C7A4

**Comment by chris-aeviator** [comment]
@kathi-aeviator 

could you please provide feedback on the implementation present at 
https://pp-cambodia.opendevelopmentmekong.net/map-explorer
![bildschirmfoto 2016-02-15 um 11 57 50](https://cloud.githubusercontent.com/assets/11522213/13046835/64d622e8-d3db-11e5-9bd9-3575629d8ad2.png)

**Comment by chris-aeviator** [comment]
changing the rest of the color's according to the provided color scheme now, see https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/539

**Comment by kathi-aeviator** [comment]
@chris-aeviator: yellow on white is not readable enough! Please implement "#FFD825" for "environment" for bg as well as for the layer HLs!
