### ISSUE TITLE
ELC PROFILES: Amendments section is incomplete & doesn't show up properly

### ISSUE THREAD

**Issue by gimmemochi** [OpenDevelopmentMekong/opendev-wptheme#569]
Text is cropped off. 
<img width="969" alt="screen shot 2016-01-19 at 6 18 17 pm" src="https://cloud.githubusercontent.com/assets/6489398/12417320/d6c91340-bed9-11e5-8695-e2ce7e73bdb9.png">

The amendments only show 1 event, not all. Thus, this listing is incomplete. 
<img width="969" alt="screen shot 2016-01-19 at 6 18 17 pm" src="https://cloud.githubusercontent.com/assets/6489398/12417414/8b187886-beda-11e5-8d76-22b988ca20a3.png">

**Comment by acorbi** [comment]
Can we consider this fixed?

**Comment by gimmemochi** [comment]
Hi Alex. You fixed the first issue (first screenshot) with the new layout adjustment. The second one has not bee fixed yet. Please see explanation below: 

1). Missing "amended texts"
Phea Phimex (map_id = elc_gdc_7) has been amended 34 times. Please see (using map_id filter on CKAN): https://data.opendevelopmentmekong.net/dataset/economic-land-concessions/resource/8cc0c651-8131-404e-bbce-7fe6af728f89?type=dataset

The Phea Phimex profiles page only shows one amendment. Please see: https://cambodia.opendevelopmentmekong.net/company-profiles/economic-land-concessions/?map_id=elc_gdc_7

2) Missing amendment references
On the Phea Phimex page, the amended text (for the one reference that is displayed on the page) refer to a "Sub-Decree No. 218, dated on 06 May 2013, 1549.90 hectares ..." (legacy file name: Sub_Decree_No_218__06.05.2013.pdf).

This sub-decree is not listed in the "References" section but is available on CKAN law compendium. Please see: https://data.opendevelopmentmekong.net/laws_record/sub-decree-no-218-06-05-2013-pdf

I check another concession to see if I can produce the same inconsistency. 
https://cambodia.opendevelopmentmekong.net/company-profiles/economic-land-concessions/?map_id=elc_gdc_116
This ELCs has been downsized 5 times but only shows one downsizing event in the profile page.

**Comment by acorbi** [comment]
@gimmemochi thanks for the detailed explanation. I will try to find some time this weekend and fix it, It should not be a lot of effort.
