### ISSUE TITLE
MAP EXPLORER: Legend display is random

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/opendev-wptheme#570]
I can't show this well in screen shots however the legend display function is random. When you have several layers open some do not display and others will. 

For instance when economic land concessions and protected area are selected the protected area legend does not open. 
![map-explorer11](https://cloud.githubusercontent.com/assets/14996905/12417660/e12d3012-bea9-11e5-9634-08a0b1009ea7.JPG)

However if you select just the protected area on its own the legend displays. 

![map-explorer12](https://cloud.githubusercontent.com/assets/14996905/12417673/f1cc1fa0-bea9-11e5-80f7-44c5566da27e.JPG)

Also can you please make the i icon remove the information and the legend at the same time. Atm if you don't hid the legend but close the information it still displays the legend. 

![map-explorer13](https://cloud.githubusercontent.com/assets/14996905/12417747/8d9cc164-beaa-11e5-920c-936edf6c669b.JPG)

**Comment by chris-aeviator** [comment]
oh that's a bug, will take care of it!

**Comment by chris-aeviator** [comment]
Fixed & deployed to production!
