### ISSUE TITLE
ELC PROFILES: Khmer page is not availble

### ISSUE THREAD

**Issue by gimmemochi** [OpenDevelopmentMekong/opendev-wptheme#575]
How it appears on PP site:
<img width="1134" alt="screen shot 2016-01-19 at 8 52 47 pm" src="https://cloud.githubusercontent.com/assets/6489398/12420436/25ecb912-beef-11e5-9a79-8f3448d77594.png">

How it appears on the staging site:
<img width="1130" alt="screen shot 2016-01-19 at 7 33 19 pm" src="https://cloud.githubusercontent.com/assets/6489398/12420440/2bbc4e3e-beef-11e5-9ab8-a61208adb9fd.png">

**Comment by acorbi** [comment]
Fixed
