### ISSUE TITLE
Search Langauge Selection in Myanmar, Laos, Thailand -- In English & German

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#577]
Intead fo teh appropriate language for the country

![search-wronglanguage](https://cloud.githubusercontent.com/assets/16559612/12420490/f4c66f2c-be8a-11e5-9025-095a60ec4931.JPG)

**Comment by acorbi** [comment]
@Huyeng @chris-aeviator @jpeizer1 this is a configuration issue of the qtranslateX on the mentioned sites. Just remove German form the list of supported languages on https://myanmar.opendevelopmentmekong.net/wp-admin

**Comment by jpeizer1** [comment]
BTW I do not have access to WP-Admin in New York to change this
