### ISSUE TITLE
Company Profiles Menu Item Not aligned on Cambodian Site

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#578]
Its not aligned with other items

![menu-item-outofsync](https://cloud.githubusercontent.com/assets/16559612/12422103/3892a178-be93-11e5-99ba-0649a6cfae8d.JPG)

**Comment by chris-aeviator** [comment]
due to missconfiguration...

correct configuration:
![bildschirmfoto 2016-01-19 um 22 21 50](https://cloud.githubusercontent.com/assets/11522213/12422784/2c63a678-befb-11e5-803e-b8d7c04a6c71.png)
(already implemented)
