### ISSUE TITLE
Check cookie for saving country value

### ISSUE THREAD

**Issue by chris-aeviator** [OpenDevelopmentMekong/opendev-wptheme#580]
When moving from cambodia to datahub the sidebar states mekong as the current country site. Ensure the cookie is working for production

**Comment by chris-aeviator** [comment]
Fixed, please Test with your Browsers !

**Comment by chris-aeviator** [comment]
re-opening as the bug is back in the system

@Huyeng could you please check if this relates to your changes with moving logic from jeo to jeo-odm when you check the master-branches ?!

**Comment by acorbi** [comment]
@chris-aeviator @Huyeng is this fixed? please close issue if so

**Comment by chris-aeviator** [comment]
@acorbi 

seem's fixed, closing
