### ISSUE TITLE
ELC -- Trim Error - Warning Message

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#581]
Shows up in title on all selected records now....

![elc-trim-error](https://cloud.githubusercontent.com/assets/16559612/12424522/8a5446dc-be9e-11e5-9494-85cf482fd592.JPG)

**Comment by acorbi** [comment]
Fixed via ed0ff67f2a2338398e1ab70d37e31578ba1f7038
