### ISSUE TITLE
Search, Download, whitespace on concession page cuts off table

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#582]
The "Search" and "Download" controls seem to 'float' in a weird position on the page, obscuring the table of concession results. A white bar the same width as them cuts off the rest of the table.

![elctablecut](https://cloud.githubusercontent.com/assets/1206387/12424608/89784c62-bf03-11e5-8c36-191c69237708.png)

**Comment by chris-aeviator** [comment]
current implementation works with horizontal scrolling, @acorbi any idea on improving this?

**Comment by chris-aeviator** [comment]
This has been hotfixed and will be implemented according to the design after we return to Europe !
