### ISSUE TITLE
Cambodia -- Menu Items not aligned correctly

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#585]
Profiles  and now Laws and Agreements Not aligned to other items

![menu-items-notaligned](https://cloud.githubusercontent.com/assets/16559612/12425125/5d451876-bea1-11e5-882a-07d4f9abbe66.JPG)
![menu-item-outofsync](https://cloud.githubusercontent.com/assets/16559612/12426948/86f9b39e-beaa-11e5-9fd7-c1548d7fc992.JPG)
![menu-alignmentissue](https://cloud.githubusercontent.com/assets/16559612/12426980/a7cbbf18-beaa-11e5-8ee3-575284439618.JPG)

**Comment by jpeizer1** [comment]
Will look amateurish for presentation to our donors tomorrow and is clearly noticeable - hence the high priority

**Comment by chris-aeviator** [comment]
`one-line country1` needed to be added to company profiles
`one-line country2` to be added to more information
as css classes in the wp menu editor
