### ISSUE TITLE
Social Network Button Formats on Issue Pages need to be aligned properly

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#586]
https://cambodia.opendevelopmentmekong.net/topics/social-development

Social network Buttons overlap menu list and Twitter button should align to BOTTOM With facebook and Google Buttons and not to the TOP COUNTER's of those buttons.

![socialnetwork-buttons](https://cloud.githubusercontent.com/assets/16559612/12425669/e3ddb2ce-bea3-11e5-8e87-33c8c403eff4.JPG)

**Comment by Huyeng** [comment]
Will change with the icomoon icons instead that recommenced on this issue https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/445
