### ISSUE TITLE
Cambodian Home Page Width issue and Overlap Error

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#587]
Its set up wider than the other pages and as a result on smaller screens and browsers the logo text overlaps the icon text. You can see the problem on a wide screen setup - Cambodia page has to wide a setting versus mekong and other pages set more narrowly that work when the browser is smaller

![ws-cambodia](https://cloud.githubusercontent.com/assets/16559612/12426196/8dd1318c-bea6-11e5-91ac-889c53b91afe.JPG)
![ws-homepage](https://cloud.githubusercontent.com/assets/16559612/12426202/95c8b2de-bea6-11e5-9573-806db3194314.JPG)

Overlap issue because of this wider format On Cambodia that is inconsistent with other pages.
![hp-cambodia](https://cloud.githubusercontent.com/assets/16559612/12426241/c3a8200e-bea6-11e5-95b0-9ab8382c8a36.JPG)

**Comment by DBishton** [comment]
Hi @Huyeng can you look into this one as a priority? The width for Cambodia should be the same as for OD Mekong and it effects the responsiveness and layout of the theme a lot.

**Comment by Huyeng** [comment]
Fixed.
