### ISSUE TITLE
Country instance navigation does not reflect current site

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#588]
Country instance selector in LHS bar does not reflect current site, always displays "Mekong".

![countryselector](https://cloud.githubusercontent.com/assets/1206387/12426721/b5a69b72-bf0d-11e5-9259-ff77b533a638.png)

**Comment by chris-aeviator** [comment]
related to https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/580

**Comment by acorbi** [comment]
yeah, duplicated. closing...
