### ISSUE TITLE
Map Explorer Category Titles STILL exceed their boxes

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#590]
In Mekong, Vietnam, Laos, Thailand and Myanmar 

This is the only Thing that rachel could see actually function post-deployment and that she liked. So it needs to look right everywhere. 

![mapserver-menu-items](https://cloud.githubusercontent.com/assets/16559612/12427675/934489ae-beae-11e5-94cf-17e0f2b36523.JPG)

**Comment by DBishton** [comment]
I've changed the title of the map layer category for "Environment" for all country instances, which resolves this issue.
