### ISSUE TITLE
ELC PROFILES: Add Khmer text to the profiles page on Khmer site

### ISSUE THREAD

**Issue by gimmemochi** [OpenDevelopmentMekong/opendev-wptheme#593]
![screen shot 2016-01-20 at 2 18 27 am](https://cloud.githubusercontent.com/assets/6489398/12429374/761862ec-bf1c-11e5-9beb-313a4dbf607c.png)

use the following text:

កំណត់សំគាល់៖ សំណុំទិន្នន័យនេះ មានទិន្នន័យអំពីសម្បទានដីសេដ្ឋកិច្ចក្នុងប្រទេសកម្ពុជា ដែលមានកាលបរិច្ឆេទកិច្ចសន្យាចាប់ផ្តើមពីឆ្នាំ១៩៩៦ ដល់ឆ្នាំ២០១២។សំណុំ​ទិន្នន័យ​នេះ​ ត្រូវ​បាន​ធ្វើ​បច្ចុប្បន្នភាព​នៅ​ខែមិថុនា​ឆ្នាំ​ ២០១៥​ ដើម្បី​រួម​បញ្ចូល​ ព័ត៌មាន​អំពី​ការ​កាត់​បន្ថយ​ទំហំ​ដី​ និង​ការ​ដកហូត​អាជ្ញាប័ណ្ណ​ ដែល​ជា​លទ្ធផល​នៃ​ការ​វាយតម្លៃ​សម្បទាន​ដី​សេដ្ឋកិច្ច​ នៃ​បទបញ្ជា ០១​ ដែល​បាន​ចាប់ផ្តើម​ឡើង​នៅ​ឆ្នាំ​២០១២​ ។​ ដោយសារ​តែ​កង្វះ​ឯកសារ​ស្តី​ពី​សម្បទាន​ដី​សេដ្ឋកិច្ច​ សំណុំ​ទិន្នន័យ​នេះ​ ពុំ​មាន​ព័ត៌មាន​ទាក់ទង​នឹង​ការ​កាត់​បន្ថយ​ថេរវេលា​នៃ​កិច្ចសន្យា​ ដែល​កើត​ចេញ​មក​ពី​ដំណើរការ​វាយតម្លៃ​សម្បទាន​ដី​សេដ្ឋកិច្ច​ក្នុង​ឆ្នាំ​ ២០១៥​ ។​

​អង្គការ​ទិន្នន័យ​អំពី​ការ​អភិវឌ្ឍ​ ព្យាយាម​ធ្វើ​ឱ្យ​ទិន្នន័យ​អំពី​ក្រុមហ៊ុន​ និង​ការ​វិនិយោគ​ទាំងឡាយ​ មាន​បច្ចុប្បន្នភាព​ និង​សុក្រឹត​។​ ប៉ុន្តែ​ស្ថានភាព​នៃ​ការ​អភិវឌ្ឍ​ មានការ​ប្រែប្រួល​ជា​ញឹកញាប់​ ។​ ក្រុមហ៊ុន​មួយ​ចំនួន​ បាន​បោះបង់​ចោល​សម្បទាន​ដី​សេដ្ឋកិច្ច​ ឬ​ទុក​ឱ្យ​ដី​ទំនេរ​ចោល​ ហើយ​សម្បទាន​ដី​សេដ្ឋកិច្ច​ខ្លះ​ទៀត​ ត្រូវ​បាន​រាជរដ្ឋាភិបាល​ដកហូត​អាជ្ញាប័ណ្ណ​ ឬ​កាត់​បន្ថយ​ទំហំ​ដី​។​ គម្រោង​មួយ​ចំនួន​ ត្រូវ​បាន​ផ្តល់​សច្ចានុមតិ​ ប៉ុន្តែ​មិន​ទាន់​បាន​ដាក់​បញ្ចូល​នៅ​ទី​នេះ​ ពីព្រោះ​ ​អូ​ឌី​ស៊ី​ មិន​ទាន់​រកបាន​ឯកសារយោង​ដែល​គួរ​ឱ្យ​ទុកចិត្ត​នៅឡើយ​។​ យើងខ្ញុំ​សូម​សំណូមពរ​ឱ្យ​អ្នក​ប្រើប្រាស់​សំណុំ​ទិន្នន័យ​ ធ្វើការ​ផ្ទៀងផ្ទាត់​ទិន្នន័យ​ដែល​ទាញ​យក​ពី​​អូ​ឌី​ស៊ី​។​ សូម​ជួយ​ផ្តល់​ដំណឹង​មក​កាន់​យើងខ្ញុំ​ ប្រសិនបើ​លោក​អ្នក​មើលឃើញ​ពី​កំហុសឆ្គង​ ឬ​ការ​ភ្លេចភ្លាំង​ដោយ​ប្រការ​ណាមួយ​។​

កំណត់ចំណាំ​៖​ ឯកសារ​ស្តី​ពី​ការ​កាត់​បន្ថយ​ផ្ទៃដី​ចេញពី​សម្បទាន​ដី​សេដ្ឋកិច្ច​ដែល​មាន​ជា​សាធារណៈ​ ពុំមាន​ភ្ជាប់​ផែនទី​មក​ជាមួយ​ឡើយ​។​ ដូច្នេះ​អូ​ឌី​ស៊ី មិន​អាច​បង្ហាញ​ផ្ទៃដី​ដែល​ត្រូវ​បាន​កាត់​ចេញ​នៅ​លើ​ផែនទី​។​ សម្បទាន​ដី​សេដ្ឋកិច្ច​នៅ​លើ​ផែនទី​អន្តរ​កម្ម​ បង្ហាញ​នូវ​ទំហំ​ផ្ទៃដី​ដើម​។​

Or, you can copy from this link: http://www.opendevelopmentcambodia.net/kh/company-profiles/

**Comment by acorbi** [comment]
Fixed via https://github.com/OpenDevelopmentMekong/opendev-wptheme/commit/e12c576c2087f8799e1834b852e77c28db56f801 and by adding the content on the page
