### ISSUE TITLE
Add new map group

### ISSUE THREAD

**Issue by mishari** [OpenDevelopmentMekong/opendev-wptheme#6]
<a href="https://github.com/Huyeng"><img src="https://avatars.githubusercontent.com/u/6613530?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Huyeng](https://github.com/Huyeng)**
_Thursday Jan 22, 2015 at 07:21 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/oeco/opendev-wptheme/issues/7_

---

Testing http://odmekong.geojournalism.org:
Can't add to the map groups, while the button Add map not work.

**Comment by mishari** [comment]
<a href="https://github.com/miguelpeixe"><img src="https://avatars.githubusercontent.com/u/820752?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [miguelpeixe](https://github.com/miguelpeixe)**
_Friday Jan 23, 2015 at 16:29 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

---

It is working ok here. We had a feel problems with the wpckan plugin breaking the dashboard javascript a few days ago but this is already fixed. Can you try again and report me a more specific error if it happens again?

**Comment by mishari** [comment]
<a href="https://github.com/WillieShubert"><img src="https://avatars.githubusercontent.com/u/3870349?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [WillieShubert](https://github.com/WillieShubert)**
_Saturday Feb 07, 2015 at 07:03 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

---

The first map group on OD Mekong  is made and set it to the home page. 

Here is an outline of the steps. We can add this to the making maps with Jeo tutorial 
http://geojournalism.org/tracks/jeo-wordpress-theme/

##Map Groups
1.  Add map group
2.  Name map group 
3.  Add the maps to the group
a.  More Maps check box
4.  Open JEO settings
5.   In front page tab select the chosen map-group for the home page.

**Comment by mishari** [comment]
@DBishton @Huyeng is this issue considered resolved?

**Comment by Huyeng** [comment]
Yes, It is.
