### ISSUE TITLE
Retitle "Table of Contents" widget to "On this page"

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#60]
Please change the title of this widget.

![image](https://cloud.githubusercontent.com/assets/1206387/7369181/c5d7dcfa-edd9-11e4-9069-ec1b9f75a8cb.png)

**Comment by Huyeng** [comment]
Changing the title of the widget, the translation file need to update too.

**Comment by Huyeng** [comment]
Fixed.
