### ISSUE TITLE
ELC - Table Scroll Bar & Other Formatting Issues

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#603]
Can we:

1) Place the DISCLAIMER AND NOTE below the data Table so the table is right under the Map That way people can see when a search is occurring.

2) Left Align the top map and SEARCH and DOWNLOAD blocks next to the map so its looks correct for large screened monitors?

3) Move the horizontal scroll bar on the table to the top instead of bottom so its easier for users to see?

![elc-formatting](https://cloud.githubusercontent.com/assets/16559612/12659162/4c4d96ce-c5db-11e5-8e95-b2a8718df810.JPG)

**Comment by jpeizer1** [comment]
@Huyeng 
In addition to above I just noted that the zoom and Social network BUTTONS on the map have just gone blank  in production version.

![buttons-missing](https://cloud.githubusercontent.com/assets/16559612/12723487/ac453646-c8d7-11e5-9839-91e6b8de550d.JPG)

**Comment by Huyeng** [comment]
1) Place the DISCLAIMER AND NOTE: done
2) Left Align the top map and SEARCH and DOWNLOAD blocks next to the map: done
3) Mored the horizontal scroll bar on the table to the top, the header is fixed when the page is scrolled up.
I don't have the problem with those icons. what browser did you view?
![screenshot_6](https://cloud.githubusercontent.com/assets/6613530/12747504/ed970ebc-c9d6-11e5-81a7-5af1fc14d9a3.jpg)

**Comment by jpeizer1** [comment]
@Huyeng This button issue seems to have been fixed in the last 24 hours and I wonder if it was fixed when Aeviator updated the button issues in Map Explorer. I was in Firefox and it works now for me as well
