### ISSUE TITLE
ELC - Download buttons - Duplicates Confusing?

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#623]
Am just a bit concerned the multiple buttons with the same labels are confusing and may look like dups... I thought it might be an error until I moused over to see the difference between 4 duplicate CSV buttons. I wonder if it would be better to reduce the buttons by a little and put them in a vertical list left aligned to the download bar they are under -- and then put a short single line of text after each button explaining it.

![elc-download](https://cloud.githubusercontent.com/assets/16559612/12537608/04d5fe14-c291-11e5-9e2c-eea5264dec83.JPG)

**Comment by prustar** [comment]
I noticed this as well and wonder if it's not best to simply provide a link to CKAN where the files are already listed and described, this way they can also read the metadata at the same time. 
https://data.opendevelopmentmekong.net/dataset/economic-land-concessions?type=dataset

**Comment by kathi-aeviator** [comment]
I agree with prustars proposal. One button for each data opportunity. 

@chris-aeviator can you please implement that?

**Comment by chris-aeviator** [comment]
I will check why the download buttons appear multiple times, this shouldn't be happening.

**Comment by chris-aeviator** [comment]
@jpeizer1 @kathi-aeviator @prustar 

The current implementation goes beyond the design. When we were planing and feedbacking this section there was supposed one dataset (containing all ELC's in different formats). Current implementation has multiple datasets and explains why we have multiple CSV, geoJSON, ZIP, ... files appearing. (see screenshot)

![elc_resources](https://cloud.githubusercontent.com/assets/11522213/13358780/42d48570-dcb1-11e5-9dfc-eeb1e96d5479.png)

There needs to be the dataset title appearing close to or when interacting with the icons.

I agree with JP's solution but also putting a simple 'download dataset' ( with a link to the ckan page on the screenshot) ,like prustart suggested, would work.

@kathi-aeviator 
can you make clear what makes most sense from your view?

**Comment by prustar** [comment]
@chris-aeviator @kathi-aeviator This will be a recurring issue in the profile section because the database for this information has not been centralised or consistent. I'm working on this. So for the moment it's best to put just one link to the resource in CKAN only then people can determine which piece of information/data they want to download and look at.

**Comment by kathi-aeviator** [comment]
@chris-aeviator  I agree with prustar

**Comment by chris-aeviator** [comment]
@kathi-aeviator 

can you then please provide a proposal on how this should look like

e.g.
font, font size, font weight, wording

**Comment by kathi-aeviator** [comment]
@chris-aeviator take one single button (the down arrow) to the CKAN download-site instead of all the separated ones.

**Comment by kathi-aeviator** [comment]
Temporary solution of this issue from tec- and design-site is to copy the CKAN list and constitute it in the download-section in WP until the files are sorted.

@chris-aeviator do you agree with that?

**Comment by Huyeng** [comment]
The duplicated file formats of CSV, geoJSON, ZIP and SHP in the download box on profile page are improved by grouping the format of each extensions into one unique. If one format contains multiple URLs for downloading, the drop down list will show up. See the screenshot:
![screenshot_10](https://cloud.githubusercontent.com/assets/6613530/15172954/4839e76e-1783-11e6-80a7-d9e43470bb85.png)

**Comment by prustar** [comment]
This solution seems like it would work fine, the only issue I see is finding a solution to present this on the front end which I know @acorbi and team are working on. If we have two separate shapefiles (1 point/ 1 polygon) then would it seem practical to send the user to separate 'screens' for each individually when in CKAN they are stored together with the same metadata?

**Comment by acorbi** [comment]
@huyeng looks good to me. i would just try to keep that dropdown menu consistant with other elements of the UI in terms of design.

@prustar since the expected behaviour is to download the file directly ( and not being taken to another screen) i think there is no problem with this approach.

**Comment by Huyeng** [comment]
What is design of the dropdown menu of the UI? 

@prustar, like Alex said, those just link directly to download.

**Comment by acorbi** [comment]
@huyeng zhere is no design proposal for it. i would say, keep it as unified as possible with the current UI elements

**Comment by Huyeng** [comment]
Done. please check and give comment on that. 
https://cambodia.opendevelopmentmekong.net/kh/profiles/economic-land-concessions/#

**Comment by acorbi** [comment]
@prustar reopened? not working as expected?

**Comment by prustar** [comment]
@Huyeng This is great and reduces the confusion with the differing file types -- however none of the download files have metadata embedded in them, so we still need to find a way to direct the user to the metadata if they need it. I understand this is part of the redesign that @acorbi is working on.

**Comment by prustar** [comment]
@acorbi @Huyeng  What are the interim solution options for this?

**Comment by Huyeng** [comment]
@prustar, each downloading file has metadata embedded in them, it will be confused to the user. 
Why one dataset of ELC has several metadata. 
With the current updated code, there is a link under the download that bring users to view the metadate of ELC dataset. Look at the below for example:
![screenshot_13](https://cloud.githubusercontent.com/assets/6613530/15310265/7bd612de-1c18-11e6-94c0-089380f749bc.png)
https://pp-cambodia.opendevelopmentmekong.net/profiles/economic-land-concessions/

**Comment by prustar** [comment]
@acorbi the function is great except that it didn't allow the user to view the metadata because it didn't take them to the CKAN entry. Now with @Huyeng 's link on the bottom it makes more sense. Thanks looks great and more towards the new re-design style ;)
