### ISSUE TITLE
"References" to appear in Khmer on Khmer pages

### ISSUE THREAD

**Issue by gimmemochi** [OpenDevelopmentMekong/opendev-wptheme#629]
<img width="741" alt="screen shot 2016-01-28 at 12 08 02 pm" src="https://cloud.githubusercontent.com/assets/6489398/12635646/224c51a8-c5b8-11e5-8e89-0b7024de1a3c.png">
https://cambodia.opendevelopmentmekong.net/kh/topics/land/

**Comment by Huyeng** [comment]
Fixed!
![screenshot_9](https://cloud.githubusercontent.com/assets/6613530/12711598/cbfe22ec-c8f3-11e5-8a7f-1c67b3f59ebf.jpg)
