### ISSUE TITLE
Disable links and mouse-over action for Myanmar, Laos, Vietnam and Thailand

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#63]
Menu items for the country instances that are in development should not be clickable. Mouse-over menu items "news", "maps" and "issues" should not display. Menu should display placeholder text (to be provided) -- text in screenshot is just for demonstration.

![image](https://cloud.githubusercontent.com/assets/1206387/7389675/68be7da0-ee9a-11e4-9ad6-faf8d9a19376.png)

**Comment by mishari** [comment]
How do we know whether a country is in development or not? Is it better to just remove the country from the list entirely?

**Comment by acorbi** [comment]
Optimally, I would tweak the odm-jeo child theme and add a BIG checkbox that would indicate if a site is in development or not. If in development, the corresponding menu would appear as indicated per this Issue, if not, it would display normal...

**Comment by acorbi** [comment]
Also, in order to reduce costs, we could hardcode a list of **sites in development" into the theme's logic and document it properly on the wiki, something like:

``` php
$sites_in_development = array('Laos','Myanmar');
if (in_array($site_name,$sites_in_development)){
   showInDevelopmentMenu();
}else{
  showNormalMenu();
}
```

**Comment by DBishton** [comment]
@acorbi Good suggestion. @mishari It's ideal that we are able to manually set which countries are in development. For the time being, this is all countries that are not actively adding new material.

**Comment by acorbi** [comment]
@DBishton then optimally, we should include a setting into the **open development theme options** http://opendevelopmentmekong.net/wp-admin/themes.php?page=opendev_options

**Comment by acorbi** [comment]
This Issue is related to this closed Issue https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/77. I would suggest that we add another little setting to the theme's configuration as in #77. The setting could be something like "Site in development" and when activated, then the button will be disabled. Let's not forget to adjust the CSS so users can "see" which buttons are disabled.

**Comment by Huyeng** [comment]
If a button of  "Site in development" of a country (Laos) is enable, does the menu of country (Laos) is click-able to the its website? Or a message like "Site is coming soon" appear once hover on it?

**Comment by acorbi** [comment]
I would do:
- Button is not clickable (disabled)
- AND a tooltip ( See http://speckycdn.sdm.netdna-cdn.com/wp-content/uploads/2009/09/jquerytooltip1.jpg ) would be presented with the message "Site coming soon"

**Comment by Huyeng** [comment]
I have add the setting to enable and disable the link of the country menu, and Message of Construction will be appeared on mouse hover. 
- Screenshot of the option in the setting page: 
- If the Site in development is activate, then the country menu on top bar is not clickable.
- The entry message in Message Construction will be appeared on hover, the default message is "Site coming soon." 
  ![site-option](https://cloud.githubusercontent.com/assets/6613530/7626857/d2a34444-fa39-11e4-84d3-ba821f1ed3b9.jpg)
- On Front-end, take Laos site as example.
  ![site-1](https://cloud.githubusercontent.com/assets/6613530/7626894/5a00b656-fa3a-11e4-9c5c-29ac06c86508.jpg)

**Comment by acorbi** [comment]
:+1: Like the solution!
