### ISSUE TITLE
Some of taxonomy items are missed in Taxonomy Navigation

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/opendev-wptheme#630]
Some of the taxonomy are missed in the topic navigation list of topic pages such the sub category of the Government, pleas check.

**Comment by Huyeng** [comment]
I would like to enhance the topic navigation to be able to expend and collapse them like this:
![screenshot_6](https://cloud.githubusercontent.com/assets/6613530/12643172/1ae860d4-c5ed-11e5-9c4b-ee81113768a3.jpg)
If everyone thought that is good, then I will update the code and implement it which fixing the issue above.
@DBishton and @gimmemochi , what do you think?

**Comment by jpeizer1** [comment]
This looks like a pretty good idea to me...

**Comment by Huyeng** [comment]
Enhanced now.  Please check.
