### ISSUE TITLE
Change "issues" text to "topics" in menu, add icon

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#64]
Please change all instances of "issues" to "topics" in the mouse-over action of the menu. Please also add an icon for the new "topics" menu item.
![image](https://cloud.githubusercontent.com/assets/1206387/7389745/47fb7c34-ee9b-11e4-9890-37e8f6d6d782.png)

Please also change text on mous-over from "latest issues" to "latest topic updates".

**Comment by DBishton** [comment]
Suggest an icon from the Entypo set we are using for other icons: http://opendevelopmentmekong.net/wp-content/themes/jeo-odm/font/entypo.pdf

**Comment by Huyeng** [comment]
fixed.
