### ISSUE TITLE
Change all references to "briefing/s" to "topic/s"

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#65]
The current OD child theme for JEO includes reference to "issues" and "briefings". We would like them all to be referred to as "topics". This means:

Change "briefing/s" post type to "topic/s"

![image](https://cloud.githubusercontent.com/assets/1206387/7390115/ea591eb6-ee9e-11e4-8653-b056d09a036c.png)

Rename and retitle "Briefings" page to "Topics"

![image](https://cloud.githubusercontent.com/assets/1206387/7390130/16e50ee0-ee9f-11e4-8e2e-5406cd29c91e.png)

**Comment by Huyeng** [comment]
This is not only change the title or label, but the post type from briefing to topic. Changing post type is will change all things relevant including data in database, file names, and some codes for briefing page, search functions and so on.

**Comment by Huyeng** [comment]
To fix this task, not only update the codes, but also the some data in database. I would like to suspend everyone's work who are working on live site about 30mins, while I working on this task. Please let me know when can implement this task.

**Comment by Huyeng** [comment]
Done. Please check, if you find any issue, please let me know.
