### ISSUE TITLE
New Map Exploror Format Bugs Just Appeared - Missing Download, Info Buttons, Key items appearing off background

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#653]
- Missing Download Button on Key
- Missing Information button on key
- Multiple Key item "fall off" background

![map-explores-error](https://cloud.githubusercontent.com/assets/16559612/12724429/ef15d936-c8db-11e5-9b43-02e1c65c1458.JPG)

**Comment by chris-aeviator** [comment]
Fixed this!

![bildschirmfoto 2016-02-02 um 10 50 22](https://cloud.githubusercontent.com/assets/11522213/12739287/ce8156fe-c99a-11e5-8b65-b191ab7b30f7.png)
