### ISSUE TITLE
MAP Explorer -- Description Indentation issues

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#671]
In both the category and key menus the indenting of first line of the description is far to the right. Note that in one case (2nd to top on INFRASTRUCTURE)  the indented description is intermingled with the title as well.

![severeindent](https://cloud.githubusercontent.com/assets/16559612/12821361/152add18-cb31-11e5-9a0a-0a6a6efa7830.JPG)

**Comment by prustar** [comment]
JP, in the initial spec that Aeviator gave us there was supposed to be a long and short description. I was never able to ascertain where these descriptions should have been kept/logged in the WP end therefore the descriptions are duplicated in both the catalog and active window which I believe is an over kill. My recommendation is to remove the description from the catalog bars entirely, maintaining it only in the active windows for now.

**Comment by chris-aeviator** [comment]
@prustar 
I aggree with your suggestion to not show duplicate info, as long as the layer title is meaningful.

@kathi-aeviator do you agree with the solution to only show the description texts in the active layer section?

**Comment by kathi-aeviator** [comment]
@chris-aeviator Yes I agree with prustar. The informations should be in the active layer.

**Comment by chris-aeviator** [comment]
_removing label p1 as map explorer development is on freeze for V2 development_
