### ISSUE TITLE
Add margin-bottom for map explorer 

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#69]
The map found on http://opendevelopmentmekong.net/map-explorer/ whould be separated from the footer in order to mantain layout armony.

![bildschirmfoto 2015-05-03 um 17 22 56](https://cloud.githubusercontent.com/assets/384894/7445546/291621d6-f1b9-11e4-8fbd-e051c3762a27.png)

**Comment by Huyeng** [comment]
Fixed.
