### ISSUE TITLE
Map Explorer: Move the map category from bottom to left side

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/opendev-wptheme#692]

**Comment by chris-aeviator** [comment]
The agreed design features the categories to be on the bottom, if there are enhancements you whish to see please make your suggestions here.

**Comment by jpeizer1** [comment]
@prustar @chris-aeviator The categories are proving inflexible at the bottom. More than the few categories we can place there are needed, The menu's popping from the bottom are proving to be counterintuitive so the suggestion was to have the menu categories on the  right side in a vertical menu where where more can exist. The legend will open by default popping up at the bottom right. This is a mockup below but Pyrou can provide more specific insight, as she is now overseeing look and feel of explorer. 
![mining-licenses-selected](https://cloud.githubusercontent.com/assets/16559612/13080731/f594f342-d497-11e5-92b9-e76daf8fa6a8.jpg)

**Comment by kathi-aeviator** [comment]
@jpeizer1 just to make clear what is your solution to this issue:
1. exchanging the active layer section and the list of layers to choose (map category)
2. showing the contend of the active layers by clicking on the HL of the layer
3. fixing the active area on the left side + scroll bar

Your 3 rd note is not clear enough for me. It would be great if you could explain that point a bit more for not misunderstanding. I'm sure we will find a conclusion.

**Comment by prustar** [comment]
@chris-aeviator @kathi-aeviator 

After some user feedback from various people the Map Explorer has been heavily critiqued as being less than optimally functional. I have outlined a series of changes and new fixes that will take into consideration these suggestions and more to improve the usability of the Map Explorer. 

Please see the spec outlined here and as discussed with @Huyeng who will be undertaking most of these tasks as per my understanding. 

https://docs.google.com/document/d/1zqPRxF80w2x_zVJ7psm2saK9zYulqy02VZiOdEGFABw/edit?usp=sharing

I also assumed that @DBishton had already discussed this with you?
