### ISSUE TITLE
Resource link symbols have no function

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/opendev-wptheme#696]
The Related Resource link on each page list the links to CKAN resources however also display an icon for file types. These are large and bulk spliting up the list and have not function currently. Suggest to remove them as if they did have function they would all direct the user to the same dataset page in CKAN where these file types are all listed and it would improve the visual list. 

![resourcelinks](https://cloud.githubusercontent.com/assets/14996905/13220971/48a67818-d979-11e5-8ad3-35b498d30d05.JPG)

**Comment by kathi-aeviator** [comment]
I agree with prustars solution to disable them because not having functionality! --> add to p1
