### ISSUE TITLE
Add marker icon

### ISSUE THREAD

**Issue by mishari** [OpenDevelopmentMekong/opendev-wptheme#7]
<a href="https://github.com/Huyeng"><img src="https://avatars.githubusercontent.com/u/6613530?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Huyeng](https://github.com/Huyeng)**
_Thursday Jan 22, 2015 at 07:23 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/oeco/opendev-wptheme/issues/8_

---

Testing http://odmekong.geojournalism.org:
Setup marker icon function did not work as expected.

**Comment by mishari** [comment]
<a href="https://github.com/miguelpeixe"><img src="https://avatars.githubusercontent.com/u/820752?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [miguelpeixe](https://github.com/miguelpeixe)**
_Friday Jan 23, 2015 at 16:29 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

---

It is working ok here. We had a feel problems with the wpckan plugin breaking the dashboard javascript a few days ago but this is already fixed. Can you try again and report me a more specific error if it happens again?

**Comment by Huyeng** [comment]
It was fixed for last updated child theme.
