### ISSUE TITLE
News Container // Change font size to allow more characters in headline containers

### ISSUE THREAD

**Issue by chris-aeviator** [OpenDevelopmentMekong/opendev-wptheme#719]
@kathi-aeviator 

could you please provide a proposal on this?

**Comment by kathi-aeviator** [comment]
@chris-aeviator Can you post a screenshot on this issue, please?

**Comment by chris-aeviator** [comment]
This is the news explorer, you will find it :smile:

---

Christopher Krempel
ÆVIATOR.CC
Pflügerstr 18
D-12047 Berlin

www.aeviator.cc http://www.aeviator.cc/

**Comment by kathi-aeviator** [comment]
@chris-aeviator please implement:

- change font-size from 18px to 14px

code:

.sticky-posts .sticky-item article h3 { font-size: 14px;}

----------
@DBishton @jpeizer1 Please review before deploying on master. This is minimum font-size.

**Comment by kathi-aeviator** [comment]
@chris-aeviator please implement:

change font-size from 18px to 14px
code:

.sticky-posts .sticky-item article h3 { font-size: 14px;}

@DBishton @jpeizer1 Please review before deploying on master. This is minimum font-size.

**Comment by chris-aeviator** [comment]
- deployed to PP
- blocked from deployment to production due to #736

**Comment by chris-aeviator** [comment]
Deployed to Production!
