### ISSUE TITLE
Exchange light and pastel colours for text highlighting

### ISSUE THREAD

**Issue by chris-aeviator** [OpenDevelopmentMekong/opendev-wptheme#722]
> no light or pastel colours for any text -- these do not display on overhead projectors, which are needed for donor presentation. When selecting alternatives, no strong red, purple, orange or pink for text :) 

For the Launch various text's have been given light color schemes on different places on the site 
e.g.
 News Explorer - see screenshot
![bildschirmfoto 2016-03-08 um 11 10 11](https://cloud.githubusercontent.com/assets/11522213/13598616/213e6ba8-e51f-11e5-9b23-0e4f320c5b78.png)

 Company Profiles - https://cambodia.opendevelopmentmekong.net/topics/energy

Please provide and implement an alternative Color scheme for highlighting.

@kathi-aeviator can you please point out which color fit's best of the individual country schemes -> dark cambodia (#06323d) or "middle-dark" cambodia (#12414e) or apply a different color ?

**Comment by kathi-aeviator** [comment]
@chris-aeviator please take the bright one as it is. The differences between the dark colors and the black font are not big enough!

**Comment by kathi-aeviator** [comment]
@chris-aeviator please close issue if no other comment.

**Comment by chris-aeviator** [comment]
@kathi-aeviator 

i think you misunderstood that the bright color is not an option - see quote on the beginning

**Comment by kathi-aeviator** [comment]
@chris-aeviator 

New proposal here: 
- implement "italic" font for the links
- change color into #999

**Comment by chris-aeviator** [comment]
after another iteration the final solution specifies: 
- text will be italic
- color is set to the dark country specific color
- for the content area (links in the topic pages for example) the font is set bold
- for the links in the right sidebar font will stay normal

**Comment by chris-aeviator** [comment]
- deployed to PP
- blocked from deployment to production due to https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/736

**Comment by chris-aeviator** [comment]
Deployed to Production!
