### ISSUE TITLE
MAP EXPLORER: Info window overlapping.

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/opendev-wptheme#735]
This has been raised by a user so I don't have screen shots specifically however when info windows are clicked they can sometimes overlap each other. Is it possible to implement a general default that when a window is clicked it is offset to not overlap a window that is currently open?

**Comment by chris-aeviator** [comment]
I suggest deciding on using one feature (as far as i know this is a cartoDB setting), showing the info window on hover **or** click, not both ( not 100% sure if this is the users intention with the feedback)

**Comment by prustar** [comment]
Thanks @chris-aeviator I've edited most of the info window's in CartoDB to remove the hover function. it should be rectified now with the fix for #512
