### ISSUE TITLE
Combine & compress CSS files for faster page loading

### ISSUE THREAD

**Issue by chris-aeviator** [OpenDevelopmentMekong/opendev-wptheme#745]
Currently we are loading about 34 stylesheets from the server on a page request.

Each request to a stylesheet add's up about 20-100 ms loading time, in worst case this means the site will take 2-3 seconds longer to load.

To make the page load faster, it would be useful if all css files could be combined and minifed by the server for production usage.

An example implementation can be found under https://wp-mix.com/combine-compress-css-files-php/

**Comment by DragonVirus** [comment]
We should use a build system like gulp (http://gulpjs.com/) for this assets management.

**Comment by acorbi** [comment]
Integrating gulp with wordpress might be a good option for this, yes. The main problem I see with these approach is that we would be adding node/npm to the list of dependencies for the wordpress components, at least for development. I haven't done it before but I have found some articles we could dig into:

http://mattbanks.me/gulp-wordpress-development/
https://ahmadawais.com/my-advanced-gulp-workflow-for-wordpress-themes
https://codeable.io/community/speed-up-your-theme-development-with-gulp/
https://github.com/synapticism/wordpress-gulp-starter-kit

Alternative, we could search for wordpress plugins that do the same as specified in https://odinitiative.teamworkpm.net/tasks/5900475

**Comment by acorbi** [comment]
Fixed on new frontend redesign, closing
