### ISSUE TITLE
MAP EXPLORER: Info Window click precision 

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/opendev-wptheme#747]
I've noticed that sometimes when you are hovering to try and click an item to bring up the info window the precision is off and often you need to click around the object to active rather than on the object itself. Can we do something to increase this precision? See random example below, the blue smug is where I need to click to activate the window. 

![infowindow1](https://cloud.githubusercontent.com/assets/14996905/13807718/dff63212-eb62-11e5-86d7-bc9be4b14d78.JPG)

![infowindow2](https://cloud.githubusercontent.com/assets/14996905/13807728/eb26d48e-eb62-11e5-81c1-a8f865e8ec46.JPG)

**Comment by prustar** [comment]
This is another example where the info window precision is incorrect. 
In Map Explorer this example is incorrect the area is not the Tonle Sap
![image](https://cloud.githubusercontent.com/assets/14996905/13813417/c20d5c2a-eb81-11e5-902f-3e9b6369a2f4.png)

In CartoDB it displays it correctly: 
![image](https://cloud.githubusercontent.com/assets/14996905/13813434/de6332aa-eb81-11e5-8dd7-ccfe7ea11b3c.png)

**Comment by prustar** [comment]
In relation to this issue the River layer in ODC does not display the info windows at all. This seems to be only an issue in Chrome @punwath and others have experienced this.

**Comment by prustar** [comment]
@derwas - seems that this issue will be corrected once we upgrade the geospatial components. If so please close.

**Comment by punwath** [comment]
This no longer an issue.
