### ISSUE TITLE
Topic Pages KH: Bold

### ISSUE THREAD

**Issue by ChandaraKhun** [OpenDevelopmentMekong/opendev-wptheme#753]
Unnecessary Bold (B) appears on footnote, foot note number (in body text) and related dataset titles (right hand side). 
![screenshot_1](https://cloud.githubusercontent.com/assets/10953792/13836331/a5141f9e-ec32-11e5-9205-67822ae3c93f.png)

**Comment by ChandaraKhun** [comment]
ODC new site is "not responsive", thus young people with mobile devices might have difficulties in using our site. The following is a screenshot from my I-phone. 
![47d981b768a67f1998d2109fe9f1baf5f834560b97c70f4425 pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/10953792/14076905/3ae4b476-f510-11e5-9043-2085fc69de4d.jpg)

**Comment by Huyeng** [comment]
Responsive issue is moved to issue #774
