### ISSUE TITLE
MAP EXPLORER: Missing legend and info windows

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/opendev-wptheme#759]
The info window and legend is not displaying in some of the layers - see example below. I double checked the links in CartoDB and CKAN as well as the legend html. It all should be displaying. 

![image](https://cloud.githubusercontent.com/assets/14996905/13918131/8e279b7c-ef65-11e5-8e30-eda195f9b52e.png)

**Comment by jpeizer1** [comment]
I dont see the legends displaying at all on OD mekong or OD Vietnam, just blank boxes - so I wonder if the individual map layers are a problem -- and its not some other issue.

**Comment by Huyeng** [comment]
The problem cause by the html of legend that added to the individual map.
There is no legend headline added, I just updated the script to show the layer's title if there is no legend title instead. 
See, the first screenshot has <h5></h5> which is the legend headline that required to have. After updated the code, the tag <h5></h5> is not required. If no <h5></h5> tag, it will use the layers name instead. However, if the legend headline is different from layer name, please add <h5></h5> tag.
Moreover, some html of legend added to legend box is not correct at all, see the screenshot 2.
![screenshot_4](https://cloud.githubusercontent.com/assets/6613530/14069499/dfb8f076-f4c4-11e5-83b2-807f2a6a9bb7.png)  ![screenshot_5](https://cloud.githubusercontent.com/assets/6613530/14069500/dfbb445c-f4c4-11e5-81c9-30f9a372df08.png)

Now the legends of map are shown up.
![screenshot_3](https://cloud.githubusercontent.com/assets/6613530/14069549/dca6369a-f4c5-11e5-9dc3-557c8601e0ca.png)
