### ISSUE TITLE
MAP EXPLORER - Fatal Error - Laos, Thailand, Myanmar

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#760]
When you click map son home page of   Laos, Thailand, Myanmar

You Get:

Fatal error: Call to undefined function qtrans_use() in /var/www/html/wp-content/themes/jeo-odm/inc/layers.php on line 498

**Comment by Huyeng** [comment]
The errors are fixed.
