### ISSUE TITLE
MAP EXPLORER - Map Layer Choice box still too low

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#761]
On wide screen monitors The map layer choose on bottom right doesn't show on whole screen. It cuts off and you have to scroll down to see the rest of the layer categories. So for example it cuts off at ENVIRONMENT on OD mekong and you have to scroll down to see 

HYDROLOGY & INFRASTRUCTURE

 ![maplayer](https://cloud.githubusercontent.com/assets/16559612/13919652/212958c8-ef45-11e5-966a-66624dbe4e3e.JPG)

**Comment by prustar** [comment]
@jpeizer1  I logged this already - see #748
