### ISSUE TITLE
MAP EXPLORER: Blank window when loading map layers

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/opendev-wptheme#762]
When you are loading layers the map reloads itself constantly and leaves a blank white space which takes a while to load. Is there a way to reduce the load times and allow layers to be loaded without reloading the entire map. 

![image](https://cloud.githubusercontent.com/assets/14996905/13925404/76e1ea44-ef88-11e5-9212-6bc386081945.png)

**Comment by prustar** [comment]
in relation to the above enhancement this half loaded screen also appears: 

![image](https://cloud.githubusercontent.com/assets/14996905/13926416/851220f8-ef8c-11e5-9803-c5af2b943393.png)

**Comment by Huyeng** [comment]
They are working fine for me. @prustar, could you try again please. It can cause by the internet issue.
![screenshot_1](https://cloud.githubusercontent.com/assets/6613530/14042819/3373b21c-f2b0-11e5-911a-6f1a0d90f2fc.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/6613530/14042820/33766336-f2b0-11e5-832a-e8506978c59b.png)

**Comment by Huyeng** [comment]
@prustar, could you confirm if the issue still exists?

**Comment by prustar** [comment]
@Huyeng it's not a problem now. I'm closing.
