### ISSUE TITLE
Add setting to disable dropdown box on topbar menu

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#77]
A setting should be added to the Open Development Theme Options. in order to disable the dropdown boxes in the top bar's menu when users hover over it.
![bildschirmfoto 2015-05-05 um 19 15 00](https://cloud.githubusercontent.com/assets/384894/7478431/0e415648-f35b-11e4-899c-49e6e5978750.png)
![bildschirmfoto 2015-05-05 um 19 15 56](https://cloud.githubusercontent.com/assets/384894/7478461/46e2c022-f35b-11e4-92ae-9fc617867beb.png)

**Comment by Huyeng** [comment]
The setting to enable the drop-down box of the country menu has been added. If you would like to disable it, just go to the setting of Open Development Theme Option in Appearance, and open development. See the image.

![screenshot_4](https://cloud.githubusercontent.com/assets/6613530/7560489/dc4b3e5a-f7ed-11e4-901d-dc97c5fc5655.jpg)

**Comment by acorbi** [comment]
@Huyeng very cool! Do not forget to add the strings to the localization workflow
