### ISSUE TITLE
Mapexplorer: need  2 layer box for catodb map

### ISSUE THREAD

**Issue by punwath** [OpenDevelopmentMekong/opendev-wptheme#773]
In the Wordpress now, there is only one box for catodb layer. Therefore, there is only one language can be shown in the Mapexplorer because each layer represents for only 1 language. 

![image](https://cloud.githubusercontent.com/assets/18112596/14075385/f65a0020-f502-11e5-8e32-7a73a5edd292.png)

**Comment by Huyeng** [comment]
Added!
