### ISSUE TITLE
ODC new site is "not responsive", thus young people with mobile devices might have difficulties in using our site. The following is a screenshot from my I-phone. 

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/opendev-wptheme#774]
ODC new site is "not responsive", thus young people with mobile devices might have difficulties in using our site. The following is a screenshot from my I-phone. 
![47d981b768a67f1998d2109fe9f1baf5f834560b97c70f4425 pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/10953792/14076905/3ae4b476-f510-11e5-9043-2085fc69de4d.jpg)

**Comment by ChandaraKhun** [comment]
On Homepage, "Announcements and Press Releases" & "Site Updates" don't have Khmer version yet.
And, all in the capital letters may be adjusted accordingly. 
![screenshot_1](https://cloud.githubusercontent.com/assets/10953792/14340469/512b1230-fcb2-11e5-9a27-c40a237054b3.png)

**Comment by acorbi** [comment]
@Huyeng mobile devices get served with a previous,  but responsive version of jeo-odm. This is a fallback solution until the frontend gets redesigned. closing by now
