### ISSUE TITLE
Alert on deadlinks

### ISSUE THREAD

**Issue by ChandaraKhun** [OpenDevelopmentMekong/opendev-wptheme#776]
Some links on topic pages can not be accessed due to, perhaps, any error with inserting the links onto Word Press, or any changes in URL by news outlets.

It would be great if there is a tool for altering those dead links. 
Here is a tool used on the old site.
![screenshot_3](https://cloud.githubusercontent.com/assets/10953792/14077065/f7c352fe-f511-11e5-93ea-27f32bf8e764.png)

**Comment by Huyeng** [comment]
Broken Link Checker is already installed and used.
