### ISSUE TITLE
ODC Main Menu  MAP & PROFILES Work Inconsistantly

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#786]
ODC Main Menu Production Instance -- DATA selection points to pp development server so no data is being displayed and link goes to: 

https://pp-data.opendevelopmentmekong.net/dataset?extras_odm_spatial_range=kh

**Comment by Huyeng** [comment]
There is not much dataset added into the PP DE. Anyways, the link was fixed since last week by calling wp function to replace the manual links added.
