### ISSUE TITLE
Add background image to header menu

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#79]
Mekong region map, light colored background, almost like an underlay. Would add a bit of interest to the banner without making it cluttered. 

@DBishton Please, can you or David Hindley please provide the background images?

**Comment by chris-aeviator** [comment]
@DBishton @kathi-aeviator 

is this still on the table/wanted ?

**Comment by kathi-aeviator** [comment]
@DBishton @chris-aeviator: From my side not – but if wanted we still need the provided images. Please close issue if clear.
