### ISSUE TITLE
Redundancy in Datahub Main Menu (Cambodia)

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#793]
You have LAWS & AGREEMENTS that resolve to the CKAN data  and LAWS, POLICY & AGREEMENTS that resolve to the new WP front end interface. I think the two are confusing to the user especially when you click on LAWS, POLICY & AGREEMENTS and get a different top menu.

MAPS are also duplicated 

PROFILES and ECONOMIC LAND CONCESSIONS also go to the same WP front end

![capture](https://cloud.githubusercontent.com/assets/16559612/14197945/74ae31ac-f7a2-11e5-85b4-8b51d6a96211.JPG)

**Comment by acorbi** [comment]
Fixed via https://github.com/OpenDevelopmentMekong/ckanext-odm_nav/pull/52
