### ISSUE TITLE
PROFILE PAGE: Enhance ELC profile page template

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/opendev-wptheme#798]
- Profile the filter function to the profile page like the old site. 
- The width of map and table is not fit each together, suggest make their width be equal each other.
- Search box and download box drop down on scolling.

**Comment by acorbi** [comment]
@Huyeng I see you have merged this PR https://github.com/OpenDevelopmentMekong/opendev-wptheme/pull/820. Does it mean that this task can be closed?

**Comment by Huyeng** [comment]
Yes, it was closed.
