### ISSUE TITLE
MAP EXPLORER: Download and Info button in category box

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/opendev-wptheme#799]
The Map Layer category box in the local language site for both Myanmar and Vietnam are not working. Vietnam has already translated their local Map Explorer and will be translating the CKAN entries shortly. It would be nice if they could test the download and info window function as they translate. 

![image](https://cloud.githubusercontent.com/assets/14996905/14246788/bbdf34b2-fa69-11e5-8d8e-014a4c4d31d3.png)

**Comment by Huyeng** [comment]
Please follow this guideline: https://wiki.opendevelopmentmekong.net/partners:adding_maps_to_map_explorer

**Comment by Huyeng** [comment]
Please also  translates the needed strings on transifex: https://www.transifex.com/open-development-mekong/odm-frontend-theme/dashboard/

**Comment by prustar** [comment]
@gimmemochi could you please help to coordinate this with ODV.

**Comment by acorbi** [comment]
@Huyeng @gimmemochi @prustar can you update on the status of this issue? Can this be closed?

**Comment by prustar** [comment]
@acorbi and everyone - thanks for fixing this.
