### ISSUE TITLE
Scaling down of ODM header, topic menu elements and search bar 

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#80]
Reduce the size of the area pictured below:
![hackpad com_lwiveyrusmv_p 221970_1430388358614_screenshot from 2015-04-30 12 05 02](https://cloud.githubusercontent.com/assets/384894/7491712/425fb258-f3ec-11e4-98b6-9b70fb04b3c8.png)
and the height of the search bar, also reducing paddings.

**Comment by Huyeng** [comment]
I just reduced the padding and expanding the width of the topic elements as well as the search box.
The screenshot is updated one.
![screenshot_8](https://cloud.githubusercontent.com/assets/6613530/7582284/3766702a-f8b6-11e4-8fc6-90b466c315b4.jpg)

Update the style-sheet of result box to make it better look, reducing the padding and highlighting the result box separate from the map container. Changing the headline from "Post " to "News".
Preview one:
![screenshot_6](https://cloud.githubusercontent.com/assets/6613530/7582318/8e9c0fa8-f8b6-11e4-8618-84008eefe8b4.jpg)

After updating:
![screenshot_7](https://cloud.githubusercontent.com/assets/6613530/7582311/8364864c-f8b6-11e4-80cd-3ceb143a4ee6.jpg)

**Comment by acorbi** [comment]
ODM Header: Looks good for me, @DBishton ??

For the search results window we have another Issue. Please @Huyeng  address it on https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/82

**Comment by Huyeng** [comment]
I just knew that there is an other issue of search result layout after finishing this one. Now, I have also assigned #82 issue to myself too.

**Comment by acorbi** [comment]
Ok cool, if you do not want to create a new branch to fix this Issue, you can actually work in the same branch and once implemented just add "Fixes #80, Fixes #82" in the comments.. This way, both Issues will be closed once you merge the branch into master
