### ISSUE TITLE
MAP EXPLORER: Missing download and info window symbol

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/opendev-wptheme#800]
ODC map layer - environment category missing the download and info window symbol for Fish sanctuaries. Seems random, I checked and there are CKAN link listed for english language. 

![image](https://cloud.githubusercontent.com/assets/14996905/14315362/e5f8c38c-fbfc-11e5-9665-71078bd35542.png)

**Comment by Huyeng** [comment]
That's because of no link added into download box. Please ask mapper to check it.

**Comment by prustar** [comment]
Thanks @Huyeng I guess the guys checked it out and fixed it.
