### ISSUE TITLE
MAP EXPLORER: line in middle of map

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/opendev-wptheme#806]
There is a white line in the middle of the Cambodia Map Explorer: 

![image](https://cloud.githubusercontent.com/assets/14996905/14522640/d07322a8-022f-11e6-9652-70338cec685c.png)

**Comment by chris-aeviator** [comment]
could be related to 

https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/654

**Comment by jpeizer1** [comment]
@prustar Could you specify which browser and version you see this on? I don't see exactly the same thing on my Firefox browser (latest version) with larger screen - rather when the map comes I see a both a horizontal and vertical line (in the place you indicate) for just a millisecond until everything is fully loaded and then it resolves itself. Also when I select a new layer to use on the map I see the same horizontal and vertical lines appear for a millisecond while the layer is loading and then  it resolves itself.

**Comment by prustar** [comment]
@jpeizer1 I also get these horizontal and vertical lines when layers are loaded and reloaded. I'm using Chrome mainly but also use Firefox on occasion. I had logged an issue regarding the AJAX script after discussion with @acorbi it seems that it's not working correctly and perhaps this is the problem. I will raise with @Huyeng when I speak to her tomorrow re-map explorer progress.

**Comment by Huyeng** [comment]
I think the issue has gone after I fixed this issue https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/654
