### ISSUE TITLE
Remove disclaimer from footer, add small credit line

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#81]
The disclaimer text in the footer of the site should be replaced by a small credit line and disclaimer text should be added to http://opendevelopmentmekong.net/disclaimer/
- [ ] @DBishton Plase coordinate with Terry the drafting of the small credit line ( suggestion was something like This is a project of EWMI-ODI. )
- [ ] Integrate this text into the translation workflow

**Comment by Huyeng** [comment]
To replace and delete the texts of disclaimer texts, please go to the Open Development Theme Option, Find the label "Legal disclaimer", you will see the texts of current disclaimer there.

![screenshot_5](https://cloud.githubusercontent.com/assets/6613530/7560758/3b8b7fb8-f7f0-11e4-9807-2816a89edf6d.jpg)

**Comment by acorbi** [comment]
@DBishton We need still that _small credit line_. Could you please coordinate this?

**Comment by acorbi** [comment]
@DBishton Here a list of pending text definitions https://hackpad.com/Texts-to-draft-0JecDHQYeqG including the small credit line for fixing this issue.

**Comment by acorbi** [comment]
Credit line has been replaced by logo on footer
![bildschirmfoto 2015-07-15 um 00 07 34](https://cloud.githubusercontent.com/assets/384894/8686325/9f958130-2a85-11e5-8800-3e0c2d767111.png)
