### ISSUE TITLE
Layout improvements in dropdown search results window and results screen

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#82]
Add some padding on the bottom so there is a separation with the contents below.
Change background color or add border to differentiate from background.
Add images in case the featured posts contain any. Also add excerpt for the results so the users can better decide if the presented contents are what they were looking for.
![hackpad com_lwiveyrusmv_p 221970_1430388687015_screenshot from 2015-04-30 12 11 19](https://cloud.githubusercontent.com/assets/384894/7491816/b7a30802-f3ed-11e4-933e-c44026c72671.png)
Advanced search page – we require list presentation that takes up less screen space and allows more results to be visible.
Search results should only show published items (eg not RSS items drawn from elsewhere)
- Result box should be improved both Visually and in terms of functionality
- Visually:  Use borders to mark the results area. Increase the number of displayed  results from 6 to 8/10. Add image thumbnails if present. Add a second column showing results from CKAN.
- Advanced search result should show only PUBLISHED contents (not drafted)
- Indicate number of results displayed.
- Remove "Search results" text. Add "SITE RESULTS" above the results list, analog to "DATA RESULTS"
- Search text and magnifying lens should dissapear on click and not on typing.
- On the advanced search, users can select to filter search results by content type. on the list of content types also feeds can be selected and should not:

**Comment by Huyeng** [comment]
What is this sentence referred to "Search text and magnifying lens should dissapear on click and not on typing." 
Why feeds need to add into content type?
Does the feed refer to the post feeds that imported by Importer Feed plugin?
Note: The posts which have 'feed' post type that imported from Imported Feed plugin are automatically published. Most of them have not reviewed yet.

**Comment by acorbi** [comment]
> What is this sentence referred to "Search text and magnifying lens should dissapear on click and not on typing." 

When you click on the search bar, the Text "Search" and the icon are still there, they should dissapear as it happens when you start typing....

> Why feeds need to add into content type?
> Feeds should not appear in the filter box because they are for internal use.
> ![bildschirmfoto 2015-05-12 um 12 09 03](https://cloud.githubusercontent.com/assets/384894/7584732/d4344696-f89f-11e4-9e54-284ca0ee5c24.png)
> 
> Note: The posts which have 'feed' post type that imported from Imported Feed plugin are automatically published. Most of them have not reviewed yet.

Why are they automatically imported, they should not be. should they?

**Comment by Huyeng** [comment]
Well, that's the functionality of the Importer Feed plugin built. That's why the posts of rss feed are appeared on the single page of page. Look at the issue, https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/89.

In DB: all the status of rss posts are "publish".
![feed-1](https://cloud.githubusercontent.com/assets/6613530/7585656/2d4b2482-f8cf-11e4-8bde-d6eb9eaeed2a.jpg)

**Comment by acorbi** [comment]
Ah sorry @Huyeng. I rather wanted to ask:

Why are they being **published** automatically. Are they not supposed to be imported as **drafts** and reviewed by editors prior to publication?

**Comment by Huyeng** [comment]
That's good question. From what I understood, some of feed posts are imported to post type "post" as drafts, then the editors will review and publish. Some of feed posts are imported to post type "rss_feed" as publishes. I don't quite understand about its functionality. Just found that, a post can find in both post and rss feed, but some of other can find in rss_feed, but not post. 
For example:
1. SET closes down 15.58 to 1,485.72  (found in both post type)
2. Corruption probe to investigate forestry officials, own staff (found only rss_feed)
You can try, go to the dashboard, and try to find the post titles above with the link below: 
- http://opendevelopmentmekong.net/wp-admin/edit.php
- http://opendevelopmentmekong.net/wp-admin/edit.php?post_type=rssmi_feed_item

**Comment by acorbi** [comment]
> Some of feed posts are imported to post type "rss_feed" as publishes.
> Is this something we are using somehow? Maybe we do not want/need this at all and basically removing this functionality would fix #89. Can you please investigate this?

**Comment by Huyeng** [comment]
The layouts of result box and advance search are improved:
- Increase the number of item results to 10 in result box
- Image thumbnails is showed up if it is presented
- Search text and magnifying lens disappear on click
- Update "search result" to "Site results"
- Exclude all the feed post type
- The result show only the published post, but the posts of feeds are also showed as their status also published. The feed won't show if fix issue #89. 

Please check if the issue can close?

**Comment by acorbi** [comment]
Ok, some comments:

> Increase the number of item results to 10 in result box
> Image thumbnails is showed up if it is presented.

Sorry for not having specified in the comments but I discussed with @DBishton and @david hinley and concluded that the best would be to present all results with the same _importance_. So optimally, we would have 9 results as in this picture. Obviously, contents would be different..... and no picture would be shown if not present in the post.
![bildschirmfoto 2015-05-12 um 15 01 52](https://cloud.githubusercontent.com/assets/384894/7587957/1d200a42-f8ba-11e4-9730-fc3535db2711.png)

> Search text and magnifying lens disappear on click 

Perfect!

> Update "search result" to "Site results"

I cannot see "Site results" nowhere, anyway, the text "Search results" text should be removed. It is too big and we can put it below (smaller) together with the number of results thus gaining some space.

HINT: If implementing pagination X/Y is too difficult, we can just show the total number of results, example: SITE RESULTS (46) instead of SITE RESULTS (19/46) ....
![bildschirmfoto 2015-05-12 um 15 03 37](https://cloud.githubusercontent.com/assets/384894/7588031/a67381f2-f8ba-11e4-9a36-60a7222d5453.png)

> Exclude all the feed post type

Perfect!

> The result show only the published post, but the posts of feeds are also showed as their status also published. The feed won't show if fix issue #89. 

Yeah, let's fix #89

**Comment by Huyeng** [comment]
Showing the excerpt texts in of each item in the result box as the picture above is so nice, however, I'm afraid that it will be ugly for the other languages such as Khmer. In English, every word has a space, so limiting the number of words is fine, but it Khmer, there is no spacing of each words, unless the writer or editor need to add hidden space (zero space) each word once they are typing. 
Look at this like below, if counting the number of words in Ms word, there is only 9 words.
http://www.opendevelopmentcambodia.net/kh/news/initiative-aimed-at-curbing-begging/

**Comment by Huyeng** [comment]
Search Result Preview in English and Khmer site:
*English
![en](https://cloud.githubusercontent.com/assets/6613530/7604119/2a133cd4-f968-11e4-98bd-e7dd31714b54.jpg)
- Khmer
  ![news](https://cloud.githubusercontent.com/assets/6613530/7604118/2a0a0e48-f968-11e4-98e9-55f1f7aa6fe4.jpg)

**Comment by acorbi** [comment]
What about using something like http://stackoverflow.com/questions/3825226/multi-byte-safe-wordwrap-function-for-utf-8

Question: Does the theme use the wordwrap() function to "cut" the strings to a certain length? In that case we could try replacing the call with one of the mb_wordwrap() function described in the StackOverflow thread.

**Comment by Huyeng** [comment]
Well, I tested the mb_wordwrap(), but it not helpful. There is an other way to solve it, but it requires the to add hidden space of each Khmer words. Otherwise, the result will be displayed as screenshot above.

**Comment by acorbi** [comment]
@Huyeng there are currently 10 news being shown on the search result window, there should be 9. I'll try to fix it myself today. keep you posted
![screenshot from 2015-05-15 12 46 54](https://cloud.githubusercontent.com/assets/384894/7651478/2543beaa-fb01-11e4-8bcd-0e5b0cb490f0.png)
BTW: As seen on this second screenshot, the khmer texts are being rendered properly. What solution did you implement currently on it? I'll try to review the code on branch https://github.com/OpenDevelopmentMekong/opendev-wptheme/tree/impl82 and close the Issue in case it is a valid solution.
![screenshot from 2015-05-15 12 48 08](https://cloud.githubusercontent.com/assets/384894/7651482/284d1aa6-fb01-11e4-86f6-e5575aece61e.png)

**Comment by Huyeng** [comment]
@Alex, I think that you haven't pulled the last change of the codes yet, the number of result items that show on the search result box is 9 only, look at the first screenshot that attached with this comment: https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/82#issuecomment-101514217
![screenshot_19](https://cloud.githubusercontent.com/assets/6613530/7673765/dc13eefe-fd43-11e4-9519-10b375be4689.jpg)

Well, for the Khmer texts, as I told you, I created a function to implement it by using PHP function to implode the space and hidden space of the strings. With this method, it requires the editors who typing a khmer texts need to add hidden space of each word or as much as they can. Most of the news, the editors copy from the other news sources, so a wraptexts tool is need to use to add the zero space before adding into the site, but it will take a bit time. 

If  we can use mb_wordwrap() to solve the Khmer Unicode issues, that is really helpful and reducing editor's time.

**Comment by acorbi** [comment]
@Huyeng I have not managed to reproduce the whole WP Multisite on my development environment completely yet. But while using the search bar on http://opendevelopmentmekong.net, you can see that 10 items are displayed.

**Comment by Huyeng** [comment]
Oh yeah, on the PP Server, it has not updated yet. I just pushed the code into the impl82 only. Would you like me to merge what I did which the master and push to the PPS?

**Comment by acorbi** [comment]
I would say not yet. Let's fix the Issue with Khmer unicode first so we can close the Issue and merge the code properly.

**Comment by Huyeng** [comment]
The issue with Khmer Unicode was spited to a new one which is #97.
