### ISSUE TITLE
Center table alignment on topic pages

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#823]
HTML tags are overridden on tables in topic pages on WordPress. We would like these to always be centred so as to be in line with other embedded elements. 

Please see an example on this page: https://opendevelopmentmekong.net/topics/science-technology/#technologies

This is also urgent as it is preventing this page from being published.

**Comment by acorbi** [comment]
@Huyeng this issue was fixed via b316d7ac615e6b68efc66d67c3e22fd3eb44ed99 , right? I can see its implemented in https://opendevelopmentmekong.net/topics/science-technology/#technologies . Please close this issue if complete. ping @DBishton

**Comment by Huyeng** [comment]
Nope. It wasn't fixed via that commit, but it was fixed by adding class "aligncenter". Thus, the table will be central aligned if the class "aligncenter" is added.
