### ISSUE TITLE
Errors on WP dashboard

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#825]
on https://cambodia.opendevelopmentmekong.net/wp-admin/post.php?post=87686&action=edit

![screenshot from 2016-04-26 14-02-38](https://cloud.githubusercontent.com/assets/384894/14817543/3d685338-0bb8-11e6-8e5c-669541f497d9.png)

**Comment by Huyeng** [comment]
I opened the link, but there is no error. Could you please check and close it if it is fixed, @acorbi.

**Comment by acorbi** [comment]
Cannot reproduce anymore, closing.
