### ISSUE TITLE
Add new "WMS" layer type 

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#83]
Previously titled "Enabled information features on TileLayer layers"

For layers added as TileLayer ( not CartoDB/Mapbox ) users cannot click on the dots or polygons, no popups with information are being presented as it happens with the layers imported by cartodb.

We can implement a new layer type called WMS and by using leaflet.wms.js (https://github.com/heigeo/leaflet.wms) we can visualize WMS layers properly and allow users to click and display content.

**Comment by acorbi** [comment]
Closing. This belongs to https://github.com/OpenDevelopmentMekong/jeo/issues/10

**Comment by Huyeng** [comment]
A few new files need to add and modify in children theme to extend parent's functions.
