### ISSUE TITLE
Profile page tooltips not rendering properly on firefox

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#831]
Browsing https://pp.opendevelopmentmekong.net/profiles/economic-land-concessions/ on firefox I have detected that the tooltips on the table view are not rendering properly and the text is outputted directly on the table cell when it should be shown only when on mouse over.

![screenshot from 2016-04-29 15-18-59](https://cloud.githubusercontent.com/assets/384894/14917171/fc1217a8-0e1d-11e6-9890-cf57aaf936c2.png)

It is working well using chromium:

![screenshot from 2016-04-29 15-19-43](https://cloud.githubusercontent.com/assets/384894/14917170/fc0fe9d8-0e1d-11e6-8222-96a4a4785f89.png)

**Comment by Huyeng** [comment]
I didn't get the same problem on Firefox. @acorbi, pls test it again.

**Comment by acorbi** [comment]
@Huyeng it was my cookies blocker, works now! closing...
