### ISSUE TITLE
Profile pages Cartodb map not showing on firefox

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#832]
Browsing https://pp.opendevelopmentmekong.net/profiles/economic-land-concessions/ with firefox, I have detected that the embedded cartodb map is not showing.

![screenshot from 2016-04-29 15-22-05](https://cloud.githubusercontent.com/assets/384894/14917203/2cd20b82-0e1e-11e6-8ddf-87e82dcb83d5.png)

The same URL on chromium works well

![screenshot from 2016-04-29 15-22-12](https://cloud.githubusercontent.com/assets/384894/14917211/31293408-0e1e-11e6-8a59-63b3e52cdc8a.png)

**Comment by Huyeng** [comment]
@Alex, it works fine for me on Firefox. Could you try again please?

**Comment by acorbi** [comment]
@Huyeng it was my cookies blocker, works now! closing...
