### ISSUE TITLE
Profile Page ELC -- Concession Summary Stats now showing up?

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#834]
I assume these stats at the top of the table should be listing a number next to each item e.g. # of Govt Data Complete Concessions, # of Govt Data Partial Concessions, no?

![suger-concession](https://cloud.githubusercontent.com/assets/16559612/14934092/b2c6644a-0e73-11e6-98f7-db1ec600f0e9.JPG)

**Comment by Huyeng** [comment]
That's the issue on the current site. 

This is the testing url: https://pp.opendevelopmentmekong.net/profiles/economic-land-concessions/
![screenshot_7](https://cloud.githubusercontent.com/assets/6613530/14980038/4b9dcf26-1150-11e6-90f3-ca0f8e3c9730.png)

If the code is pulled, the summary stats will be fixed.

**Comment by acorbi** [comment]
Fixed via 1cc1c3e3777c49391189cd67b846e6f87aac7f26
