### ISSUE TITLE
Profile Page ELC -- Clicking Individual Concession on Map not taking me to detail page on that concession

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#835]
Shouldn't clicking on an individual concession on the map take me to the detail page of that concession in the same way clicking on an item in the table below does? It doesn't now meaning I have to search for the individual concession on the table below the map if I wish to see more detail. 

![indiv-concession](https://cloud.githubusercontent.com/assets/16559612/14934124/f1951d5a-0e74-11e6-93dd-7ddc19d600b4.JPG)

**Comment by prustar** [comment]
@jpeizer1 -- the info windows previously had a read more.. button on them but as the map was created in CartoDB I'm not sure what the added step would be to include this function. I know that it is possible. But to manually add each link in would be time consuming. 

@acorbi @Huyeng  -- is there a way to automate this via the API?

**Comment by acorbi** [comment]
I guess that link would take to the detail page of the corresponding concession? We can study to add this in the code so it is can be automated.

**Comment by jpeizer1** [comment]
Yes, you'd want clicking the concession on the map to take you to the same concession detail as if you clicked corresponding table link on the table. Otherwise the user is left to try and figure out  which concession on the map is related to which table item in order to click through on the table to more detail.

**Comment by Huyeng** [comment]
To add the read more button on pop-up window, this task could be done on Cartodb side. 
My suggestion, custom the html of infowindow of each layer and add the the html code below.
`<p><a href="https://cambodia.opendevelopmentmekong.net/profiles/economic-land-concessions/?map_id={{map_id}}" target="_blank" />View detail</a></p>`

Note: the url of the address need to change based on the profile link, and "**/?map_id={{map_id}}**" must add at the end of the link. See the screenshot below to add the Read more in Cartodb:

![screenshot_16](https://cloud.githubusercontent.com/assets/6613530/15311211/b93b48e2-1c22-11e6-84bb-97096c92f14a.png)

**Comment by prustar** [comment]
Done! Thanks @Huyeng for the code tip!
