### ISSUE TITLE
Map Explorer - ELC Layer- Table Icon Knocked Out of Place in Latest Update

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#837]
I noticed in the latets update the that the Table icon on the map layer chooser was knocked out of place.. Looks like an 1 extra spacer to many...

![elc-table](https://cloud.githubusercontent.com/assets/16559612/14990689/be2971fa-112b-11e6-9754-6c45454a4722.JPG)

I'm using firefox latest version on widescreen monitor

**Comment by acorbi** [comment]
@Huyeng is this issue fixed and can be closed?

**Comment by Huyeng** [comment]
Fixed!
