### ISSUE TITLE
ELC & Mining Datasets // Additional explanation for data types needed to be added

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/opendev-wptheme#841]
Within the map data sets (including ELC, mining) in the previous ODC site there was a '?' placed next to the categories to explain the definition of the attributes. This included for the data sources category for both ELC's and mining and the adjustment type for ELC's. 

The text is in this file: 
[Data_Source_description.txt](https://github.com/OpenDevelopmentMekong/opendev-wptheme/files/248856/Data_Source_description.txt)

Example: 
![image](https://cloud.githubusercontent.com/assets/14996905/15016382/07fe53fa-1211-11e6-9bf0-f1d954f37004.png)

![image](https://cloud.githubusercontent.com/assets/14996905/15016411/2f2d2474-1211-11e6-904d-d77c3ad65773.png)

**Comment by acorbi** [comment]
Fixed
