### ISSUE TITLE
PROFILE PAGE: Adding the related profile pages

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/opendev-wptheme#843]
Need the option that be able to add the related profile pages like what ODC has done before. 
![screenshot_16](https://cloud.githubusercontent.com/assets/6613530/15037290/d2c6f3be-12c3-11e6-92c8-fe03598eaea7.png)

**Comment by acorbi** [comment]
@Huyeng this issue is fixed and can be closed?
