### ISSUE TITLE
Discrepancy on taxonomy box on topic pages

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#850]
Currently, the taxonomic topics are displayed in different order, not alphabetically, in the wordpress frontend:

https://cambodia.opendevelopmentmekong.net/topics/disasters-and-emergency-response
![screenshot from 2016-05-09 12-50-14](https://cloud.githubusercontent.com/assets/384894/15111014/acfee758-15e4-11e6-84fb-d186c2fe30f3.png)

https://opendevelopmentmekong.net/topics/disasters-and-emergency-response
![screenshot from 2016-05-09 12-50-28](https://cloud.githubusercontent.com/assets/384894/15111015/ad0124d2-15e4-11e6-9ff3-3d5a39deeeb0.png)

@Huyeng @gimmemochi is this intended to be like this? why not alphabetical anymore? why the discrepancy?

**Comment by gimmemochi** [comment]
As for ODC, the main categories are intended to be displayed in an
alphabetical order. The sub-categories are intended to be displayed based
on the hierarchical order. Huy Eng made it happened for ODC before the
launch. I believe she implemented this for the other sites including ODM
post launch.

On Mon, May 9, 2016 at 5:52 PM, Alex Corbi notifications@github.com wrote:

> Currently, the taxonomic topics are displayed in different order, not
> alphabetically, in the wordpress frontend:
> 
> https://cambodia.opendevelopmentmekong.net/topics/disasters-and-emergency-response
> [image: screenshot from 2016-05-09 12-50-14]
> https://cloud.githubusercontent.com/assets/384894/15111014/acfee758-15e4-11e6-84fb-d186c2fe30f3.png
> 
> https://opendevelopmentmekong.net/topics/disasters-and-emergency-response
> [image: screenshot from 2016-05-09 12-50-28]
> https://cloud.githubusercontent.com/assets/384894/15111015/ad0124d2-15e4-11e6-9ff3-3d5a39deeeb0.png
> 
> @Huyeng https://github.com/Huyeng @gimmemochi
> https://github.com/gimmemochi is this intended to be like this? why not
> alphabetical anymore? why the discrepancy?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/850

ᐧ

**Comment by Huyeng** [comment]
the main category is displaying in alphabetically order, and the sub categories are also displaying in the hierarchical order after restoring the related plugins.
