### ISSUE TITLE
Artifact on resource download box in ELC profiles

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#856]
Note that 4 appearing in the box.

Happens both on:
https://cambodia.opendevelopmentmekong.net/profiles/economic-land-concessions/
https://cambodia.opendevelopmentmekong.net/kh/profiles/economic-land-concessions/
https://pp-cambodia.opendevelopmentmekong.net/profiles/economic-land-concessions/
https://pp-cambodia.opendevelopmentmekong.net/kh/profiles/economic-land-concessions/

![screenshot from 2016-05-11 10-57-55](https://cloud.githubusercontent.com/assets/384894/15175602/63f9424a-1767-11e6-86f9-7701ca8cbc70.png)

@Huyeng maybe you can fix it as part of the fix for https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/623

**Comment by Huyeng** [comment]
It was fixed.
