### ISSUE TITLE
Reference Document on profile page won't display properly

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/opendev-wptheme#871]
See the error:
![screenshot_17](https://cloud.githubusercontent.com/assets/6613530/15314042/aa9a96fa-1c39-11e6-9373-60b741cc4a3d.png)

**Comment by acorbi** [comment]
@Huyeng which URL?

**Comment by Huyeng** [comment]
oh sorry, I upload the wrong screenshot. It should be this one.
![screenshot_18](https://cloud.githubusercontent.com/assets/6613530/15314925/e479e4f2-1c3e-11e6-813e-adb8fa9bab48.png)

**Comment by Huyeng** [comment]
It will update to show like this:
![screenshot_19](https://cloud.githubusercontent.com/assets/6613530/15314966/113b9e7c-1c3f-11e6-8961-9af5957fffa0.png)
