### ISSUE TITLE
Add Table Icon and Link to Map Explorer Layers with new Profile Concessions 

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#877]
We need Table Icon Links added on the Map Explorer Layers that relate to the new Profile concessions being added just (note table icon on Economic Land Concessions Layer for example
![000065](https://cloud.githubusercontent.com/assets/16559612/15335204/50218728-1c3f-11e6-85b6-af8a168ba360.png)
)

**Comment by Huyeng** [comment]
Those profile pages are on the PP-Site. They will be added on the Main site.

**Comment by punwath** [comment]
Issue was solved.

**Comment by acorbi** [comment]
@Huyeng @punwath can we then close this issue?
