### ISSUE TITLE
No download files for Oil & Gas Profile Page?

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#878]
![oil-gas](https://cloud.githubusercontent.com/assets/16559612/15447082/cadabf64-1f02-11e6-905e-ff7d49912dd0.JPG)

Using Firefox

**Comment by Huyeng** [comment]
Found the problem, the dataset name on CKAN was changed but, the added link didn't update, as a result show nothing. Fixed with updated new url.
