### ISSUE TITLE
CSS adjustment for tables in WordPress

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#888]
I'd like to request a CSS styling tweak to apply consistent styling to basic tables. Currently any tables created with the TablePress plugin have a very small font size for the header row, which looks odd with the larger table cell text.

**Comment by acorbi** [comment]
To be approached as part of the redesign. @DragonVirus Could you please add information about the styling for the tables on https://docs.google.com/document/d/1BYndbNy7ywyFZB1Rtq53RGuCTXN5YP2zClcGJ6T675w/edit

**Comment by Huyeng** [comment]
Fixed and Added.
