### ISSUE TITLE
"English" Flag inconsistant across country sites

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#889]
I notice that on every country site including Mekong the language flag (top right) for English is the Union Jack (English), but in Cambodia its the Stars and Stripes (American). May I suggest this hybrid flag (below) across all pages to denote English? the benefit of this flag is that it immediately denotes a language rather than a country -- which will work better in the new V2 design if we use flags to denote languages because it immediately makes that clear.

![eng-flag](https://cloud.githubusercontent.com/assets/16559612/15502437/df7ef6e8-2181-11e6-86ec-f9a111193930.png)

**Comment by acorbi** [comment]
@jpeizer1 Agreed, I am adding this to the implementation plan document

**Comment by Huyeng** [comment]
Changed them all.
