### ISSUE TITLE
RSS Feed are appearing on single map page incorrectly

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/opendev-wptheme#89]
Currently, RSS feed items that have not been published and been published feeds are appearing on single page of maps. Clicking on them causes a 404 error, and clicking on the published items causes a script error. 
The rss feeds should not appear on the page, only post or topic that relevant will be appeared.

http://opendevelopmentmekong.net/maps/greater-mekong-subregion-hydropower-dams-2014/#!/map=53660 
![feeds](https://cloud.githubusercontent.com/assets/6613530/7585476/455b60c4-f8ce-11e4-91b4-9fb4d41a6910.jpg)

**Comment by acorbi** [comment]
Adding this to milestone 1.2.0. Good catch @Huyeng !

**Comment by Huyeng** [comment]
Let me change the status of rss posts in Feed Items to pending review first. Then let see how it works.

**Comment by acorbi** [comment]
Sounds like a plan!

**Comment by DBishton** [comment]
@Huyeng What action was taken on this issue? I know this RSS feed item issue also affects issue #82. Basically, these published feed items should not appear anywhere on the site. My understanding is that the importer publishes the rss feed items, and is currently configured to also creates a draft post. This draft post is what is reviewed, edited and published by the editors.

Currently, posts from RSS items appear to be being as posts published automatically, even though the importer is not configured to do this (Default post status = "draft" under Autopost settings). e.g. http://opendevelopmentmekong.net/2014/03/03/gm-names-execs-for-southeast-asia-thailand/

Has this been set deliberately?

**Comment by Huyeng** [comment]
That's confusion made by the plugin. 
From my understanding, the all the feed items imported into the feed item database first which set the post status as "publish".  If the option of Autopost setting is enable, it will import the posts from the feed item database as the daft status that did in configuration, and then they will be removed after 1day (minimum setting). See the screenshot:

![screenshot_21](https://cloud.githubusercontent.com/assets/6613530/7764285/4431ec42-0079-11e5-8072-c51984d6f314.jpg)

![screenshot_22](https://cloud.githubusercontent.com/assets/6613530/7764281/339ff702-0079-11e5-82f6-8fa5a535b8e2.jpg)

There are two ways to solve this issue:
1. Customize the plugin to change the status from the publish to draft or pending review
    -  If the new version of plugin release, we need to change the status every released versions
2. Go to Feed Items in dashboard, and change the post status manually

**Comment by acorbi** [comment]
Thanks for looking at this @Huyeng I would prefer the second option where we do not need to change the code.

So, if I understand it correctly, it just takes us to change the value of **Default status of posts** to draft, that's it, right? If so, please, let's configure it like that and close this Issue.

**Comment by Huyeng** [comment]
Well, for the second option, changing the post status refers to the updating the status of the all feed item posts to "draft" every time the feed posts are imported. See the screenshot of what going to do: 

![screenshot_24](https://cloud.githubusercontent.com/assets/6613530/7766467/9f8a117c-0093-11e5-82a2-0613a3caeb2e.jpg)

I would like to change the code rather than. We can fork the plugin from the github repository, https://github.com/wp-plugins/wp-rss-multi-importer, and change the code for our needs.

**Comment by acorbi** [comment]
Yes let's do it! As mentioned I would do this:
- Clone the code of the plugin into our github Organization
- Modify the code so imported RSS Feeds have the 'draft' status per default
- Integrate the installation of the plugin within our workflow (odm-frontend repo)

**Comment by Huyeng** [comment]
The plugin has been integrated and modified the default post status from 'publish' to 'draft'.
From now on, the RSS feeds have been imported as 'draft'.
