### ISSUE TITLE
MAP Explorer -- OD MEKONG - "Map Layer" Title/color on Layer Window no longer displaying

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#899]
![capture](https://cloud.githubusercontent.com/assets/16559612/15831923/e6b2b636-2bed-11e6-989c-81d34b8abbce.JPG)

This is what it looks like displayed with title in Cambodia (although I'd suggest right-indenting the title here as well because its very close to the margin)
![capturea](https://cloud.githubusercontent.com/assets/16559612/15832010/505498f2-2bee-11e6-8572-6c4735a8d80b.JPG)

**Comment by Huyeng** [comment]
It will be fixed when the PR 
https://github.com/OpenDevelopmentMekong/opendev-wptheme/pull/905 is merged and released.

**Comment by acorbi** [comment]
Thanks @Huyeng Im reviewing that PR now

**Comment by acorbi** [comment]
Fixed via 050704a44ecbf28c1f4ee0e29b50b1b18fb9a02a
