### ISSUE TITLE
Top bar menu on hover not reacting

### ISSUE THREAD

**Issue by mishari** [OpenDevelopmentMekong/opendev-wptheme#9]
<a href="https://github.com/acorbi"><img src="https://avatars.githubusercontent.com/u/384894?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [acorbi](https://github.com/acorbi)**
_Sunday Feb 01, 2015 at 09:28 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/oeco/opendev-wptheme/issues/12_

---

![bildschirmfoto 2015-02-01 um 10 24 11](https://cloud.githubusercontent.com/assets/384894/5991640/7c99009e-a9fc-11e4-9cc5-901157d52a93.png)
Tested using firefox 35.0.1 & chrome 40.0.2214.94 (64-bit)
When hovering on the top bar menu over the News or Maps sections, no content is shown. Expected behaviour is that the user can select among the posts of that category.

In case the reason is that there is no post from that category to display, then a message such as "No posts avaialble under this category" should be shown.

**Comment by mishari** [comment]
<a href="https://github.com/Huyeng"><img src="https://avatars.githubusercontent.com/u/6613530?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Huyeng](https://github.com/Huyeng)**
_Sunday Feb 01, 2015 at 13:57 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

---

I agree with Alex, should sow a message if no content available. 
From my understanding, some news of ODC won't show because ODC's news has post types "news" or "post".

**Comment by mishari** [comment]
<a href="https://github.com/acorbi"><img src="https://avatars.githubusercontent.com/u/384894?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [acorbi](https://github.com/acorbi)**
_Sunday Feb 01, 2015 at 14:01 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

---

Then, IMHO, we should do one this 2 things:
1. Bulk change the post types from "news" or "posts" to that type the theme expects.
2. Change the theme logic so it presents also posts with types "news" or "posts".
@miguelpeixe  @Huyeng Which one would you favorise?

**Comment by mishari** [comment]
<a href="https://github.com/miguelpeixe"><img src="https://avatars.githubusercontent.com/u/820752?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [miguelpeixe](https://github.com/miguelpeixe)**
_Tuesday Feb 03, 2015 at 00:55 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

---

On this theme news and posts are the same post type (post). The news title is just to give more meaning to it. I chose to use the default "post" post type because it already contemplates the concept of news on it's default behaviour, without the need of any extra setup.

Any "news" post type from the previous WordPress theme/setup should be migrated to the "post" post type. If you prefer to use "news" post type I can set it up on this theme.

About the menu, the idea is to not interact with non existing content. The menu that has content gets a different hover style (gray background color) to highlight between the 'static' menus. I can change it to show "no content found", but I think that this way is better.

**Comment by mishari** [comment]
<a href="https://github.com/miguelpeixe"><img src="https://avatars.githubusercontent.com/u/820752?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [miguelpeixe](https://github.com/miguelpeixe)**
_Friday Feb 06, 2015 at 17:55 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

---

Any conclusions on this matter?

**Comment by mishari** [comment]
<a href="https://github.com/acorbi"><img src="https://avatars.githubusercontent.com/u/384894?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [acorbi](https://github.com/acorbi)**
_Monday Mar 02, 2015 at 08:27 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

---

I believe now is working fine.

@Huyeng Are we happy how the menu is working now? Should we close this?

**Comment by Huyeng** [comment]
Yes, it should close.
