### ISSUE TITLE
Map explorer layer info windows should close when a layer is deactivated

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#907]
It is unintuitive for the info window to remain when the layer is no longer being displayed. Please see example in screenshot below

![image](https://cloud.githubusercontent.com/assets/1206387/15929382/de3817fe-2e76-11e6-801f-644520104a6c.png)

**Comment by acorbi** [comment]
@huyeng, im assigning this task to you. However it does not have high priority, please focus on https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/717 before

**Comment by Huyeng** [comment]
Fixed with #717.
