### ISSUE TITLE
Map Explorer -- The Foundation Map Layer has vanished in all countries

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#908]
![maps-vanish](https://cloud.githubusercontent.com/assets/16559612/15938332/bf3a4df8-2e40-11e6-97a4-d0cfafb819a0.JPG)

![capturea](https://cloud.githubusercontent.com/assets/16559612/15938389/e41ecfae-2e40-11e6-9b41-893878ac4055.JPG)

![capture3](https://cloud.githubusercontent.com/assets/16559612/15938420/04fa782c-2e41-11e6-96c0-31a47de2b8ac.JPG)

![capturerf](https://cloud.githubusercontent.com/assets/16559612/15938457/3a3306d0-2e41-11e6-9c25-76642c80d44c.JPG)

**Comment by acorbi** [comment]
@jpeizer1 please try refreshing your browser with CTRL + F5 or browsing the site in incognito mode, I believe this is a cache issue...

**Comment by jpeizer1** [comment]
Thanks Alex - that did it (CTRL+F5) - I had to do it for each country map instance  -- The question is how many other users experience this same thing without knowing how to clear it and move on instead... Is it that my browser was up when a change was made? Had I completely closed and restarted my browser would this error have cleared automatically? IS it useful to say somewhere "if you have trouble seeing the maps clear your cache - press CTRL+F5? BW I was also trying this to see if I could get a map layer form Myanmar to show and unfortunately like Pyrou the wheel spins but nothing else happens. In vietnam it seems to work though.

**Comment by acorbi** [comment]
> The question is how many other users experience this same thing without knowing how to clear it and move on instead

I believe some user might have similar issues but would dissapear once the browser caching would be cleared. This can be triggered in many ways, without needing the action of the user. So I would not worry that much.

> IS it useful to say somewhere "if you have trouble seeing the maps clear your cache - press CTRL+F5?

I would not do that...

Closing this Issue now, please reopen if you can reproduce it in the future.
