### ISSUE TITLE
Mixed Khmer and English Number 

### ISSUE THREAD

**Issue by S-mardii** [OpenDevelopmentMekong/opendev-wptheme#916]
on ទំហំផ្ទៃក្រឡាតំបន់ការពារធម្មជាតិគិតជាហិចតា column, the number appear in both khmer and english.
![screenshot_3](https://cloud.githubusercontent.com/assets/18528756/16002239/d267d952-3180-11e6-925e-bb9a0dbe6e8a.png)

**Comment by S-mardii** [comment]
https://cambodia.opendevelopmentmekong.net/kh/profiles/natural-protected-areas/

**Comment by acorbi** [comment]
@S-mardii I would say this happens because there is no khmer value on the dataset for those rows and therefore the code fallsback to english, which would be the expected behaviour. Can you please check if the dataset contains that information?

**Comment by S-mardii** [comment]
@acorbi  Thanks for the clue. I will check it out.

**Comment by S-mardii** [comment]
After checking the data, the issue happened due to the fact that the dataset posted by the mapper consist of a comma in the number (e.g. 2,000,000), so that the function detect those data with comma as strings not numeric.

The issue is now fixed as the mapper has deleted the comma from the data in that column.

**Comment by acorbi** [comment]
@S-mardii good catch, thanks!
