### ISSUE TITLE
Search bar does not appear on pages/posts other than home page.

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#92]
Search should be presented consistently and on all pages. Suggest it be integrated into the header menu.

Home page:
![image](https://cloud.githubusercontent.com/assets/1206387/7604006/c6cbb918-f966-11e4-948a-9cf261c6e3ef.png)

All other pages/posts:
![image](https://cloud.githubusercontent.com/assets/1206387/7604015/db5b5668-f966-11e4-9c47-d0db765710d6.png)

**Comment by acorbi** [comment]
+1 for this, adding to https://hackpad.com/Sprint-05.15-towards-v1.2.0--eOA1d2VjJAi and the sprint's projection..

**Comment by Huyeng** [comment]
Any comment if the search bar place this position and the drop down search box be appear like this:
![screenshot_7](https://cloud.githubusercontent.com/assets/6613530/7811258/19e039f0-03d3-11e5-96d6-d9d344bb40fe.jpg)

![screenshot_6](https://cloud.githubusercontent.com/assets/6613530/7811152/3a67d346-03d2-11e5-8c2f-c0b53180b3f4.jpg)

Or Do you prefer to make it overlay the other?

![screenshot_5](https://cloud.githubusercontent.com/assets/6613530/7811237/f3db8ba6-03d2-11e5-8c7a-8a667172a7f1.jpg)

**Comment by Huyeng** [comment]
Voted: #2. 
Done.
