### ISSUE TITLE
Profile Page // SEZ info window fonts and legend

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/opendev-wptheme#920]
@punwath Please see screenshot below, the info window fonts sizes are not consistent and the legend is not displaying the symbol. 

![image](https://cloud.githubusercontent.com/assets/14996905/16060708/72325a12-3289-11e6-85af-2b774e09bc76.png)

**Comment by punwath** [comment]
Solved already.

**Comment by Huyeng** [comment]
Thanks for solving this @punwath.
