### ISSUE TITLE
Decrease font size for WordPress reference footnotes

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#922]
Try has requested that we visually distinguish footnotes from the body text of the page for aesthetic reasons. Please decrease the font size for footnotes (references) by two points.

![image](https://cloud.githubusercontent.com/assets/1206387/16071907/34f787b0-3308-11e6-838d-8995574b1009.png)

**Comment by acorbi** [comment]
Fixed via 49897eeae9af96d44b9e9d91402e05cddc45754c
