### ISSUE TITLE
Enhance the styling of the base layers

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/opendev-wptheme#924]
After adding a few base layers onto the map explorer, it noticed that, the items won't show inline due to the the long texts and adding thumbnail of base layers. See the screenshot below:
![screenshot_12](https://cloud.githubusercontent.com/assets/6613530/16074047/eea267c0-3312-11e6-8d55-bb154b71ebe7.png)

Suggesting design: 
![screenshot_10](https://cloud.githubusercontent.com/assets/6613530/16074260/dadf793e-3313-11e6-8178-307cf0a12fe5.png)

**Comment by acorbi** [comment]
fixed via 40cfbca09a1567c74510378429c34c05090ac157
