### ISSUE TITLE
"Read MORE" link on ODC SLIDER for new ELC Data resolves to 404

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#927]
When i click read more on this below I get the 404 page rather than going to profiles...

![elc-slider-404](https://cloud.githubusercontent.com/assets/16559612/16109977/8b0cea84-3379-11e6-8277-348df573d298.JPG)

@Huyeng (Also wouldn't it be better to put newly updated slider pages as the first slider page (or after map explorer first slide) so that new information is presented quickly to the user and it's obvious something on the site has changed? It takes quite a while for the site to load, and then more time for the slider to auto-cycle and the fact that the newest information is at the end of slider worries me that user leaves before he/she sees new slider information.

**Comment by Huyeng** [comment]
Yes, you are right. The updated information should be presented on the first or second slide. 
Since the new function of profile page is implemented, the link was changed, but we forget to update the link on slider. Right now, it was updated.
