### ISSUE TITLE
Map Explorer -- ODC -- Energy map layers not showing or turning off in ENVI/LANDSAT/TOPO mode

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#928]
I can't see any of the ENERGY layers showing up on either the ENVI, Landsat or TOPO maps and if I switch between the TOPO, LANDSAT maps while these Energy layers are "on" I also cannot turn the layers off even though I dont see them appear on the base maps (e.g. I can't uncheck the energy layer radio buttons).

![layer-issues](https://cloud.githubusercontent.com/assets/16559612/16110289/11d5dd22-337b-11e6-87e4-96b3bee6f828.JPG)

**Comment by S-mardii** [comment]
@jpeizer1 Which browser do you use?

**Comment by jpeizer1** [comment]
Firefox latest versions.

**Comment by acorbi** [comment]
@jpeizer1 can you still reproduce this issue? does it get solved when you refresh with CTRL + F5 ?

**Comment by jpeizer1** [comment]
@corbi I can confirm it has been fixed - the layers show up on top of all the various background layers and the layers now click on and off without getting stuck in on position.

**Comment by acorbi** [comment]
Then we close this issue :cactus:
