### ISSUE TITLE
Myanmar language switcher flag is incorrect

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/opendev-wptheme#929]
The flag for the language switcher on the platform for Myanmar needs to be updated to the recent 2010 flag see: 

https://en.wikipedia.org/wiki/Flag_of_Myanmar

**Comment by acorbi** [comment]
Fixed via https://github.com/OpenDevelopmentMekong/odm-frontend/commit/25d15ae4416b270f2919fbc48b09b7c125fa7a80
