### ISSUE TITLE
Remove "bullets" from Feature Box

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#931]
Hi @Huyeng, please remove the "bullets" styling from the links  in the Feature Box plugin. Many thanks!

![image](https://cloud.githubusercontent.com/assets/1206387/16169783/4f3f39ba-3565-11e6-8343-67fa9f7d159b.png)

**Comment by acorbi** [comment]
Fixed via https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/939
