### ISSUE TITLE
"wpckan query resources" widget throws error

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#935]
Adding "wpckan query resources" widget to ODMm topic page causes error: 

"Warning: require(/var/www/html/wp-content/plugins/wpckan/utils/../templates/ddataset-listphp): failed to open stream: No such file or directory in /var/www/html/wp-content/plugins/wpckan/utils/wpckan-utils.php on line 304

Fatal error: require(): Failed opening required '/var/www/html/wp-content/plugins/wpckan/utils/../templates/ddataset-listphp' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/wp-content/plugins/wpckan/utils/wpckan-utils.php on line 304"

https://myanmar.opendevelopmentmekong.net/?post_type=topic&p=239&preview=true

![image](https://cloud.githubusercontent.com/assets/1206387/16183236/922736e0-36d9-11e6-81f9-fe9e983dbd88.png)

**Comment by acorbi** [comment]
@DBishton @Huyeng Fixed.

The problem was that the only post on the myanmar country site, which was the default test hellow orld post from wordpress, was not multiligual. closing....

**Comment by acorbi** [comment]
reopening, wrong issue
