### ISSUE TITLE
WordPress "bullet" text line spacing is inconsistent

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#936]
When using "bullet" formatting on text in WordPress, the line spacing is different to the body text:

Please make it the same.

![image](https://cloud.githubusercontent.com/assets/1206387/16183502/c2fca3d8-36dc-11e6-8db7-d3afaf374b03.png)

**Comment by Huyeng** [comment]
Code is updated!

**Comment by acorbi** [comment]
@Huyeng can we close this now then? @dbishton?

**Comment by acorbi** [comment]
Fixed via 64f59b6746e277a0997dd2967f8212e8731f45f9
