### ISSUE TITLE
Related news widget throws error 

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#937]
Adding the "related news" widget to the Myanmar page throws error:

"Fatal error: Call to undefined function qtrans_useCurrentLanguageIfNotFoundUseDefaultLanguage() in /var/www/html/wp-content/themes/jeo-odm/inc/od-related-recent-news-widget.php on line 44"

![image](https://cloud.githubusercontent.com/assets/1206387/16184040/17717708-36e3-11e6-9929-83fe44d5cd0c.png)

**Comment by acorbi** [comment]
@DBishton @Huyeng Fixed.

The problem was that the only post on the myanmar country site, which was the default test hellow orld post from wordpress, was not multiligual. closing....
