### ISSUE TITLE
PROFILE PAGE // ODV SITE

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/opendev-wptheme#947]
ODV will be presenting their new Hydropower Research at a workshop this Thursday and they are cleaning and translating the data as we speak. I wanted them to simply make the dataset available on CKAN for users to use but they would like to upload into WP as a profile. 

I created a draft page already but there is no menu for profiles yet on the ODV site. Could this please be added URGENTLY, the workshop is on this Thursday. 

![image](https://cloud.githubusercontent.com/assets/14996905/16225585/a2743218-37a7-11e6-9843-876596ebf5f3.png)

**Comment by acorbi** [comment]
@prustar you need to publish that Profile Page before we can link it from the menu. Once done, please ping me or @DBishton and we will added the link on the header

**Comment by prustar** [comment]
@acorbi Thanks will do. It's in draft format currently now with nothing in it.
