### ISSUE TITLE
WPCKAN library items being displayed as datasets

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#948]
Filtered WPCKAN resources on the OD Vietnam land page (https://vietnam.opendevelopmentmekong.net/topics/land) displays all resources as datasets, when spot -checking reveals that many are library items. No "related library items" widget appears on the page.

![image](https://cloud.githubusercontent.com/assets/1206387/16228200/d0e66854-37df-11e6-8283-cee2e98b14e9.png)

Widget appears to be configured to display library items if available:

![image](https://cloud.githubusercontent.com/assets/1206387/16228242/0c86c408-37e0-11e6-8f95-66bb31bd6b8b.png)

**Comment by acorbi** [comment]
@DBishton actually, all the related datasets added to the vietnamese land page are library records. the inconsistency relied on the fact that the widget had a wrong title. Now it is fixed and the related resources appear on the **Related library records**.

Closing
