### ISSUE TITLE
ODC PROFILE // INDIGENOUS COMMUNITY

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/opendev-wptheme#951]
@ChandaraKhun @samean -- I like the new Indigenous community land profile page. 
Could you please however edit the map to zoom a little more into Cambodia. Edit the legend to include the colours of the various dots and apply info windows using the standard template. Please include the information: 
IP Name,
IP land area,
Title land area, 
No. of families. 

![image](https://cloud.githubusercontent.com/assets/14996905/16308640/1b5054fe-3966-11e6-8ed3-43a554e64d89.png)

**Comment by Huyeng** [comment]
The JSON API of cartodb has error with custom legend , the color of legends doesn't appear if customized. Suggestion: please do not custom it.
