### ISSUE TITLE
MAP EXPLORER // CartoDB legend

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/opendev-wptheme#955]
@Huyeng -- I added a title to the legend on the profile page of the new IP communal land map and it removed the colours for the points? This has to be a bug because in the Map explorer it works fine. 

![image](https://cloud.githubusercontent.com/assets/14996905/16334867/da4b6676-3a03-11e6-82c2-07173cf68340.png)

**Comment by Huyeng** [comment]
Fixed.
