### ISSUE TITLE
Error Khmer Translation on Laws Page

### ISSUE THREAD

**Issue by S-mardii** [OpenDevelopmentMekong/opendev-wptheme#963]
The summary of data above the table is not translated when switch into Khmer Language.

![screenshot_2](https://cloud.githubusercontent.com/assets/18528756/16477094/f90b89ce-3eb8-11e6-85f6-e1538048363a.png)

**Comment by acorbi** [comment]
Fixed via https://github.com/OpenDevelopmentMekong/opendev-wptheme/pull/968
