### ISSUE TITLE
ODC MAP EXPLORER Hydro Power Reservoir DOWNLOAD gives 404 error

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#966]
When you click the download error for Hydro reservoir map layer in ODC Map Explorer you get a 404 error 

https://data.opendevelopmentmekong.net/dataset/hydropower-reservoirs-in-cambodia-1999-2010?type=dataset

![image](https://cloud.githubusercontent.com/assets/16559612/16484360/ce2e86de-3e86-11e6-8355-12fe1cb783e1.png)

BTW I decided to test _ALL_ the ODC downloads for each layer that has one and this was the only 404 I found.

**Comment by acorbi** [comment]
@jpeizer1 fixing....

**Comment by acorbi** [comment]
@jpeizer1 the problem relied on the dataset's name having changed. this is an Issue that got fixed a while ago but there could be other download links not working. can you please check them all? and reopen/report on this Issue if you find any other 404?

**Comment by jpeizer1** [comment]
@acrobi -- please note my comment at bottom of original posting under graphic- "BTW I decided to test ALL the ODC downloads for each layer that has one and this was the only 404 I found."
