### ISSUE TITLE
Word wrap and Line wrap for Khmer Unicode

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/opendev-wptheme#97]
Khmer texts are not rendered properly in the drop-down search result as well as the briefing page.
Right now, in order to wrap the texts, it requires the editors need to add the hidden space while they are typing or using the tool to adding the zero space. However, it overlap the texts still happens sometimes. 
May be  the mb_wordwrap() function could solve the problem and reduce the editor times. 

![news](https://cloud.githubusercontent.com/assets/6613530/7604118/2a0a0e48-f968-11e4-98e9-55f1f7aa6fe4.jpg)

**Comment by chris-aeviator** [comment]
this seems fixed, my khmer is up to zero knowledge, but I  tried to start a search with one of the top topic items (see screenshot)

![bildschirmfoto 2016-02-29 um 18 20 54](https://cloud.githubusercontent.com/assets/11522213/13402600/56f95adc-df11-11e5-8f9a-85a54a04b85e.png)
