### ISSUE TITLE
Clustered markers not being hidden

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#977]
![screenshot from 2016-07-07 16-30-57](https://cloud.githubusercontent.com/assets/384894/16656845/7613d9b0-4460-11e6-9706-93b521df9a25.png)

on https://cambodia.opendevelopmentmekong.net/maps/families-with-less-than-1ha-rice-land/#!/story=post-95562&loc=11.92110315424958,104.765625,7, there are both **single** and **clustered**. When I click **Hide news icons** , only the **single** markers disappear.

**Comment by Huyeng** [comment]
fixed.
