### ISSUE TITLE
Error link for the Cambodia daily English news (double http)

### ISSUE THREAD

**Issue by Linnie08** [OpenDevelopmentMekong/opendev-wptheme#980]
There is a problem with link copied from the Cambodia Daily English news source, which resulted in unable access to the original source from ODC site. (https://cambodia.opendevelopmentmekong.net/unionists-freed-after-strike-called-off-in-kampot/#!/story=post-95646). From back end, editor has copied the exact address which appeared on the target news, but how it is presented from the front end of the news when published on ODC site appears differently, with double http (see attached image), making the link dysfunctional.

![issue](https://cloud.githubusercontent.com/assets/10954244/16678652/563fd494-450b-11e6-8bc6-f1cddf46d2b5.JPG)

**Comment by Huyeng** [comment]
fixed.
