### ISSUE TITLE
ODM News map basemaps not working

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#984]
Hi all,

OSM basemaps are not working on ODM news explorer currently: https://opendevelopmentmekong.net/#!/

![image](https://cloud.githubusercontent.com/assets/1206387/16762715/e7363ab4-484f-11e6-85da-6a0ac10f714e.png)

Error message states 'Mapquest direct tile access has been discontinued from July 11', but ODC does not seem to present this problem. and is using an ODM basemap:  https://a.tile.openstreetmap.org/{z}/{x}/{y}.png

This basemap does not work on ODM. @Huyeng Could you look into why this works on ODC but not ODM?

@prustar Any suggestions for alternative basemaps in the meantime?

Thanks!

**Comment by acorbi** [comment]
@DBishton @Huyeng Changed basemap to OSM on ODM as well. mapquest has cut access to its tile server.

@prustar please indicate it OSM is good for the moment or we should think about using other base map as default one. Please mind that the news section on the v2.0 is going to be on https://pp.opendevelopmentmekong.net/news-article
