### ISSUE TITLE
Editor functionality missing on OD Myanmar WP instance

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#987]
ODMm editor does not feature extended functionality, please see screenshots below:

OD Mynamar:

![image](https://cloud.githubusercontent.com/assets/1206387/16833274/c1b02b62-49d8-11e6-8725-4061e86b42f8.png)

OD Mekong:

![image](https://cloud.githubusercontent.com/assets/1206387/16833307/e9822c94-49d8-11e6-9e64-85a0d426f4ff.png)

**Comment by Huyeng** [comment]
The second bar is there now. 
if it is was hidden, please click toggle toolbar likes the screenshot below.
![screenshot_8](https://cloud.githubusercontent.com/assets/6613530/17163015/532ccf80-53e5-11e6-8980-136edb5c0e99.png)
