### ISSUE TITLE
The the sub menu doesn't show correctly 

### ISSUE THREAD

**Issue by punwath** [OpenDevelopmentMekong/opendev-wptheme#988]
When add more sub manus, the main menu doesn't show correctly. 
Those 4 sub manus should be under the Hydropower
![image](https://cloud.githubusercontent.com/assets/18112596/16941067/0c9aec10-4db8-11e6-96a7-a563a517f022.png)

**Comment by acorbi** [comment]
@huyeng @punwath fixed and deployed on PROD. 
![screenshot from 2016-07-20 10-35-41](https://cloud.githubusercontent.com/assets/384894/16980368/ed221e18-4e65-11e6-89df-b187301d0fac.png)
