### ISSUE TITLE
Implement breadcrumbs on topic pages

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#99]
Currently, above the title on topic pages, a clickable list of categories is presented for the user to be able to browse through contents:

![bildschirmfoto 2015-05-21 um 10 56 12](https://cloud.githubusercontent.com/assets/384894/7746088/085a297e-ffb0-11e4-99b2-bd4ed8297517.png)

Optimally, this tags will represent the hierarchy of the page's taxonomy and provide real breadcrumbs functionality.

For doing this, a function needs to be implemented that takes the page's current category ( or the lowest in the hierarchy) and goes up till the top parent, adding clickable tags in order.

**Comment by Huyeng** [comment]
I create a breadcrumb function to demonstrate the topic navigation, and it also works for the whole site. 
Here is the screenshot of breadcrumb of topic page, Hydrowpower page is an example. 
![screenshot_28](https://cloud.githubusercontent.com/assets/6613530/8075210/afb2c2c8-0f67-11e5-8745-b734aada7d19.jpg)

As discussion with @DBishton  and Terry, the breadcrumb functionality will apply to all the pages of the site except the homepage. However, for the news post, there is an issue with the hierarchy, whether the hierarchy link to category or what else, that need further discussion. For temporary, just hide the post category of the breakcrumb.
![screenshot_31](https://cloud.githubusercontent.com/assets/6613530/8080335/d68cd856-0f95-11e5-867e-a5d197020e98.jpg)

This is the breadcrumb of page looks like: 
![screenshot_32](https://cloud.githubusercontent.com/assets/6613530/8080345/e80b6fca-0f95-11e5-9cc8-9e0f1a65a8a4.jpg)

**Comment by acorbi** [comment]
:clap: beautifully implemented!

**Comment by Huyeng** [comment]
Done.
