### ISSUE TITLE
Miss Contact button and Footer of site

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/opendev-wptheme#991]
![screenshot_5](https://cloud.githubusercontent.com/assets/6613530/17051592/9da86f1c-5023-11e6-9c8f-6c47599f96e7.png)

**Comment by acorbi** [comment]
@Huyeng I checked and plugin is enabled for ODC PROD...

**Comment by Huyeng** [comment]
it may affect from any css. I just update the css to display the footer and button.

**Comment by acorbi** [comment]
Fixed. @huyeng, @DragonVirus, @S-mardii  do not forget to close the issues. For doing that automatically, you can specify `Fixes #ISSUE_NUMBER` as part of the description of the Pull request and github will close the issue for you :-)
