### ISSUE TITLE
ODC main menu "MAP" function is showing 404

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#995]
Please note -- If you click MAPS on main ODC MENU you get a 404 error

It points to:
https://cambodia.pp.opendevelopmentmekong.net/map-layers

Instead of:
https://cambodia.pp.opendevelopmentmekong.net/map-explorer/

**Comment by Huyeng** [comment]
The url was changed to the map explorer instead.
